# [dbo].[TERP_COST]

In [0]:
USE [MikroDB_V15_1399]
GO

In [0]:
/****** Object:  Table [dbo].[TERP_COST]    Script Date: 4.06.2021 11:14:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TERP_COST](
	[GUID] [uniqueidentifier] NOT NULL,
	[MONTH] [smallint] NULL,
	[YEAR] [smallint] NULL,
	[CODE] [nvarchar](50) NULL,
	[COST] [float] NULL,
	[LAST_QUANTITY] [float] NULL,
 CONSTRAINT [PK_TERP_COST] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TERP_SEMSI_PERIOD]

In [0]:
/****** Object:  Table [dbo].[TERP_SEMSI_PERIOD]    Script Date: 4.06.2021 11:14:23 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[TERP_SEMSI_PERIOD](
	[GUID] [uniqueidentifier] NOT NULL,
	[YEAR] [smallint] NULL,
	[MONTH] [smallint] NULL,
	[NAME] [nvarchar](25) NULL,
	[MILADI] [nvarchar](50) NULL,
	[START_DATE] [datetime] NULL,
	[END_DATE] [datetime] NULL,
 CONSTRAINT [PK_TERP_SEMSI_PERIOD] PRIMARY KEY CLUSTERED 
(
	[GUID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[TERP_COST]

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0d1004d5-5987-4a1f-9c41-0057ddb500bf', 2, 1399, N'1001669', 23853.211, 45)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a7ef0263-64bc-4dad-aafe-005d41d6eaae', 1, 1399, N'1001287', 60173.21964579256, 630)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ae7e6213-d1a7-4428-83b9-0067674734eb', 1, 1399, N'1000867', 116724.56283337275, 1680)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cab0b18f-c639-4aec-952c-00803e15955d', 2, 1399, N'1000859', 56688.094172516496, 1893)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'154ce4cf-a6d3-4896-8a2d-00a8d9ff4629', 1, 1399, N'1000269', 22269.798453182953, 841)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7e82a31b-f8c1-484c-8aef-00c361214171', 2, 1399, N'1000268', 22296.469453149391, 1132)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a3265e8a-188c-43df-94bc-01030a9f6a45', 1, 1399, N'1000899', 31459.80113121972, 1072)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bad5291a-8338-4783-bdbd-01183babadf7', 1, 1399, N'1000466', 14062.889999999998, 65)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'98bbd546-f3c2-4b0c-afca-012c5cdb384e', 2, 1399, N'1000403', 145871.56, 3331)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9a0a1892-a47c-4cac-b54e-0162e45701fd', 1, 1399, N'1000993', 36742.890000000007, 326)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'853569fb-e19f-4f42-9581-019653edb0d8', 2, 1399, N'1000770', 39866.960542850786, 6134)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'79ca4be7-1ce3-459b-a117-01c9ff8cc8f8', 2, 1399, N'1001199', 23944.9538, 8115)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9ec37e25-cad4-484a-a1cf-01ebf75aad0c', 1, 1399, N'1000670', 70659.658019656708, 1735)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'084ea5e4-138f-4a9f-8666-01fcf51ee365', 2, 1399, N'1001675', 207095.80246913582, 3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ac2d00e4-34f1-411b-a0fb-0208e997bb8e', 1, 1399, N'1000235', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eee6cdfc-fb2c-49e6-9272-0211cfe55ea9', 2, 1399, N'1000404', 18074.797517895528, 4487)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd256d45b-0734-4b2a-b8c5-022817a54d9a', 1, 1399, N'1001030', 19266.179999999997, 59)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b47b0adc-86db-4b57-8bc2-022cf6cb510f', 2, 1399, N'1000719', 157310.47698425656, 480)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2f30fdec-5231-4d41-ac0a-025daa9648c6', 2, 1399, N'1001620', 65137.615, 1730)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'31d09047-21c7-47ab-8e2e-02aaa04bf612', 1, 1399, N'1001296', 149894.89768439104, 459)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'feacf05a-92ce-4548-9e30-03091507cc20', 1, 1399, N'1000733', 66054.96, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6d2e389d-46ac-4d85-a8da-030a0eac394a', 1, 1399, N'1000972', 14131.616088547302, 1716)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7c6c1268-e8e1-4c42-ad2d-031b80022fc4', 1, 1399, N'1000353', 64403.950000000004, 379)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b0b13645-239a-45d8-b696-032fbcda4b07', 2, 1399, N'1001447', 45660.999756189609, 923)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'37a2263f-79b3-4532-ac04-0360b12e0f49', 1, 1399, N'1000592', 75004.820000000036, 4102)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f4ccf89d-d37e-4d8f-ac94-0384016b49ac', 2, 1399, N'1000956', 123322.62805951334, 2638)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'73407e8a-01ff-4957-91d5-03a1f0645f03', 2, 1399, N'1000837', 109174.312, 2810)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a587c372-5870-45cd-b8d8-03b857697cbd', 1, 1399, N'1000706', 161652.05817861858, 1915)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'881759e5-73b3-465b-8c5d-03ccb97043f3', 2, 1399, N'1001584', 172018.349, 39)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7f5c28e3-2cd5-4684-9af9-03cd6084591b', 2, 1399, N'1001068', 44807.156830869681, 474)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b23b805b-1aea-406e-a24c-03e160571c34', 1, 1399, N'1000275', 17479.13, -15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fdc45026-2871-44f8-9895-03e25b2d5368', 1, 1399, N'1000372', 126165.62000000001, 249)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1c85a41f-910d-472d-a0e2-03e98c478dd2', 1, 1399, N'1000297', 26052.515279183161, 2815)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'51a2c05d-b3ae-4af2-ba0e-03f28af31845', 1, 1399, N'1000162', 59358.405139225542, 1406)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c1a14270-d506-4349-88bf-03f80a541e3c', 2, 1399, N'1001373', 3349.486661314254, 21106)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4dc740ab-9480-429c-9c10-04245e14b4e8', 1, 1399, N'1000453', 109918.89978962709, 2124)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dc3ac040-ed0a-4c67-91c7-04379ffd3727', 1, 1399, N'1000153', 150068.44287342089, 9060)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f7e8b583-5232-43bc-bc92-0445b62a8355', 1, 1399, N'1001342', 31814.260864636602, 2424)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fadaca49-9a14-4004-99dd-045f1b0d6f5b', 1, 1399, N'1000031', 60434.74, -6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c7813d79-f183-4e2e-ac41-047a9284aa79', 1, 1399, N'1000699', 268491.63899761223, 645)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f2a7d19e-0bad-42ed-b926-0481d5f2d6f1', 2, 1399, N'1000777', 165137.61500000005, 1800)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dd691b98-31b5-4df3-a741-0496440f2829', 1, 1399, N'1000991', 67159.42, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f635345a-11bd-4c5e-8f6e-04af703189d3', 1, 1399, N'1001125', 28499.97, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'601bf213-56d7-4f81-99b3-04cfbcb7a657', 1, 1399, N'1001397', 7065.9373666080191, 19788)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9651a0d7-c6d9-4eac-9784-04dcaca5b23f', 2, 1399, N'1000705', 175788.7698724645, 2844)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b1c26082-7b7f-4b26-b4a6-04dcc4226ecd', 1, 1399, N'1001612', 99030.965048496015, 3865)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd6458aac-1888-445c-a563-04e0690eb78b', 2, 1399, N'1001688', 152158.60428231562, 5470)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e1b40220-5e2a-4bf8-826d-04faa73c5be1', 2, 1399, N'1000020', 42537.399863172119, 3610)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'185edb30-027b-40c0-9b5a-04fea7760f44', 2, 1399, N'1000506', 7064.3548933798511, 31120)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd7cedd88-7d02-4f5f-a17b-05157a55e482', 1, 1399, N'1001490', 33100, 233)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ec3465fc-8dbe-4696-8e86-05269e0add73', 1, 1399, N'1000636', 209404.53, -3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c94ca1b0-9a8e-4bc5-8d4c-052769cc6b22', 1, 1399, N'1001089', 494085.43560606061, 1615)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd29094bd-6f2e-422d-abee-053bfa56c304', 2, 1399, N'1001582', 38509.131054047262, 3718)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e9df84c0-3f67-4a65-a06c-0544038c12d6', 1, 1399, N'1001409', 98679.050000000017, 3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e2a85aa0-3fd1-4a14-9b8b-056f78970dca', 1, 1399, N'1001518', 202752.06038423648, 1088)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3f1c0a71-53df-4acc-9917-0579ca8b68cd', 1, 1399, N'1000236', 103198.63, -1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8e4deb90-ce34-43d6-b36f-05a5e0cfa4e4', 2, 1399, N'1000668', 63584.077380861228, 4817)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'39d6ddd7-1544-4c27-82f1-05db4b0de7ca', 1, 1399, N'1000894', 30654.664752035424, 1453)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b1b6d492-800c-4c98-afb8-05f193af30e3', 1, 1399, N'1000517', 42414.114338569882, 3135)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'42bf6d9a-1b48-43d1-8e86-05fbced55f34', 2, 1399, N'1000990', 190734.06819505218, 642)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5ef44755-1708-45c7-baa0-05fd69afb93d', 2, 1399, N'1000030', 84419.719524291562, 1441)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1b545d35-bb1b-419c-87ea-060444cf24e9', 2, 1399, N'1001536', 60550.091127798842, 3556)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd3c894af-5aea-4d4c-889e-06169017faeb', 1, 1399, N'1000875', 61065.999221590959, 17853)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a711db98-1b8a-4d4c-a1fd-064a5f85f0b7', 1, 1399, N'1001358', 77174.736347538055, 3652)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b9c83ca5-724e-420e-96b3-066761ffb975', 1, 1399, N'1000331', 17068.214934116055, 5808)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'af1f491d-e454-4d0e-8f57-066ce118ee25', 2, 1399, N'1000310', 134128.78197194758, 1012)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'52a76d44-ea56-4248-9633-069abefbf151', 1, 1399, N'1000001', 33676.05888721579, 13542)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3bd59809-b186-4d6b-8d89-06b1bfb4289e', 1, 1399, N'1000836', 81928.335611591247, 1775)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'89afcbc5-0003-4655-91e4-06b7656cca6a', 1, 1399, N'1000250', 69486.40674596114, 2266)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'46f1d6f3-fac5-4d9c-98d3-06bc0b92ddd0', 1, 1399, N'1000350', 144178.26675090607, 3804)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b5f298ee-39b5-41d6-80a3-06d2c0d53d1f', 2, 1399, N'1000883', 38533.494789080709, 6703)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'61d080ce-092e-4cf2-a4ae-0700680bc172', 2, 1399, N'1000365', 119266.05499999998, 187)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3e581634-bb67-4622-842e-0711c5ae8a9e', 1, 1399, N'1001341', 31759.549999999996, 2368)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'694d2e6f-6042-40e5-a712-0725abea040c', 1, 1399, N'1000955', 30879.56, 34)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dca94acd-af6a-4933-9e76-073188a9c6bb', 2, 1399, N'1000349', 27466.639953535509, 10921)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'346eb447-4dd0-437b-be68-07448eae35dc', 1, 1399, N'1000931', 77538.225761044785, 297)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dc5164f1-9da4-4e28-a62a-074f9a95655d', 2, 1399, N'1001665', 85568.1267474371, 2427)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'58ba9305-2932-4075-a792-077fe1d6b59f', 1, 1399, N'1000704', 162419.76636470959, 2113)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5a01eb60-07c1-497c-a9f0-07881dac17bc', 2, 1399, N'1001644', 200970, 1843)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a8222340-fd8f-43f4-aaa2-078bd3fd7e2a', 1, 1399, N'1000547', 113944.72933068981, 656)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'db2230b7-df57-49bb-8930-07d446c04338', 2, 1399, N'1001056', 160550.459, 1257)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c7663959-91c0-4880-b946-07e6add8d81e', 1, 1399, N'1001300', 92893.923895287939, 977)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9da4cb60-e15f-4f77-a28c-080b419e8a2e', 1, 1399, N'1000202', 23884.242238646704, 3812)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3ef3dd4f-9747-49cc-ba15-083d773fa8c7', 1, 1399, N'1000085', 45445.131889995595, 4927)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc1d3e36-e301-491c-b9c0-085d63008f5c', 1, 1399, N'1001622', 48223.43760033889, 2074)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b352bd59-b9e0-47d3-911d-088d6fe602a9', 2, 1399, N'1000170', 14400.427355156429, 4613)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'69f5a98c-65ea-43b7-81b1-08a124851adc', 1, 1399, N'1000101', 49652.120965093731, 2274)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b07a2624-c3be-4d87-9e92-08ce6c8c8f7c', 1, 1399, N'1000426', 115688.34012222223, 53)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2abbc901-f57f-496b-bc1f-08d5f287127e', 1, 1399, N'1000366', 94302.576653929849, 2661)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3081c1bb-23f2-4b8e-931f-08d7760b7183', 1, 1399, N'1001073', 22100.87, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a2762c7c-2e31-4aac-b2d0-08fad986c482', 2, 1399, N'1000721', 54657.46017651639, 814)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'496e0355-3bc4-4fbf-980f-08feb91b737b', 1, 1399, N'1001454', 138000, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1de2d294-496e-4a8d-931a-09516d361ab1', 2, 1399, N'1001317', 61252.639716327321, 4889)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd5749a76-ad33-4871-9bd9-095d4c294708', 1, 1399, N'1001511', 85380.327678451635, 2881)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e72961cc-9f8a-404d-bb1c-0991eddaabf4', 1, 1399, N'1000172', 83860.46367035115, 2070)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'95d1d809-e8df-4010-853d-09e4411d4b24', 1, 1399, N'1001121', 124999.93, 6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c9ffe830-00e8-4838-8cd9-09e8b297f5f2', 1, 1399, N'1001492', 56000, 160)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'852b6730-f8aa-4c73-b5dc-09eea734f03b', 2, 1399, N'1000179', 98018.5138712959, 3840)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'13e95a98-774a-4fe0-83d0-0a44239649f4', 1, 1399, N'1001097', 111861.04, 450)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ee5641a3-fbc0-40f6-a940-0a623ebf80ee', 2, 1399, N'1001036', 83353.0092200334, 1946)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f6ef1343-5589-4d5a-89b3-0a7b8c2248c8', 1, 1399, N'1000960', 257296.34977966492, 1547)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'688865f2-ee0c-4e53-9c04-0a8238fbec9e', 1, 1399, N'1000567', 241325.36, -2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'edf43a2c-4ae2-4924-95c1-0a90c125433a', 1, 1399, N'1001422', 52852.131770100081, 1913)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5a09f74e-df3e-4a53-8276-0aa280711bee', 1, 1399, N'1001471', 43028, 398)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eaf4d799-51e0-4d40-8e6e-0aaaafba0199', 1, 1399, N'1001350', 28514.205163272596, 5844)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'311b27c0-f686-4cf7-9020-0abb3ed30bd7', 1, 1399, N'1000624', 158551.09224277013, 736)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'df6ec728-ac59-4b99-8c23-0ad9f91a44d9', 2, 1399, N'1000539', 129000, 1695)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'827209d3-50cf-4991-8d33-0b3883f25922', 2, 1399, N'1000402', 37798.165, 6026)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6731701f-a812-4324-b1d1-0b5c5b3c781f', 1, 1399, N'1000081', 61555.294483098674, 5239)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ebeb339a-4438-4615-b0ff-0b6f99b2b6ad', 1, 1399, N'1000761', 33207.795939349133, 18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'550f9955-2cd6-4311-b5de-0b7d8a93d5cc', 1, 1399, N'1001568', 151489.68965607276, 993)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'09ec9bde-d804-4fd0-a912-0b99638a22b5', 2, 1399, N'1001619', 136700.70055417763, 2461)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a84cafd4-6e55-4fea-bd3e-0bb19a4bd0d9', 2, 1399, N'1001104', 2960999.9410810908, 373)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'107abda6-e245-4310-90f9-0bd3aaf4eddb', 1, 1399, N'1000846', 210000, 5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7e1f8485-bc2d-4637-9720-0beaf3986e59', 1, 1399, N'1001394', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bf1976aa-684e-4aa8-ae9a-0c4d52d87f0d', 2, 1399, N'1000715', 244322.23174248741, 759)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'201aceed-7e45-4f9e-9e60-0c6e00e20f32', 1, 1399, N'1000204', 16799.989999999998, 1136)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'98873adc-4a8d-4ade-b2f0-0c87b04519d4', 1, 1399, N'1001353', 50437.589597299913, 1981)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bff1f0ec-d428-44e6-bc86-0c95c49acad5', 1, 1399, N'1000820', 69826.22, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ebc74121-2d77-4c91-a0f8-0c9c222c8212', 2, 1399, N'1001116', 69108.225623249964, 1406)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd032c6a3-0605-43cd-bfdc-0ca229c8bf12', 1, 1399, N'1001574', 98051.403755818712, 3564)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3f7a6222-9881-48a6-a5f8-0d0e480a6c9b', 1, 1399, N'1000185', 26250.360453141093, 139)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'41f42f36-e437-4872-ac5d-0d10fad7591d', 1, 1399, N'1000992', 18779.919999999995, 975)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'945e67ea-89dd-425c-bb8d-0d1b03353fcb', 1, 1399, N'1000483', 72018.3728353604, 3937)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5e7736ce-cb79-4254-a801-0d1b9886fbbe', 1, 1399, N'1001276', 175606.88488953488, 57)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'64b2b149-7529-4467-881b-0d267c337c32', 1, 1399, N'1001082', 77981.86, 6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6fc80dda-5cbe-45af-b807-0d55d825776b', 2, 1399, N'1000573', 7064.022481905412, 2619)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c6a70b56-a7a0-4ec2-bbc3-0d84ddba270a', 1, 1399, N'1001309', 77186.001274111957, 1585)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c0ea7f88-d4d1-4206-90c6-0da4a5b0d5bd', 1, 1399, N'1001311', 110058.67315252956, 1813)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ac9d71e1-9c04-4ecb-bc3b-0da82d9981e2', 2, 1399, N'1000166', 209164.34925864911, 184)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fdfffa7a-43bf-4814-8785-0db16f468bdf', 2, 1399, N'1001339', 267432.03835757315, 1217)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cf1a3b7d-4f1d-4260-9da7-0e4e48612208', 1, 1399, N'1000890', 16629.290027207109, 5728)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b09f99dc-49d6-4b6f-b874-0e69d62179b4', 1, 1399, N'1000152', 21715.027512442481, 7724)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'88286cf0-5eb3-4887-91bf-0e73e8864b61', 2, 1399, N'1001272', 68702.517313084492, 2176)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c575fc24-8956-49b3-b351-0ea6aa3a33d5', 1, 1399, N'1000626', 10389.280246049444, 14446)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'01b38543-652b-4518-a088-0ea80472d458', 1, 1399, N'1000188', 15000, 1246)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'28350b01-0cca-462f-8f37-0edcb96f05f7', 1, 1399, N'1000711', 44060.801889688693, 4449)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1f958269-9dbf-4ad1-ba83-0ee9cd8080f5', 1, 1399, N'1000480', 98537.990000000034, 81)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'39d7107e-0e1e-4df0-8a05-0eeb4c4665f0', 2, 1399, N'1001495', 56653.585111529166, 2728)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd7018303-e9b5-484e-8e9c-0efc29229351', 1, 1399, N'1000782', 431778.95731910755, 1450)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'301de889-3045-4e3d-a304-0f2c603b7f20', 1, 1399, N'1000881', 38532.904069839213, 3501)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'579a83ea-dcd7-4ad8-abb8-0f4870a4ac3f', 1, 1399, N'1000941', 33885.69353094363, 1600)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'19bb0253-6126-423e-b3d5-0f523184a7f7', 2, 1399, N'1001431', 48362.458208057724, 752)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'80f8c44b-fac6-4232-8fef-0f59984db61d', 2, 1399, N'1001332', 48200.567236580515, 4648)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2c55a638-0cf9-4dc6-a943-0f7d5452aea6', 1, 1399, N'1000128', 158256.17000000004, 12)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'23bfb217-0db3-4127-b10c-0f7da7ab38ca', 1, 1399, N'1001433', 14907.856864279576, 1325)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fbb31bc1-fda6-4b51-839d-0f8a1cb44afa', 1, 1399, N'1000428', 147763.48532763534, 186)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bab77801-a135-46d0-8248-0f8a9740e081', 2, 1399, N'1000327', 59736.155527905052, 6787)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0f0ac1af-ba3c-4706-81f8-0f9d3e2522d0', 1, 1399, N'1001560', 62935.199117110533, 3679)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'de2d17a3-cd21-47a5-97c7-0fcc7aa8e24c', 2, 1399, N'1001432', 96665.854014598546, 586)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'92d80693-60e4-4d52-8c4f-0ff490f61cff', 2, 1399, N'1000087', 23852.979725694677, 2802)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bfe68b80-97a3-4c8b-9f59-0ffb5eb9bbde', 1, 1399, N'1001160', 185531.65999999997, -9)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f73a7f2c-32b8-493f-9f51-0ffc531a41c2', 1, 1399, N'1000989', 59450.350000000006, 42)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ca65edb2-59bb-4f49-8533-10543131368d', 1, 1399, N'1000585', 14130.667459158341, 436)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c2d1e244-739e-4814-a70b-10a0cd244c3d', 2, 1399, N'1001404', 230275.229, 1163)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5729043f-0f9b-4ac1-bf95-10c53cf9a431', 2, 1399, N'1000082', 45392.609294018708, 2646)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0cdf7ac9-b4cf-4f44-99e3-10de319f01f7', 1, 1399, N'1000505', 3533.0635149001346, 20044)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0a72ee56-bf17-492e-84ec-1111482bbaf3', 1, 1399, N'1001642', 153315.85701183236, -140)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9069d84a-5610-40e3-9e2e-111b69813bb7', 1, 1399, N'1000707', 379915.39326172048, 288)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0c899ac2-a77a-4c69-a4a2-1123e0ef708e', 2, 1399, N'1000027', 78878.956529921925, 1575)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'10f2ff40-c765-416f-a2fe-115cfc0c34ea', 1, 1399, N'1000591', 70648.912794845834, 449)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'05c4d4c5-afd0-4274-872b-1167aa7bf7c8', 2, 1399, N'1000108', 80999.967178442064, 2370)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b34ec238-fb61-4208-bb86-11998826d022', 1, 1399, N'1001174', 44454.26999999999, 7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd894906a-afa3-4da0-b1fc-11feaee0ad86', 1, 1399, N'1000947', 182012.90288949542, 5769)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2cd645b8-7be7-48b4-86dd-120821d38481', 1, 1399, N'1000997', 21192.895941722909, 1760)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6b1fad7e-5aec-4e60-9bf4-1229b17b0477', 1, 1399, N'1000755', 214560, -13)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b588e3de-25e0-46db-81eb-1238810714e3', 2, 1399, N'300003', 160000, 22600)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f7f5e082-a8cb-4790-839c-12408cb7405c', 1, 1399, N'1001010', 88578, -133)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'02a0a25a-5cdf-4a2a-a948-124f382e88bf', 2, 1399, N'1000121', 411500.96716268122, 994)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ca27d47a-24cc-4d22-bc51-12bad410fc39', 2, 1399, N'1000158', 189000, 1044)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9168bab9-a23a-4873-8daf-12d6c5509a3c', 1, 1399, N'1001541', 20712.275892488895, 7155)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9668c444-49b1-49b3-8d37-12fbf5899652', 1, 1399, N'1000806', 768794.12051292066, 444)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'86f4570d-b303-4b2b-ba5a-130abcf18024', 1, 1399, N'1000774', 36747.221814781049, 988)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0d40dfc1-23c6-4125-9bcc-1317840f39ad', 1, 1399, N'1000500', 53208.552464914574, 973)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5bd5485c-5bf6-43f4-b9d0-13361e61658d', 1, 1399, N'1000472', 9792.9199999999983, 16538)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b899ced6-3496-4e65-8727-1357a7614c7a', 2, 1399, N'1001734', 18165.095999310393, 9675)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c5e8f740-9bc2-4966-9a72-13c4b5f9f60f', 2, 1399, N'1001364', 30275.229, 2383)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'248eb694-7852-4e13-a897-13e1948b0185', 2, 1399, N'1001569', 100342.39503339384, 938)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c809dd63-f30e-4c7a-ba29-14076800d8c5', 2, 1399, N'1000701', 111022.65998703904, 4039)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'46662c9c-00a9-4c1b-b727-145c2363cb45', 1, 1399, N'1001081', 77981.76, 5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b66228f0-cd14-45cc-a775-1460f663ef3a', 2, 1399, N'1001497', 212916.99208037331, 293)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8498a225-900e-4ed5-b12c-149b7ed49665', 1, 1399, N'1000043', 7669.4699808954238, 9027)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a3b3c9be-4eaf-4853-aafb-149bb559f734', 1, 1399, N'1000897', 29897.94, 2049)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9fcaab16-6af9-4ce8-9973-14a387a1f8a7', 1, 1399, N'1000969', 249984.03999999998, 5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3a05afc1-f416-4f0f-9a8e-14aa08c3ac00', 1, 1399, N'1000404', 17947.669486236453, 5224)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6b4b6b0f-5ad1-49dd-a3f8-14cad440e4d0', 2, 1399, N'1001558', 143944.954, 1015)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'52596f51-f075-44ed-8627-14ce4c60d171', 2, 1399, N'1000559', 157796.24377610072, 6212)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a3c34d56-efc8-4753-a6c9-14d058759f3f', 1, 1399, N'1001108', 83662.071694066108, 11314)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6c90f66c-679f-4a8a-9a0e-14d9dbabf439', 2, 1399, N'1000717', 25589.993161998307, 4137)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d3a7b80-866a-4801-9dd4-14dc07fb53de', 2, 1399, N'1001359', 82568.807, 2707)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd5ebaa48-7b85-43bd-b2c2-14f135500016', 1, 1399, N'1001654', 95670.180215239146, 881)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'19af3b7d-b42e-4a73-a4d1-1547bcfaeac4', 1, 1399, N'1001136', 136423.96, 15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e98cadbb-313b-46ed-95e6-15524c465de8', 2, 1399, N'1001316', 435000, 141)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fba90dd1-bc78-4993-a03d-15540a465c49', 1, 1399, N'1001551', 68807.37, 1101)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b6891c97-0abe-4167-a6f4-156d7dd5b2cd', 1, 1399, N'1001360', 98354.788603772773, 841)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'92f90d45-9d38-47b6-b23c-156f87716f2a', 2, 1399, N'1001696', 145666.11175287748, 1099)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'39abc385-0028-4828-8bbd-15c37efecd4b', 1, 1399, N'1000201', 17129.772123455019, 4475)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e21542a5-25ec-468a-a788-15d3f1d79863', 1, 1399, N'1000548', 76199.726005769437, 978)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'87027bdc-5730-4948-a8f2-15df5593ad1b', 1, 1399, N'1000046', 64157.1282186491, 2372)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bedc05f9-73ce-4e91-82c6-15f42544da2b', 1, 1399, N'1001027', 588042.18967436976, 518)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9d97a81b-c917-4fc4-8349-15fc627ec913', 1, 1399, N'1001076', 11150.98, 3677)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bab37e6f-843d-478b-ac5e-16037053aec7', 2, 1399, N'1000154', 230118.75480399691, 2783)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3d94b89c-1ac8-4acf-a28d-165501b333a6', 2, 1399, N'1001679', 117479.02250456052, 8852)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7192871a-c034-45de-bc49-166924d7ecd4', 1, 1399, N'1000705', 155972.46854555284, 1940)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6d45e31e-c35d-4d05-aed9-1669c75f1c30', 1, 1399, N'1001572', 17135.954602827296, 5397)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ceea6253-a47f-4bae-aaf5-1683dcd7fed6', 1, 1399, N'1001544', 144330.67, 408)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'40dc1533-6b47-4343-83d6-168c105a5f42', 2, 1399, N'1001274', 36746.604417641349, 23147)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'03126ade-deac-40ea-997c-16ab944a5143', 1, 1399, N'1000781', 41146.482313579087, 740)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fb3e65b6-1222-496f-8e7e-16d453ff149f', 1, 1399, N'1001222', 90897.087068576264, 4540)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c3b96dbe-5197-4376-9a9f-16ef7b10d565', 1, 1399, N'1001291', 700909.09, 7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd9bc11ed-c396-4f68-a254-17051a23973a', 1, 1399, N'1000842', 237758.26091706651, 543)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'93e049b0-77df-4228-b6bb-174462470cfe', 2, 1399, N'1000143', 80526.575832140719, 2150)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8ce91dbf-5ca4-4448-901b-1758c4fca987', 2, 1399, N'1000997', 19997.371815153569, 604)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b2add38e-ea4f-400c-b588-175a916087d2', 1, 1399, N'1000373', 147423.12, 40)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'73073a17-90b9-4f9a-84a3-175d10c1d91e', 2, 1399, N'1000354', 51604.853831596716, 2862)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c1809cf8-2d19-4c4e-93ef-1786ec634f19', 1, 1399, N'1001218', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b7d71ec3-29ee-4d9c-bedb-17a16847bb93', 2, 1399, N'1001695', 64211.728977266474, 1652)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1e382aa6-79b5-490c-b04d-17ce140e4e5c', 2, 1399, N'1000152', 51075, 4841)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c2b047fa-5fd4-44b0-b67d-17d6334bf2ab', 2, 1399, N'1001285', 44927.928681950973, 11080)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd9a2eb5b-94d6-40d9-a4c9-17dc28f2a215', 1, 1399, N'1001273', 18781.796356038321, 51693)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3bf84c3a-200a-481b-a78e-180207eb13e1', 1, 1399, N'1000239', 67432.531591761581, 680)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c45d812b-9b45-47cc-a593-1804afb45771', 1, 1399, N'1001626', 185015.77287066245, 32)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'926db2bf-dfe2-4816-adcb-182cae9093a5', 2, 1399, N'1001711', 133684.90453673236, 2999)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bba4dc28-674c-4ee4-ba39-184f7c27bd3a', 1, 1399, N'1000783', 166972.03999999998, 16)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a7808da9-d9a3-4d92-9cd1-185cafdf71f6', 2, 1399, N'1000737', 72477.064, 476)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'be9048b0-4196-4539-b136-185e38cbe108', 1, 1399, N'1001096', 22313.133920709151, 2216)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ce1c1ba7-de35-42ec-aed1-1866fc9ab116', 2, 1399, N'1000977', 27716.744148619095, 630)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e38be289-4090-40d0-9322-186c84abe9ab', 1, 1399, N'1001221', 85001.7262345088, 3158)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'25cabf06-a49f-4743-bba7-18adbd29fea0', 1, 1399, N'1000864', 56751.606537317275, 1432)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bc602ee9-54b4-4e07-9aa2-18dff0e62cd3', 1, 1399, N'1001416', 134491.14795168056, 2336)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fec5fff7-aee7-4fa7-a3f1-19104de8ee93', 1, 1399, N'1001460', 45000, -3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bbda47c7-0d59-401c-b8ed-191380541cbd', 1, 1399, N'1000047', 86632.17, -5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6f988e77-917f-40e5-a7dc-195c1aa3d914', 1, 1399, N'1000763', 7064.5301758752721, 12248)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eb6dfd61-585d-4505-82f1-195c91112829', 1, 1399, N'1001510', 153193.67652960602, 801)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd91814d5-55b2-4422-a579-19ec864d24e8', 2, 1399, N'1000655', 8715.596, 10655)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3744c59e-583b-4a80-9d63-1a796b71816a', 1, 1399, N'1000474', 622050, 9)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'97835fdc-aaff-4d33-9a75-1a99a9ba5b6d', 2, 1399, N'1001580', 283405.77482917218, 1348)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'706dec39-1430-4b97-af5e-1a9b74924079', 2, 1399, N'1001405', 6973.3512120351852, 7819)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd341c7aa-6518-48f8-874a-1ab52736f877', 2, 1399, N'1000608', 46238.571173671175, 6593)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3db0e79e-4480-44a1-807e-1ad2dccc141d', 1, 1399, N'1000064', 39090.763960891658, 740)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'87e66277-c5ff-4901-9417-1adf5aefa838', 1, 1399, N'1000813', 553649.598166421, 132)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'74c97542-e9d8-43fe-bab1-1aec78dcbb85', 1, 1399, N'1001170', 37631.56, 25)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'979a225e-7296-49a0-a9da-1af1d614262d', 1, 1399, N'1001333', 47710.2500613497, 4222)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7c37b575-8a5e-4ff9-961a-1af8c9078c2e', 1, 1399, N'1000760', 33226.048495634837, 24572)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'536ec8c4-cde3-4e94-9610-1b618b86bc69', 1, 1399, N'1000669', 64374.88, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd393f35d-898b-4391-b015-1b625af6f6d4', 2, 1399, N'1001268', 229000, 821)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'03995882-1ba4-4d37-9548-1b8d3acd24fb', 1, 1399, N'1000138', 177102.69278920308, 1815)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4847b8b9-21fd-4489-92d7-1b94339c842b', 2, 1399, N'1001718', 316350, 1216)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8b6096d5-840a-452d-be5e-1ba08e45bb37', 2, 1399, N'1000060', 158531.55937988311, 1048)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'36e4f63e-56fa-42eb-a9e3-1bc947da7f93', 1, 1399, N'1000582', 14131.45794499598, 1920)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'21350e39-f0b6-4ea1-b313-1bd41d1d5e5e', 1, 1399, N'1001508', 139459.63060138046, 968)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b42229ec-66cd-4a75-a613-1bf8932231b9', 2, 1399, N'1001712', 148623.92924194445, 3170)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'73dd2d5c-62de-4cfc-af6e-1c181051dc70', 2, 1399, N'1000116', 304015.61216105177, 3637)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6084b756-69dc-4387-8763-1c3ef44acba1', 1, 1399, N'1000853', 223020.85527151995, 1470)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f318c05b-cf1a-4274-87af-1c48b5d99cf6', 1, 1399, N'1001132', 76799.92, 14)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd0aba6ff-b653-4786-bc25-1c78e5876d8c', 2, 1399, N'1001529', 11926.488992012735, 8268)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bba7d6b6-1a94-4018-8d28-1c95699df62d', 1, 1399, N'1001214', 160584.81632789437, 1173)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7bd4cd79-4e87-44b5-8394-1caab9184246', 1, 1399, N'1000896', 30036.616041455698, 1116)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'176a75eb-93ef-412a-ad26-1cc2deaf8d6f', 2, 1399, N'1001398', 7067.0501546107125, 16836)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'237c9e41-57d3-4a02-a42a-1cf046d6ae9c', 2, 1399, N'1001638', 23857.315313653475, 3374)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1006e2ab-0158-44cc-84ee-1d026dc5ea4c', 2, 1399, N'1000459', 13762.443262456258, 14403)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e398b73c-52fc-4be2-b90e-1d1eb238a15e', 1, 1399, N'1000486', 231918.51556148037, -24)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'68123172-63be-406f-9e19-1d5833188854', 1, 1399, N'1000284', 15601.074814275926, 7979)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8ed6486f-2ba2-49e0-9ea4-1d6308a86af4', 2, 1399, N'1001710', 128210.98386953786, 1529)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'66f1b1b2-fbf3-4dad-a7b0-1d78199bbbf2', 2, 1399, N'1000229', 28000, 7663)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6d5d3fc4-6687-419b-9ce7-1ddb04a1bab7', 2, 1399, N'1000032', 84251.682341685562, 2119)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a4c53ae1-3821-408b-be73-1de0ae092f51', 2, 1399, N'1000174', 214597.41282565848, 698)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7adb46cd-299f-4b01-b5d7-1dfb05b8325e', 1, 1399, N'1000798', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b861c02b-96a6-483f-8b6e-1e000f72e716', 2, 1399, N'1001377', 127613.90021519993, 2896)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'62de26c7-ec28-475a-9de3-1e0574d0296c', 1, 1399, N'1001447', 42696.572398644319, 179)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'acc203f9-0dd5-4076-bf7a-1e0ecaa128cf', 1, 1399, N'1000990', 187446.13223867948, 918)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'48306c55-1fe7-4830-af73-1e1c9db23cca', 2, 1399, N'1001374', 56979.193520180961, 5763)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cfef3372-d623-4ab3-9bae-1e2cdce51fa3', 2, 1399, N'1001723', 115844.16619013935, 707)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'819034d7-095b-4aa4-8aea-1e77e1f80290', 1, 1399, N'1000808', 701173.15999999968, 153)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'29c7de59-998b-47b8-a7d9-1e826c68b7a6', 1, 1399, N'300004', 1001367.99, 3655)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3563969e-84ed-4c47-b420-1ea41623c1d1', 1, 1399, N'1000574', 7070.2337078864948, 2226)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3fb76399-49f7-403f-a6d9-1ea7e09f7f56', 1, 1399, N'1000965', 16298.42, 169)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'578a207d-1f39-44a8-a51e-1eafe7459506', 1, 1399, N'1001536', 60555.741798207921, 2710)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6311f186-6048-45e4-9d36-1ec402e3826a', 1, 1399, N'1001318', 80478, 3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c96e6de0-847f-4154-a31f-1ecf8056a55f', 2, 1399, N'1001535', 18569.625158723091, 17681)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a51e50fa-c95c-4ecd-814a-1ef0185e3747', 1, 1399, N'1000209', 701077.39205882337, 923)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5f21faa8-a978-454a-b992-1f2354489a96', 1, 1399, N'1000974', 7066.7006888032811, 2261)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4850c527-10b3-44c0-862e-1f41658a1659', 1, 1399, N'1001211', 22396.177498258869, 3384)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'075f8f81-06fa-46b4-951b-1f50f956c831', 1, 1399, N'1000113', 208729.01526520829, 2557)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c6435896-81c7-4471-8914-1f9565ba4c88', 1, 1399, N'1000917', 81902.62, 19)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'81986646-fbf4-4007-a2e7-1f98911cdb27', 1, 1399, N'1000240', 68612.554190125651, 1070)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e5b0b3de-c40a-4aef-acfb-1fbac77f5e08', 1, 1399, N'1000673', 14131.238512227203, 14914)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'63fd0c14-8394-4322-83a6-1fdb519a48ab', 1, 1399, N'1001258', 13478.859516596665, 3523)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'560d6f75-2389-40b7-808b-200527aaba32', 1, 1399, N'1000726', 29183.460000000003, 133)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0f4d011d-0517-4e67-80da-200c94720388', 2, 1399, N'1001100', 352306.50887573964, 2292)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'552f7cf7-c6df-437b-8154-20305b3f12ce', 2, 1399, N'1001263', 30761.976970334708, 24544)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ff01f488-daea-41a3-b425-203e195580e9', 2, 1399, N'1000966', 391241.06055538583, 168)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a3257432-7ea0-4511-a53f-203eee519f53', 1, 1399, N'1001588', 317890, 233)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dcdaadc4-93e6-4bd8-bde4-204e1663371d', 1, 1399, N'1001504', 343875.09, 395)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'55d0f1cf-c86f-40be-b831-20adc214c393', 1, 1399, N'1000252', 73398.462672645124, 2271)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'01720046-167a-4916-b510-20e38a14bc7c', 1, 1399, N'1001546', 630220.99447513814, 107)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0fa2fbca-b21e-4a15-a479-20ef4d449340', 1, 1399, N'1001178', 90065.48, 34)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'905eabbc-548e-4084-bddd-20f3ddc09fe9', 1, 1399, N'1001340', 31641.648606060604, 2312)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd0ad8fec-e9e4-4f5d-9f04-211297e8ba19', 2, 1399, N'1001642', 160550.459, -445)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e6caf6ce-f88a-4020-9917-213009d857bd', 1, 1399, N'1000605', 158164.49022759558, 2338)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c7802d1b-31b1-40a3-9b74-213b481c85de', 2, 1399, N'1000677', 22018.801282907731, 13953)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd83502b0-b47c-4fbf-b7c5-2156e473898c', 1, 1399, N'1000461', 10733.129068927441, 4358)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6b5abb20-89a7-4062-a835-2177bd5e52ca', 1, 1399, N'1000410', 48601.149999999994, 2318)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5d655655-555e-4f3d-81f3-21d17aaa28c5', 2, 1399, N'1000753', 173394.495, 610)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'926472cc-c58b-4744-b0ad-21e0218f2f00', 1, 1399, N'1000945', 296943.40343356458, 3286)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'14ee7c56-80bd-4606-aa21-21f14f960ece', 1, 1399, N'1000310', 120811.24617745851, 1404)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cd30525b-f26d-4c71-9a51-22031a5e44a1', 1, 1399, N'1001443', 291467.54, 1164)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'357d0c87-e5cc-4be2-8001-220795b0ffc1', 1, 1399, N'1000464', 21466.8102902442, 4276)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ae21b406-a9ba-4cd3-a810-220bdcb9194e', 1, 1399, N'1001123', 16999.98, -2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7eabdd79-0ed7-47a3-952f-22212693928e', 1, 1399, N'1001257', 29497.82715135836, 2956)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7839d753-5519-486c-bf6c-222bd464db5c', 1, 1399, N'1001565', 79944.133530132865, 2604)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a3fec7ea-f8a2-41e2-b568-2235cbd90f02', 2, 1399, N'1001190', 52023.831149619007, 2488)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5fc8bd30-aa77-43f6-ba0b-223ba4ea9527', 1, 1399, N'1000129', 110091, 9)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'78dc8521-a320-4c36-b18e-224a60a8390a', 1, 1399, N'1000980', 287034.97, 5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cfe163ea-4b0c-49de-940e-224bb1a834ea', 1, 1399, N'1000189', 22500.313238359959, 1859)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'02c84753-9d76-4ee9-ab4c-22634fb388d5', 1, 1399, N'1000674', 10616.204692171517, 7498)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd12c655c-3a02-4394-9692-22ba4eac7038', 2, 1399, N'1001501', 48740.871938940945, 4428)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e63cd184-3acb-4006-b87e-22c38cfc6265', 2, 1399, N'1001020', 135287.53786764195, 2351)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'269c8066-27a2-49b5-a8f8-22c84a532929', 1, 1399, N'1000715', 242069.7641138279, 2294)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b5dbc65a-2e01-49e7-99f7-22edf5bd1b62', 2, 1399, N'1000114', 590000, 5754)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c5bc9450-d539-475c-a6b9-22f6b696252b', 1, 1399, N'1001417', 147207.17492435026, 1645)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5978975e-dd72-43de-aa34-22fa047ad55a', 2, 1399, N'1000299', 56922.169013006882, 1171)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'af47b119-d6eb-429a-bafb-2300f11c5798', 1, 1399, N'1001523', 88375, 850)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ae7d13d1-c132-4af3-b966-231e8c33cbba', 2, 1399, N'1000090', 237171.35889704261, 2645)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'57cd6917-d00a-4f2d-af13-231fe472041d', 1, 1399, N'1001242', 187268.24, 124)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'68b01038-a141-4ddb-98a6-2336e1966f5c', 2, 1399, N'1001310', 67761.331901181518, 5280)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f369c3b0-d965-4606-b932-233f18a2972c', 1, 1399, N'1000167', 57217.402702769534, 2542)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'40233445-6327-404d-8876-23603f4f527c', 2, 1399, N'1001612', 108715.596, 2846)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3b008746-2fc8-4300-8e24-236220e40457', 2, 1399, N'1000724', 86829.317104822054, 1614)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'38d48af1-165a-438d-991d-238a99d22b04', 1, 1399, N'1000348', 67125.174620853082, 848)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0f374976-b825-4b6a-a3d5-23abb9ae067b', 2, 1399, N'1001210', 22751.8794338252, 3168)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c0d0d2fe-6b2f-49ff-afe5-23c0e4d477ce', 1, 1399, N'1001391', 190000, 18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b236447c-1099-4d01-bd97-23c2c7167215', 2, 1399, N'300002', 158734.17721518988, 45060)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c061bd70-f05d-48b7-8e7b-23d04830af02', 1, 1399, N'1001210', 22551.558505188848, 3591)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'30bea392-b74e-4e41-99b6-241a09bf2369', 1, 1399, N'1001441', 114400, 670)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'beabe5aa-d6b5-4623-a027-2424962fd019', 2, 1399, N'1000397', 127522.936, 2021)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'693c8d22-5b81-4967-9514-2431d8290659', 2, 1399, N'1001200', 123184.4654374852, 1790)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'09e2db1d-6f50-4f8a-a4f6-243728332956', 1, 1399, N'1001200', 123116.70500732771, 1809)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'87f37265-aeec-45bc-a032-249c88e1e3b8', 1, 1399, N'1000734', 99143.030000000013, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c2cf7ff5-bb9a-40ae-aa23-24a5e3f76faf', 1, 1399, N'1000038', 52828.734116156469, 888)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'00e20d16-cbc9-45ba-a78e-24a664577766', 1, 1399, N'1000320', 48169.4984716509, 2828)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7401867f-4036-4cb8-b7a9-24a9ab72de20', 1, 1399, N'1001494', 22407.833813747231, 3495)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e74c9f36-d88f-47c8-b188-24b7be2a92f9', 1, 1399, N'1000377', 36592.61, 32)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ccafccbf-58d5-4cdd-83c5-24bc5e06363d', 2, 1399, N'1001721', 68431.058836802884, 246)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b5a4687c-aae7-4b5a-900c-24d86316f312', 2, 1399, N'1000713', 74114.652577639325, 5027)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'529af161-5f3e-4f79-bd0f-24ffc4849e4b', 1, 1399, N'1001590', 68960.43, 48)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'20059484-df18-4960-a1fa-250031f317ca', 1, 1399, N'1001264', 478261.79, 178.045)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0661fb6b-d4c0-43e4-9c39-25365cafb094', 1, 1399, N'1000551', 119709.73526873119, 1422)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b61cc5c0-ca40-4fe5-bb14-256d0fd55934', 2, 1399, N'1000520', 44800, 362)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7b08ce90-4693-46de-926a-257db6ff81e4', 2, 1399, N'1001680', 76147.073273982023, 6362)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7eb54bb2-ecff-4a07-b124-25bd10d9bd32', 2, 1399, N'1001356', 180789.55660635617, 2462)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0ee22d12-5bf0-4670-bc74-25e2d5a5c368', 2, 1399, N'1000609', 37774.601232768204, 9113)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'45da7517-72f7-443d-b1d1-260d036c41a7', 1, 1399, N'1001054', 670036.39000000013, 56)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ed25f426-21c4-44fc-a09c-2628901aec00', 2, 1399, N'1001426', 864929.41565729119, 243)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd6c8b6e6-8caa-4ec8-a1f5-26644be6816c', 2, 1399, N'1000295', 46744.645177763392, -146)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'44200833-7741-4262-823d-26977d92287e', 1, 1399, N'1001213', 21640.678241960988, 3411)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1b077afa-9e50-4106-b9ef-26b521ae53fd', 1, 1399, N'1000632', 15770.37720413002, 5619)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'281f4c9e-16f7-4eeb-ae05-26b7f7431e5f', 2, 1399, N'1000707', 471788.991, 261)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'931c2b33-32cd-49d8-8433-26e4b1c2c063', 2, 1399, N'1000367', 29469.202696221266, 7646)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0b4c1c14-3d5c-4c49-90eb-26e50c1fd95d', 1, 1399, N'1000588', 21194.858905698205, 1134)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'17d98f96-46d5-4ac6-8765-26fa8bba0ece', 2, 1399, N'1000918', 111241.58377553767, 2383)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b7111f1b-24b9-4628-801c-270ea9fabb5e', 2, 1399, N'1000104', 118988.01703993669, 2164)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'efc2f3d0-7182-4b03-b160-271204f700f8', 1, 1399, N'1001012', 118503, -124)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'54d546c0-911f-4fce-9701-27192fa75e4e', 1, 1399, N'1001380', 132605.2, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'46f39fe8-4fae-42ed-94e9-2748d956d0f0', 1, 1399, N'1000111', 53557.728347893171, 1153)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'384de8c0-b227-478b-8dfe-27679c7c3693', 2, 1399, N'1001229', 66663.583562111016, 4087)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'95d460d5-065e-4653-9c82-2775e3fb347d', 2, 1399, N'1001403', 46881.00836954773, 2167)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'afe64e3d-be5e-4fc5-8d27-27988976b42a', 2, 1399, N'1000065', 38966.69584249537, 3136)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'65abcaf3-5224-4ccd-ba98-27a5aecfbfba', 1, 1399, N'1000405', 36000.020000000004, 1157)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bec11eb4-5583-46b0-bb87-27a7b87376f5', 2, 1399, N'1001725', 159513.71571072319, 1430)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4b244b95-dbd5-4d92-9c78-27c27f51682a', 2, 1399, N'1001565', 79965.010016543849, 2354)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d8f6c25-7054-4315-9d52-2811f0a1fa3a', 2, 1399, N'1000044', 57828.062417918358, 2781)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a9cba032-1455-4e75-a6a3-2838ea312025', 1, 1399, N'1000105', 72081.758211833134, 1494)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dfdedf91-53da-4e5f-8383-285c14eeb7a5', 1, 1399, N'1001248', 333592.05509592668, 1223)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'54038f3b-7050-4b21-8332-2862ab8d0622', 1, 1399, N'1000810', 735690.88000000012, 216)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b461753e-0c7b-4748-a2e0-286d5da56a87', 1, 1399, N'1000378', 112018.17000000003, 421)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0107278f-4120-42f8-a8b2-2877315be87a', 1, 1399, N'1000025', 15715.275355096142, 6902)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5734d4d9-b730-4155-91f0-28779bb09f4c', 2, 1399, N'1001371', 101156.67811968336, 1013)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6a2084fc-ac11-4c09-a863-28b47dede5b6', 2, 1399, N'1001449', 61926.606, 145)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'447291a8-7897-452d-b5f6-28e79663f921', 1, 1399, N'1000174', 182025.73409532619, 735)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8381ac44-9af8-46bf-b5a5-28fee95dbd91', 2, 1399, N'1001283', 55605.61238849, 2875)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dd7805c0-23d5-4f2a-b3a1-295f96325070', 2, 1399, N'1000322', 261742.38284548573, 3313)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'00d9b6d1-fd23-411c-9170-296243fb6d40', 2, 1399, N'1001648', 143130.92271317894, 11734)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'51fc0e01-a3d6-4c53-a305-29733c6ccf36', 1, 1399, N'1001332', 46905.361915673682, 6758)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dcefefca-e2b1-45f5-8598-298bc90514e5', 1, 1399, N'1000880', 147005.11926178989, 2627)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd13ca05d-2c74-4683-bbdf-298d1a426fe1', 1, 1399, N'1000672', 14131.746875929322, 24864)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3d09853f-b7e5-402e-bb80-29cdabb53634', 1, 1399, N'1000685', 120368.75517195324, 310)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd8fdaa7d-fb7a-4125-a62e-29f06c8b7842', 1, 1399, N'1001679', 117427.86793341719, 9579)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'49d29034-6a56-4858-86e3-2a84de1d2ce1', 2, 1399, N'1000042', 13775.977589352799, 11241)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e3e8be2c-41df-4a93-bb43-2af8f528862a', 2, 1399, N'1001751', 330274.96298772178, 1248)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f72fef93-f03c-4d55-98c4-2afa5a8a3539', 1, 1399, N'1001556', 29352.97, 276)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7e1c778d-1bcc-4d7d-81d6-2affc10cc1d2', 2, 1399, N'1001237', 94145.08971814609, 2517)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4e6fac02-3070-48a9-a922-2b06d231ffed', 1, 1399, N'1000168', 77867.825199306753, 1904)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'79263c8e-cfe5-4a24-8991-2b60d934067d', 2, 1399, N'1001570', 108055.49454145866, 1126)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a881e872-8252-4b36-a50b-2b8429903e6a', 2, 1399, N'1000315', 118127.29571130607, 943)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'06064d68-d159-44db-a9c6-2b906060fc41', 2, 1399, N'1001610', 86743.47671011537, 1704)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8974a1d6-76c1-4f63-b0af-2b94d03ff2ed', 1, 1399, N'1001411', 113542.85158644932, 1479)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a5c89ac0-9157-4222-8e58-2b96eb4c5bad', 1, 1399, N'1001479', 68022.139999999985, 232)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'52e42f23-5a7e-4c6f-92ea-2b97a05810b1', 1, 1399, N'1001256', 448631.41000000003, -49)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e95139f2-edc7-48b7-9095-2ba9bc599574', 1, 1399, N'1000652', 518009.94, -4)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'374db91f-ee0d-4bbd-8c59-2bc1adf840f8', 2, 1399, N'1000940', 51959.966909090916, 11180)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'67cc8509-cef0-4cfc-808b-2bccd7750024', 1, 1399, N'1001629', 293175.71774199419, 1950)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'888bd404-28ff-4750-b873-2bd9a6a10d0c', 1, 1399, N'1001128', 51699.960000000006, 15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1ac80537-ebe6-4655-8d51-2c1b3e4ef7d5', 2, 1399, N'1000191', 63872.987499530107, 12951)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'24a0ee13-f8cb-4e7d-ae15-2c1bafca4b24', 1, 1399, N'1000032', 83130.47668830755, 1174)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'69faad12-22c5-46c3-aa25-2c5b56fc1770', 1, 1399, N'1000934', 36685.463741373889, 12936)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'67bbe03f-3204-4ddd-b831-2c5d804544cf', 1, 1399, N'1000718', 57227.689200089728, 1282)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'03c742c5-4d9b-48c2-ac8a-2c858f53514b', 1, 1399, N'1000696', 194321.71, 3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d24121b-898c-44a6-aa14-2cee08d0ae04', 1, 1399, N'1000709', 415192.59139675967, 617)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'787e20d3-7e46-436e-b85c-2cf4c226c5a2', 2, 1399, N'1000897', 33027.534056821132, 2599)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'48a266f7-9364-47b1-a458-2d2f3deb2199', 2, 1399, N'1001354', 90825.688, 271)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8d0a78db-b5d1-4096-9f4a-2d8271d02150', 1, 1399, N'1000722', 67191.792523274649, 916)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dae7b71c-e6ce-4f25-8c9f-2d9ea09fbb3b', 1, 1399, N'1001440', 114400, 648)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ed14eb45-b6b8-4e86-b5e4-2da0a5f0e18c', 2, 1399, N'1000406', 26506.158779700105, 4111)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0ee16024-c001-4161-ad71-2da5641be418', 1, 1399, N'1001067', 596000, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1639adbb-1a9d-4e1d-9a78-2dea01a8fd7e', 1, 1399, N'1000375', 66906.959999999992, 6085)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2103cbf0-8f62-4b70-aaf5-2dff8f5c6f92', 1, 1399, N'1001570', 108086.71149616643, 1175)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'09b62117-d8e7-423a-8497-2e05d2ce9586', 2, 1399, N'1001259', 29725, 4620)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ca4343de-174c-4047-a37a-2e4a4ebb6fca', 1, 1399, N'1001475', 44735.65, 442)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a1d62754-5fae-4aa7-ae7c-2e714b163be7', 1, 1399, N'1000422', 57824.504189710606, 89)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'74abd1f5-075c-4dc3-84c6-2e7fcd8aa2b4', 1, 1399, N'1000246', 92323.418621244346, 5593)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e6e48d16-f561-4ad5-93bd-2e96b37fb3e0', 2, 1399, N'1000854', 123861.73002902854, 3216)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd2674fea-ecaf-43d0-8a15-2e979cb8b33e', 1, 1399, N'1001269', 49828.748639175246, 2561)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b24d5901-5dd6-4bdf-a1e0-2e9c45f3b18c', 1, 1399, N'1000858', 52636.038028531177, 1133)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4ce34714-ec0b-42e0-925b-2eb98c3ce3c1', 2, 1399, N'1001184', 68761.754449038286, 6168)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'759aa871-385e-428c-85d8-2f32f78219bb', 2, 1399, N'1000133', 47725.768786528366, 877)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3e4dad10-608d-4cb5-b02f-2f45eb8c4826', 1, 1399, N'1000290', 41654.846539031081, 1149)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ded3a4e4-9f2c-432a-a51c-2f72d7c52687', 1, 1399, N'1001000', 47330.327719007044, 11109)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a352c825-cbd6-4d74-a836-2f80def5f732', 1, 1399, N'1000549', 178563.95312142855, 88)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'24c231b4-38bc-45d5-a507-2f918f50cacf', 1, 1399, N'1001230', 238701.34, -4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'deaced59-5481-401c-8adb-2fa55fe3eb10', 2, 1399, N'1001365', 28965.492089734151, 2867)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'168f400a-0176-43ba-abed-2fcc24715a61', 1, 1399, N'1001254', 24586.99, -587)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'59a8f337-3afc-45db-8140-2fd7d422810d', 2, 1399, N'1000378', 113302.752, 373)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fb3ba8b0-0cd4-4672-a72d-2fdf1025c36b', 2, 1399, N'1001323', 20871.56, 8119)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d87e624-bb58-42f1-a11f-302151cc224d', 1, 1399, N'1000681', 172714.54999999996, 17)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9643458c-6c5d-40e7-b691-307208f8ddaf', 2, 1399, N'1000529', 118371.34739457139, 1285)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9a5ab3fb-45c9-41bf-a521-30a222435b9c', 1, 1399, N'1001066', 77462.03, 61)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8aef8009-4bf3-4c29-a29c-30ab9e65613c', 1, 1399, N'1001633', 16368.713709325581, 4982)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0fcaeacb-36fd-4366-9176-310161b315ff', 2, 1399, N'1000894', 33027.6848209178, 2400)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'01f3cf68-d0c7-45cb-af25-310987264d77', 1, 1399, N'1000462', 10733.215867755789, 4960)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f24c6bc0-3a56-4284-9f64-31197830295d', 1, 1399, N'1000161', 90999.873082597827, 1967)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'576da24d-a43b-4bcb-88fd-314f25dda082', 1, 1399, N'1000578', 7068.7983679106028, 128.99606111)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'159fa0ab-dca3-4098-8dcd-319eee7488fd', 2, 1399, N'1001289', 232832.83215838307, 1573)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd50742d2-36b2-446a-873a-319f5960cebf', 2, 1399, N'1000853', 223984.41400451618, 517)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'433d9e08-075b-4a3a-b13d-31d081a7aba7', 2, 1399, N'1000832', 40000, -26)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b2cea5cb-b46e-4272-af52-31d2036ee2bc', 2, 1399, N'1001061', 5505.2558224169879, 21833)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c80e2072-96df-44aa-baca-31e7569c9d00', 1, 1399, N'1000536', 73152.223711903483, 2529)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6ece6691-9d7e-4547-8dec-3201b399cd5f', 2, 1399, N'1000631', 13945.671739109792, 4735)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1469283c-770a-49dc-a99f-324969fe1129', 1, 1399, N'1000093', 23118.97, 58)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd1e67308-f0ed-45eb-9485-32ab42a5236b', 2, 1399, N'1000003', 37234.554214501426, 4533)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'52e42920-dce7-4fe3-ab39-32b6782a42b4', 2, 1399, N'1000464', 21478.524051616987, 2999)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd18d48f2-7ae4-4513-949a-32bee86e9ac1', 2, 1399, N'1001410', 928500, 5970)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'638b029c-989d-4d13-b981-32d06ad36ab8', 1, 1399, N'1000795', 73759.510000000009, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'62ca9d69-61ad-4b37-ab65-32eac5502413', 1, 1399, N'1000094', 23119.03, -9)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5cdc7d15-ba73-47f0-a320-32eb0945613e', 1, 1399, N'1001150', 45000, -50)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cab18e81-1a53-43b0-a1f0-32f53295b0b0', 1, 1399, N'1000338', 61709.542966929665, 4723)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7dbf4dbd-d250-4d9a-8535-3318c207b10f', 1, 1399, N'1000725', 29134.839999999997, 126)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9c94580c-ab13-4df3-8097-331eca668477', 2, 1399, N'1001498', 46788.991, 4409)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c8a070bf-b55a-4925-9a53-3326d73a34ed', 1, 1399, N'1001404', 183532.53769221029, 1372)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0eb79fea-1528-4215-a25a-332b2639d811', 1, 1399, N'1001153', 45339.38, -12)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6e39b05d-d1bf-41ba-9327-333164dc9a4b', 1, 1399, N'1000639', 51983.00674746553, 848)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'156165db-4a0c-49d4-8a45-3346fb9b1615', 2, 1399, N'1001496', 107533.3960195523, 1481)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'351465e4-ae42-447e-85db-3376b04f3d06', 2, 1399, N'1000162', 75000, 797)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6ea9abb1-0131-4c54-a2d5-337ceeff9989', 2, 1399, N'1001049', 95084.500650305854, 2505)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1bc47ba6-e890-412a-8c27-338999384bf5', 2, 1399, N'1001632', 22018.349, 8265)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4c377a39-0bc7-47fa-94ad-33acef52bcb0', 1, 1399, N'1001308', 86861.268493506432, 2291)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9f3047d4-72fa-409f-8534-33b0f276dea4', 1, 1399, N'1000730', 150000, 69)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f4314740-d207-43a9-ae6a-341013a40ac1', 1, 1399, N'1000260', 85475.137477270517, 2156)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cd3290a8-6d79-49d1-aa2a-343bec04a0c3', 2, 1399, N'1000119', 213622.65816870003, 1479)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c9484966-acb3-46d5-b28a-344428f4ca6d', 1, 1399, N'1000148', 119698.0025553327, 2600)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'46472546-48a2-4242-86fe-348188f31397', 2, 1399, N'1001739', 172018, 3416)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dc065bfc-f278-40bc-bb28-34d5d6dae63d', 2, 1399, N'1000296', 44293.983232411651, 118.998)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b21ca75a-527e-4c89-8fa8-350e45d55fde', 2, 1399, N'1001300', 84848.436366978523, 1187)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1c3e7bd5-227b-4204-b74a-3543c4275c94', 2, 1399, N'1001708', 0.917, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'64f50bca-e3cf-48a9-b322-3555713fb45e', 1, 1399, N'1000237', 77054.807672631563, 1119)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'90c1af86-5ee8-4d7e-ad84-3555fed40199', 2, 1399, N'1000697', 57801.589892343662, 4835)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cb960cbb-ed49-4db0-8c2b-35ad52577ce5', 2, 1399, N'1001236', 66055.046, 360)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4e0dcecb-ca27-4e6b-82fb-35afd64dee1e', 1, 1399, N'1001316', 419958.26825053996, 332)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'415c08bd-d14d-405d-9331-35fe29ea9fc6', 2, 1399, N'1001635', 158214.28571428571, 3002)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3ad00f9c-97ba-4b88-aa68-360731f1dc19', 1, 1399, N'1001558', 143338.99000000002, 1087)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'80d0efcb-c3db-49cb-be4c-360c0de5521c', 2, 1399, N'1001628', 3669.725, 101617)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d798e3b-6d63-40e5-9152-362b65725962', 1, 1399, N'1001204', 150317.06, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a07fbfd2-803d-4f82-93d2-3643f2ac6772', 1, 1399, N'1001059', 47336.179999999993, 15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7a2900c0-588b-4a02-9c5b-3666e050f7ee', 1, 1399, N'1000539', 102775.34030392388, 2115)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'69ebce96-5990-4c5e-8357-36a0ef967879', 1, 1399, N'1000062', 39528.569445173838, 16547)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd2be4c34-b6cf-45c4-95ca-36df3d63b9df', 2, 1399, N'1001519', 171559.633, 1187)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7c50e8c3-00b2-4a99-b317-36e700bb2039', 1, 1399, N'1000663', 93624.06, -5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cb5c5915-f646-4f33-a685-36f98553336e', 1, 1399, N'1000055', 323783.70102777163, 3148)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a580c5bc-9a86-4e51-a690-370293cbbc06', 1, 1399, N'1001667', 43394, 3600)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5fedeaf2-f4a6-4a73-861e-37114b3c6736', 1, 1399, N'1000831', 50000, 28)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a7a6aefd-5c3f-46bd-a8ae-3758b2f38ba4', 2, 1399, N'1000328', 46254.579879595891, 8321)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2bd80191-2379-41b0-baf6-377f84a9d59b', 1, 1399, N'1001208', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c487cb9b-32a3-41f3-ab34-37a36f619c93', 1, 1399, N'1000065', 39582.612826750235, 2615)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bcde1149-8e90-41eb-a9eb-37a6210c7b0e', 1, 1399, N'1000109', 36338.721569423178, 2661)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da222385-51b1-40ad-bd09-37c45a30ef27', 1, 1399, N'1000518', 25204.534970911449, 637)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9704c016-8719-4678-88ec-37c95498e399', 2, 1399, N'1001639', 26424.967118807981, 2968)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fcf64ab2-ebc4-40db-8f94-381b9facf986', 1, 1399, N'1000656', 7081.9528519364221, 14672)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0c0280e7-820f-43f7-bdd3-381fa17266ec', 2, 1399, N'1001278', 462202.59599462169, 1565)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd3b74bad-2095-4a01-99a0-382c3f835ce7', 2, 1399, N'1000948', 195124.61834394693, 1731)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8318220b-fe3d-4efe-b2db-384362b949c7', 1, 1399, N'1001652', 218080, 2222)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'63971155-4291-40d0-a88f-384defacafc4', 2, 1399, N'1001667', 47706.422, 877)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'010b5561-4f58-45c6-a4e3-3867e83605b1', 2, 1399, N'1000957', 113358.7239616091, 3576)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'636968ac-2b8a-4868-bfc3-386af2b09b49', 2, 1399, N'1001534', 520247.68029626081, 4186.574)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eb141ff3-072d-477a-8c4c-3886e783676f', 2, 1399, N'1000531', 56879.828845993106, 1502)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8fd06cc5-705d-4c89-81d9-389dfabbf734', 1, 1399, N'1001281', 75388.937252408476, 2534)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2921169c-e7a5-4cf3-bf5a-38cd0030423c', 1, 1399, N'1000298', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'88e0f781-3550-4fb3-a274-38dccbc5914e', 1, 1399, N'1000481', 2813.7900000000004, 1683)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'33fa55d4-17b6-4435-8cc4-3914624f379d', 2, 1399, N'1000584', 14135.381964604583, 1695.99715111)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c3ae6b97-8e79-4204-80b5-392378177a68', 2, 1399, N'1000498', 27999.792920056581, 5281)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'de6e7333-f37b-4f0e-82a2-39282664732c', 2, 1399, N'1001666', 240035.85657370518, 4120)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f72888f9-da57-43cf-addd-3947a0ad3356', 1, 1399, N'1001061', 5525.495572016157, 17435)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da9784df-d3be-4a8d-9839-395755ab43df', 2, 1399, N'1001472', 62385.321, 118)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'31abeb19-6cce-4968-a345-395d712e409f', 1, 1399, N'1000164', 307500, -2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'61ab364b-e04f-40ed-a34d-395fadc73b71', 2, 1399, N'1001412', 108014.82146998617, 1284)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2efbedf0-c096-41a6-867b-397b6fe241b4', 2, 1399, N'1001314', 116170.47970479705, 2084)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4ecd67c6-743e-484a-9d4a-397d98db5c24', 2, 1399, N'1000500', 54411.254106169945, 1108)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd421fd6c-b5cd-4b7e-91c3-3986028c0ebf', 1, 1399, N'1001144', 232200, 5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'384b425a-05ec-4bd1-89c9-39c7fedcd763', 1, 1399, N'1001437', 11926.236701731727, 1246)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1b58f0bd-4d38-4261-8722-39e6a65abeb5', 1, 1399, N'1000553', 85500, -30)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'905473bf-c681-44f1-84b6-39f12dd972e2', 1, 1399, N'1000019', 42611.788976036281, 3689)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e38ab9f8-f2fc-4c34-82e2-3a167fdd20af', 1, 1399, N'1001650', 48461.062511267832, 1860)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'af1f2aa2-2cd7-4ef3-aec4-3a2b4db78486', 1, 1399, N'1001620', 51695.857760850107, 2616)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b097a4f9-1535-4d13-9c89-3a448e29c6b7', 1, 1399, N'1001133', 550000, 18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c17dc704-42b1-441e-9510-3a477cc0f26a', 1, 1399, N'1001516', 242920.59911692512, 1531)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'aea056f8-f502-45ca-8434-3a4c90f60080', 2, 1399, N'1000089', 138145.95190182998, 3178)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'31520a05-9052-4e31-b5ea-3a4f78abd91d', 2, 1399, N'1001532', 32797.949775305315, 480)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'91267122-f800-4b6b-9b94-3aee088e38ce', 1, 1399, N'1001455', 132935.31999999998, 1852)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'897c826e-3295-4912-aec9-3b1254df9c0c', 2, 1399, N'1000269', 22293.132428837569, 896)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ba35fcf4-5721-4e3d-8a02-3b2595a24587', 1, 1399, N'1001154', 7799.99, -5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f5c65507-998b-47b9-864a-3b5133caa5b9', 1, 1399, N'1001395', 60917.054068731573, 174)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7c338462-f2f7-4da4-b9e1-3b5ef281691e', 1, 1399, N'1000723', 57824.385901705115, 846)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'384c4e74-e5a7-4e1f-9420-3b9161258eab', 2, 1399, N'1000331', 17066.415107792986, 6305)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'baf55c94-7a88-43d5-8aa0-3bb751004690', 2, 1399, N'1001343', 40470.523169620566, 24675)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'610ed260-95e3-40e8-8f16-3bffcdd8a002', 1, 1399, N'1000171', 14369.794041437293, 4164)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7c7e4031-8e52-4299-9ad2-3c24c9ccba4e', 1, 1399, N'1001557', 25390.047160674978, 1173)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'75876ed0-d9cb-4b95-aa3e-3c342cf8aced', 2, 1399, N'1001567', 57904.090591659631, 5129)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a3089131-2988-4bf9-a1bd-3c3af2688275', 1, 1399, N'1001533', 507090.30964755075, 7047.275)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e09615cb-f88a-452f-a327-3c6ef64dd96e', 2, 1399, N'1000244', 17936.661094853112, 915)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7413977c-39d6-44c5-bb90-3c74316797b7', 1, 1399, N'1000829', 92066.03, -30)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dac38bfa-69f1-4a2e-81da-3c8cecf208d9', 1, 1399, N'1000638', 287655.41933774587, 784)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bf4b9916-890c-4785-b24c-3cb7791c85c9', 1, 1399, N'1000194', 33886.384173255807, 1352)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e68806c4-7615-48fc-b66d-3cd2a22c2cfa', 1, 1399, N'1000659', 13767.454660242667, 3836)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7a344f96-0a1f-4613-b54f-3cd3d9bdb7b7', 1, 1399, N'1000635', 209430, -2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'901e4e15-2767-4e98-aa5c-3cdb41130b15', 2, 1399, N'1001090', 40366.972, 2358)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e116f6c0-2adf-4d99-952d-3ce1ee24db29', 2, 1399, N'1001388', 529000, 186.885)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5f10dac3-7c1e-41a2-beb1-3d073be4a83f', 1, 1399, N'1001327', 176381.5, 6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d4ee2ef-4881-4a05-8734-3d14bd264644', 2, 1399, N'1001540', 359211.95652173914, 623)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6ed1e596-651d-4c95-a2c7-3d405e35b2c0', 2, 1399, N'1001307', 51379.64530261141, 2140)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e4481e9b-8d87-41ad-86c1-3da4f2ec9d29', 1, 1399, N'1000411', 68675.426370313289, 1643)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f1899d70-4b76-4e38-999b-3dafd9decc89', 1, 1399, N'1000928', 227669.35, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0b3ecd32-5be5-46f0-9b56-3dc254f3d1dd', 2, 1399, N'1001503', 153482.32968953633, 2074)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b72ce0a0-e2bc-4647-8313-3ddc84462a5d', 1, 1399, N'1000003', 37221.58440741137, 10662)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f1e3957c-9842-452f-8ca4-3e09dd114429', 1, 1399, N'1001197', 64038.535379155677, 4319)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bf1869b9-7a55-446e-8907-3e19dff5eae6', 2, 1399, N'1000289', 45906.65271622561, 989)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'00cb5dc3-4c98-47e0-abea-3e8e73d95d79', 1, 1399, N'1001434', 14907.75, 185)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'de657f50-38f9-4e12-a705-3e9c02305f98', 1, 1399, N'1000651', 850185.03682774713, 150)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'15f96456-c028-49e8-85e2-3ebc041e71ae', 2, 1399, N'1001425', 1230097.7280531852, 248)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'70aa1fd5-73fa-45ea-abe3-3efa0ac7c724', 1, 1399, N'1000173', 57321.748958150842, 3070)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'383e1ea8-ef3f-4846-936e-3f5c0d13d3aa', 1, 1399, N'1000063', 39597.027215054113, 2655)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'09da76c7-7808-45f2-8eca-3fa15b909625', 1, 1399, N'1000457', 49539.7, 72)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'217dfa7c-7d0d-4dba-91f0-3fad5b45bb9d', 1, 1399, N'1001049', 163323.1128162588, 2772)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a39593a3-2c84-4431-9e87-3fb97fb59399', 1, 1399, N'1001474', 26010.633965176236, 1553)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c9c71fe0-b3e9-4952-9f35-3fc1edd1fa06', 2, 1399, N'1000533', 61000, 1180)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'25cf7c0b-c511-4a78-993b-402f4845af10', 1, 1399, N'1001203', 296145.96, 646)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1d4b9580-d6f5-42ed-bb25-406af6ae733d', 1, 1399, N'1001535', 18505.857648959733, 11510)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a0b132fd-54c9-4001-bc1f-409e65ecd475', 2, 1399, N'1001643', 70000, 2013)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5ec2d9f3-3db2-416d-ae67-40a769db935b', 1, 1399, N'1000092', 23119.04, 35)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5110b13a-b4d4-4611-9652-40ace86bfe0b', 2, 1399, N'1000159', 109211.88320831352, 2895)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6bcfa615-4bfa-42ae-b119-40d1a286f901', 2, 1399, N'1000861', 105963.68252552528, 1617)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1ceaa80d-9662-4c11-a296-40d52a2cc63e', 2, 1399, N'1000257', 105617.80987441307, 1669)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f5398231-1d4f-495e-8259-40fe39d532bf', 1, 1399, N'1000395', 62101.525345255359, 5069)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b971f15e-119c-48b9-9717-4102e50c786a', 1, 1399, N'1001676', 109174, 7200)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c48115c1-0ed4-49d9-91d1-4148e468d600', 2, 1399, N'1001185', 136077.3829894313, 4962)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a7baa2a4-53e2-46e6-a4e6-4150c06527ce', 1, 1399, N'1000925', 219283.67231081286, 776)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6e39b756-b17e-4041-8822-41ad7de8b01f', 2, 1399, N'1000591', 70882.908581746742, 976)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ddb61a26-7c4f-47d3-94fc-41bf95986626', 1, 1399, N'1000083', 41606.035347700315, 4835)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6e21cb58-eafe-4772-afb4-41ca08cc4866', 2, 1399, N'1000645', 820002.96704756271, 544)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'872222c5-42e6-4bf6-aea7-41cbeec1a446', 2, 1399, N'1001313', 77003.671471308131, 3382)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e84937ad-f2ec-4cd1-808a-41f2a1df4262', 1, 1399, N'1000175', 716476.37999999989, 82)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2c50e9a5-8efc-48cb-b0d8-42497b7a0d45', 2, 1399, N'1000307', 97846.460849465162, 869)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2539a801-d1c4-48f3-8842-4282ba8fde00', 1, 1399, N'1000603', 64788.36592975707, 2448)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6d6f6cd5-5df3-4805-897e-42b910633bf1', 1, 1399, N'1001094', 150000, 8)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'44b85fdd-5317-46c1-8a9e-42c1a19afb48', 1, 1399, N'1001491', 40755.4, 196)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f9f06aaa-8bb1-4c57-a45b-42dfe5d56c48', 1, 1399, N'1001503', 145995.46499784006, 2517)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2c3e05ba-7d37-4d37-be70-42eb31195a3c', 2, 1399, N'1000321', 262403.08216916089, 2112)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b0720c12-d590-4ddc-940e-42ed5f0c0672', 1, 1399, N'1000933', 50194.191530677985, 17763)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'03cefe69-1a1c-4ecd-b8ab-42efc76d4977', 1, 1399, N'1000986', 23119.14, 31)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'25039ce6-a8ed-4cf2-a778-42f05c32ee6d', 1, 1399, N'1000837', 77385.31, 3069)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9deb4e8c-25e3-4c36-a1be-43486cb1b8c1', 1, 1399, N'1000727', 171000, -6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3f767a8b-2073-4558-905d-43501408abe0', 1, 1399, N'1000713', 73109.534033215285, 6241)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ff8f335c-fecd-434f-8700-437464876584', 2, 1399, N'1000204', 19000, 1073)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da097b53-df9b-4d3e-90f3-43909a618a76', 2, 1399, N'1000284', 16400.561167819491, 6838)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c77c43f2-a4ec-45c5-a9a3-43c66a6bb619', 1, 1399, N'1001520', 84976, 1423)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f5de14d0-4e78-4d7b-93b8-43dbd886e4b7', 2, 1399, N'1000782', 431896.62392777693, 1417)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'142ec3b7-567f-4028-a3cd-43e805efee8e', 1, 1399, N'1001329', 36485.98000000001, 78)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2f0ab3f8-115a-49be-a94f-4400266daece', 1, 1399, N'1000306', 118471.25999999998, 8)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7fa5d363-c9ff-4d64-aa41-4447d8d796dd', 1, 1399, N'1000207', 561791.51805697591, 1009)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'defb3333-2f69-4013-a5e4-4451ce293f51', 1, 1399, N'1000580', 14108.075554196983, 1838.00072666)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4f42d634-13a4-401f-94d9-449aa604f1b3', 2, 1399, N'1000532', 56909.037601561155, 1374)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'977c49ca-f693-4d9d-b4fc-44d5bbf621fe', 1, 1399, N'1000022', 36333.397629871819, 2939)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b902eb1f-b40f-41d5-ad1a-44dcca78aafa', 2, 1399, N'1001355', 80074.632418606809, 1257)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6bd0d392-f6da-4b6c-a4bb-44f5fde8b6ef', 1, 1399, N'1001285', 40745.6, 6926)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'98fe886a-d1e4-48f8-ad00-453bc62c9e35', 1, 1399, N'1000590', 70647.106753845073, 469)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'89c8585f-5063-4af6-bc08-45564ce728de', 2, 1399, N'1000126', 26685.3846664487, 9899)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'84b202b4-302a-428e-bd96-45aef5a6442d', 2, 1399, N'1000978', 8934.32208549655, 2759.999455)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'66b5aa19-f025-4d9f-aee6-45d575a658be', 2, 1399, N'1000588', 27533.88316425863, 1063)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7a4da95c-dead-463d-875d-461056bab1cd', 1, 1399, N'1000058', 111559.259364125, 5482)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'561f8f69-94fc-4563-b283-4611753ec1ee', 2, 1399, N'1000395', 75229.358, 4218)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a695280a-86bd-4dcc-9786-4616f9ac0565', 1, 1399, N'1000968', 25928.270000000008, 1241)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b5aee81c-78f2-4818-8332-462acd33fcc7', 1, 1399, N'1000953', 201028.37000000002, 15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'47d7aa61-c4ca-4853-9b38-466edbfb3121', 2, 1399, N'1001066', 77461.986832091468, 2207)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2464cdfc-7da9-4347-aa10-467b7665abf9', 1, 1399, N'1001390', 122849.95000000001, 7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'93da503c-0912-4ebb-b764-4698381551d6', 1, 1399, N'1001220', 239473.001113602, 707)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e8db5c3d-ca37-4934-aa7c-46a6e8d0ddaa', 2, 1399, N'1000504', 49449.5687669005, 2593)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'27b8677b-7332-43fe-b39c-46ab7132bc01', 1, 1399, N'1000315', 114407.19534251651, 1280)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd9e214d9-42e4-4625-b68d-46b96105995c', 2, 1399, N'1001609', 82598.003327787024, 108)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f2ecc780-f201-4e6e-9a2a-46efdbcab402', 2, 1399, N'1000033', 51771.993418814942, 6357)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da2fb61c-0a42-49fc-a435-4714e13a73c2', 1, 1399, N'1001099', 239054.1214198535, 2110)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b3af51a0-8813-4ea2-9cbb-4731f859dfd3', 1, 1399, N'1001396', 228615.67476472995, 3572)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fbc4e01f-439a-42f8-ab69-474295eeb0ad', 1, 1399, N'1000682', 82147.43, 14)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'09be1640-c933-455b-bb99-4743ce4aef38', 1, 1399, N'1000272', 17942.915804373384, 3246)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'99728532-ff94-4fcb-a657-4766ed951f00', 1, 1399, N'1001335', 18806.46, 7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd1008fcf-56ea-4b6e-9896-478788a9425c', 1, 1399, N'1000943', 260220.896631473, 1547)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'419e686b-f5fa-4902-a72e-47f899863fef', 1, 1399, N'1000544', 113981.30954120532, 970)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c2aa4215-9a1f-4451-9146-4807e2e43993', 2, 1399, N'1000873', 98165.138, 3195)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f6842136-93c5-4ae5-ac9f-48753cffae1a', 2, 1399, N'1000345', 71990.344395859749, 2106)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'85e101f1-bf4f-4e2d-931e-487d48b9e639', 1, 1399, N'1000692', 31363.268854707243, 3077)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6281834b-ea22-46c7-914b-48912b8d662e', 2, 1399, N'1000368', 132568.807, 549)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7bfc82a3-971e-4aab-95a9-48a8b472d017', 1, 1399, N'1000107', 81747.1650299112, 1810)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c01a4c84-ca05-4194-8b62-48ab07cf3c11', 2, 1399, N'1001350', 37155.963, 3300)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bdf85c77-043e-4b4e-9389-48adfd3440d8', 2, 1399, N'1001235', 39879.425330067061, 2245)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'637e018e-acce-4851-9bdc-48d75f156fb6', 2, 1399, N'1001338', 33050.733590657735, 2691)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc1f26cb-6434-4c14-8494-48f5c7c6ee8e', 1, 1399, N'1001267', 203024.52107279692, 1044)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'769d39e6-fa97-45c6-8342-491d31995915', 1, 1399, N'1001362', 145004.44629843914, 852)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2ee40092-432f-444c-accf-494f895f73dd', 1, 1399, N'1000865', 52384.687508917137, 2789)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'79a1efcb-6621-4d98-bdac-4969964e8f93', 2, 1399, N'1001676', 117094.80133333332, 6374)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'277ded8e-bf91-4da9-ab8b-498945b2d602', 2, 1399, N'1000465', 25044.773090382128, 2479)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ae050c94-6a15-4cf5-94a7-49d3ea579277', 2, 1399, N'1001378', 62977.124052816369, 5933)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'32f83662-d5f8-4f7c-8bfb-49d6b3a59d1c', 1, 1399, N'1001064', 171747.53038265748, 1470)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1e11593d-a105-49eb-9200-49d80b6e0077', 1, 1399, N'1000631', 12653.397319617223, 6052)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6c2c0245-a9ec-4372-bad9-49e124e9aeaa', 2, 1399, N'1001430', 780768.06743052416, 221)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'730ed50f-2a52-494b-a55e-4a2958752eeb', 2, 1399, N'1000513', 35321.723899186909, 7046)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'88603f12-fdd7-483e-9fd3-4a34c3d52f7a', 1, 1399, N'1001352', 28528.220000000008, 8080)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c1e24e87-a837-49ba-8a73-4a376c4e79ee', 2, 1399, N'1001691', 473868.23059645621, 3205)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c0d2944f-7352-4ab6-9b20-4a644c57e97c', 2, 1399, N'1000670', 70720.782738770824, 991)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7aae459b-1fbc-40aa-abc7-4a756b3c8591', 2, 1399, N'1001633', 17889.960085883093, 5820)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'92fa3652-d63b-448e-900e-4a955fb1a3d6', 1, 1399, N'1001659', 38213.817636963184, 1462)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'19a474be-352f-4a5f-844d-4aa22120070c', 1, 1399, N'1000737', 61584.409999999989, 574)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'21b00665-875e-49bb-ab29-4ab9ae5547d7', 2, 1399, N'1001690', 42661.577129931735, 14406)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9d8290ae-dc23-4d9e-a8ef-4ae7d663769b', 1, 1399, N'1001361', 96914.998079110141, 853)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c9d8bc1e-2cbc-4d7c-b41c-4b02e4f4efba', 2, 1399, N'1001521', 185229.358, 774)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2ff27ffd-5135-44d8-8779-4b31f010d01d', 2, 1399, N'1001414', 74435.085419378229, 1311)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'aecdcf4a-f7af-4ee4-958a-4b3f75754384', 2, 1399, N'1001326', 33526.211135085105, 3474)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'025f0a98-5a22-4379-99ed-4b666eacef57', 1, 1399, N'1000219', 19891.245360143221, 7552)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'011a2d2c-42fe-4c86-9f45-4b88eb37ab0b', 2, 1399, N'1000867', 118833.90572299933, 1764)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'888aff80-8759-4f73-8e19-4b8d0eb3b087', 1, 1399, N'1000499', 25931.096762717214, 4237)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c714087d-09de-4429-9f75-4bb2b87abbe5', 1, 1399, N'1000716', 145892.432766627, 3250)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0d844d48-7414-46cc-819b-4bb3b2dff30a', 1, 1399, N'1001562', 50196.985960055572, 382)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'50d9bffc-dfd7-4a31-ac29-4bcb385249a0', 1, 1399, N'1001643', 49006.248140434393, 2991)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9593b9bd-495d-4326-9d98-4bdc6ca52cc2', 2, 1399, N'1000460', 118807.339, 1619)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5b11e59d-e5e7-4c66-8ec8-4bde19780938', 1, 1399, N'1001140', 157999.83, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd36836a5-6aff-4c82-8791-4bf989af8977', 1, 1399, N'1000329', 61318.045510300733, 3468)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7043fe1d-49ab-48e4-a7f6-4c1e015dc93e', 1, 1399, N'1001025', 199940.03361538457, 21)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cd3ffd51-1762-4819-bc5a-4c8f9322452b', 2, 1399, N'1000429', 133027.523, 377)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e7730cad-638c-430d-a0bc-4c9d6dbba88e', 2, 1399, N'1000718', 59620.405238933607, 1319)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f39efe40-e165-410c-8fac-4cd677ad2969', 2, 1399, N'1000115', 574000, 5965)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd6268b44-0e44-4431-a685-4cd69c41bde7', 1, 1399, N'1001644', 200981.674302374, 1951)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'39d1b2f0-3662-467d-a82b-4ce81e3d898b', 2, 1399, N'1000444', 19246.525366684589, 3987)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9b2089f7-87a8-482a-ba43-4d0746548d9a', 2, 1399, N'1001517', 357798.165, 540)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd347536d-d6c6-4659-af4c-4d481a70c572', 2, 1399, N'1000468', 26424.497769159829, 9784)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e803b94e-bf41-4f67-a7b3-4d7060bb4eb7', 2, 1399, N'1000256', 379000, 16)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5176a4d9-00b3-44fb-bb6e-4d88c4174d89', 1, 1399, N'1001184', 58611.728117084152, 4520)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'36f085ec-af88-4ae3-8ee4-4d9a3a17516b', 1, 1399, N'1000872', 268524.1147104667, 2319)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2b87b984-c52f-44f1-a615-4d9da7b78b9b', 2, 1399, N'1001342', 35824.103914448177, 2119)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd628ec3b-cace-49ec-b50c-4de97b42c065', 2, 1399, N'1001096', 22324.086033215357, 1621)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'53e64ba4-6e9f-44cd-806c-4df580f372df', 1, 1399, N'1000244', 17936.213789517667, 1355)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2b12aa33-3df8-4964-a255-4e1e3c3bd87e', 2, 1399, N'1001193', 23394.495, 3166)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0e2d76d3-9fab-4156-9007-4e25d24505c4', 2, 1399, N'1001737', 49503.31383724411, 1722)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eb3fcc96-e31e-4d4d-945f-4e29cec6129e', 1, 1399, N'1000522', 18242.079999999998, 19275)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0c297059-f2f7-4bd7-b2f7-4e6b54ab9124', 1, 1399, N'1001617', 180014.61377870565, 6596)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4fb4750f-0051-4476-8b94-4e7496a12988', 2, 1399, N'1000876', 489307.85069762537, 1846)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e77765a8-9b3d-4eaf-be00-4e87dd117b5c', 1, 1399, N'1000622', 63547.964843337744, 2693)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c12f510d-b410-4411-aed9-4ed05b07e0d2', 2, 1399, N'1001553', 392966.36100000003, 12)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'912c1ccb-fecf-4b79-a84b-4ef2d934858a', 1, 1399, N'1000828', 209877.19, 3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f4ace9fb-4775-47ae-848e-4f2e6a2acb10', 1, 1399, N'1000658', 3532.6361244028863, 4727)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3a8a05fc-9ac6-4e18-a6eb-4f355f0c040c', 2, 1399, N'1000996', 19389.475491104637, 830)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4e112463-a602-4b5d-9738-4f4546b0fffe', 2, 1399, N'1001717', 14678.984616065714, 5600)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'629c06b7-afd0-4bde-92bb-4f539c654252', 2, 1399, N'1001063', 27528.610977895631, 3409)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd7d138e9-707b-4b41-ad31-4f5fa6863e91', 2, 1399, N'1000018', 42540.343533996049, 5917)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd3ed0e6d-e379-42b5-bf6a-4f6ab0dee10b', 2, 1399, N'1000011', 16247.798032942579, 13440)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2ad45b1e-5103-4f5f-a228-4f71cc9c5d36', 1, 1399, N'1001193', 20893.960699526422, 5436)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'61bea832-4afe-4bde-864b-4f7b4646afb3', 2, 1399, N'1001353', 49945.291297233569, 2214)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5c3faefc-bc09-4e2d-aba5-4f9bf6df9da3', 2, 1399, N'1000142', 47706.422, 1946)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0ef17e2e-90bd-4f94-aa1c-4fc60d89d519', 1, 1399, N'1001376', 104092.11000000002, 923)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c6cbb7d9-da29-4c3b-b388-500309426e87', 2, 1399, N'1000659', 13761.809198721101, 3765)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0ed9c900-dca1-46a6-b676-5026997f41ba', 1, 1399, N'1001527', 636293.29375687113, 893)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d06e6ed-d066-4cd9-ab74-504a112537ea', 2, 1399, N'1000157', 240000, 534)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd4050e52-1be0-4423-9bc7-504e14dd46c4', 1, 1399, N'1001325', 59266.06, -2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e1ec0c34-a05d-4fc3-bd28-505bd6a2e6c4', 1, 1399, N'1000383', 332626.650980009, 1194)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'226cfab6-204f-400c-ae5d-506d307ee773', 2, 1399, N'1000551', 119693.03223492391, 1258)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5bcebd0e-3adc-48f2-812f-50785eb968d8', 1, 1399, N'1000634', 300850.07, -2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'926d755f-37b9-4948-8e22-50832f1a6588', 2, 1399, N'1000842', 238654.53105617978, 899)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6b4d15bc-f5dc-4f70-857b-50e9fa0ea823', 2, 1399, N'1001568', 151629.09189772958, 289)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'311386c1-5f3c-48fe-85f7-5112a5abcdd3', 2, 1399, N'1001297', 204594.59299789715, 395)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5b2f461e-5834-42ff-891e-51ae739753a8', 1, 1399, N'1000824', 34474.38, -14)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'89e442f5-32ad-427f-8de7-51cfdeff6846', 2, 1399, N'1001625', 67889.908, 17519)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'538db025-f53f-4775-939e-51edfed813df', 1, 1399, N'1001525', 79538, 1045)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a995e01a-4b81-4d36-8e3f-51ffaaac850d', 1, 1399, N'1001473', 54330.643566319166, 1572)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6637fd9b-836b-41b9-a543-520cc6766155', 2, 1399, N'1001671', 126100.29498525074, 437)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eb1c3935-9ed5-4246-a73c-521c8f65b00e', 1, 1399, N'1000628', 24437.969931815136, 13628)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'11e8107a-9c15-4a1e-887e-524e5c0c0427', 1, 1399, N'1001075', 113091.04000000001, 34)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8904e43f-660c-4020-89e5-52536e3c2a31', 1, 1399, N'1000532', 53807.57115752915, 1808)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'574318f7-8e3b-4819-89d5-5266857a91fe', 2, 1399, N'1000866', 113768.41784200202, 1679)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4f0521cf-0fb3-44d3-a922-52738fe2572b', 2, 1399, N'1001191', 44041.83624992468, 6826)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fa68d74d-0c26-47d1-9be0-5276bb36a9ee', 2, 1399, N'1001288', 37108.736763892535, 5205)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4161a5db-e9e8-46e7-90b1-52883cb5ee1e', 1, 1399, N'1001120', 107999.88999999999, 5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1ed9a88d-8f90-4250-a9d6-52a6681382e9', 2, 1399, N'1000025', 16714.770945385455, 7783)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'30b877c8-0a81-436e-b798-52c5456c91fc', 2, 1399, N'1000505', 3533.7798949081052, 17245)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a2d5e6dc-7cc5-4171-ac30-52dcdc2bc006', 1, 1399, N'1000096', 21137.84, 100)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c172f76d-1276-4afe-84a8-52e5fb726adb', 1, 1399, N'1000267', 103325.65252717392, 118)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da8634a0-3dc7-4b43-bab9-53045a65054d', 2, 1399, N'1000852', 71891.558319125659, 8015)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'adcaad62-7c24-4338-b749-530b1beaacea', 1, 1399, N'1000191', 41374.329224051748, 1920)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6322d27f-1ed8-45f0-88e1-53414b53d43d', 1, 1399, N'1001171', 47514.29, -428)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0bd0aa04-c102-4997-bfff-53503c2f0a2c', 2, 1399, N'1001296', 206244.30379746837, 119)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c6a1f3b8-49c5-4e97-a71b-5350c7f613db', 1, 1399, N'1001055', 54001.225407414146, 9262)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bac4bf11-a21d-45ae-a4f3-5357fe44ffc5', 1, 1399, N'1000489', 419877.39347816881, 2181)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7c25cd8c-38b6-4f63-ab85-5389d24177ff', 1, 1399, N'1000764', 133032.69068613136, 27)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bcbffe81-a935-4d78-9787-53977a7c97ab', 1, 1399, N'1000341', 61682.575245001673, 17306)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'69d99f53-73d7-4b10-9ec7-53c1dd1027b2', 1, 1399, N'1000857', 53710.75, 78)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'80f885b2-6ebd-46e5-9d43-53d961fe9b8f', 2, 1399, N'1000383', 333744.5514041998, 1392)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'be7c3706-a7b5-469c-85c5-540bacc1f886', 1, 1399, N'1001365', 29045.625894278935, 3085)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c0dbdec0-300c-41c1-953e-54215218e586', 1, 1399, N'1000133', 47621.255504894405, 1083)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a9011c43-a825-4c53-8cc2-54685ec0ee66', 2, 1399, N'1001702', 81011.20896409289, 1186)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'44aa49b7-884d-4cc3-8ad0-546f49830e1e', 2, 1399, N'1000314', 99086.269740150165, 488)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'34fb97c3-c138-4a57-afeb-54748725786a', 1, 1399, N'1000007', 13217.490730818374, 10814)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3c884f4f-77bd-4d15-9383-54bfb1c29e47', 1, 1399, N'1000918', 110844.27544141866, 2872)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd0810773-d8cd-4be9-82e6-54fa257fb385', 2, 1399, N'1000478', 61886.977888774505, 1801)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3ae6a303-6859-483c-8843-552675f8ce5b', 1, 1399, N'1000929', 240748.44, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'456a9710-3f56-4477-b68c-5537580fb962', 1, 1399, N'1001425', 1178109.1557861178, 238)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8783d851-184d-4b9e-8723-5552fca50385', 1, 1399, N'1001145', 61999.930000000008, 14)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9cf62e16-4520-49a6-a83b-55700888cb26', 2, 1399, N'1000130', 105504.587, 132)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'83f70a94-6907-49c9-a7ba-5574dc1c7819', 1, 1399, N'1001418', 181974.83999999997, 38)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'571a4063-ed23-4cb9-ada6-5602c0dea686', 2, 1399, N'1000702', 158496.38299069382, 1680)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6bba5630-7409-4b64-a693-56179c75c211', 2, 1399, N'1000711', 48167.218137893477, 9950)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'aaaeb8b4-630e-41ad-9ebc-561c371aef4b', 1, 1399, N'1000279', 119172.53999999998, 10)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b38219cd-93b5-447a-b001-562ffa28985a', 1, 1399, N'1001371', 90165.790000000023, 295)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ee9bf700-c740-4021-b657-56374eb41adb', 2, 1399, N'1000180', 67523.886871775278, 922)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'47e14e11-67f5-4636-878d-563de386642e', 1, 1399, N'1000084', 92186.99059462687, 5202)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4ea5f427-1ed5-45cc-8fb4-564177ca2b54', 1, 1399, N'1000159', 95253.128364555043, 2667)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9856627c-35dd-4353-b68c-565c525a7eee', 1, 1399, N'1001539', 111571.76581539976, 761)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9a2af84d-fde3-446c-b6f3-565ef75eada8', 1, 1399, N'1000854', 122664.42197840527, 4543)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'39e6cb13-83aa-4383-a2a9-566db1dd66f0', 1, 1399, N'1000114', 474457.79356317094, 6595)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8a291f27-2aa6-4e07-9ab1-56794a4fef30', 2, 1399, N'1000817', 209475.28822095355, 987)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'86d594ca-1e42-401e-8b9f-569e49f97c53', 1, 1399, N'1001636', 22069.440000000002, 3018)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0888275f-2fde-487e-8513-56aa21569098', 1, 1399, N'1000787', 51976.149999999994, 26)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'93ae3a06-856d-41c9-bdec-56b78037eed7', 2, 1399, N'1000461', 10733.633722468108, 10813)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4af9a1f7-fe2d-4d97-bb68-56bf9cc87bf8', 2, 1399, N'1000131', 71989.4845994063, 1244)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'42243209-38ba-4998-9146-5743120ec750', 1, 1399, N'1001074', 108947.45, -452)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0b038e19-7f69-4990-80f8-5761a6a622c3', 1, 1399, N'1000805', 769115.07520000031, 250)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5cc805a8-846c-405a-8be5-578b09a6b02f', 2, 1399, N'1001562', 50188.052862631113, 825)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ea145e65-4b19-405d-a1e8-57b1a9a5700e', 1, 1399, N'1000608', 43892.6941117854, 6587)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'08ef067d-da2f-4157-a729-58070ed99021', 2, 1399, N'1000207', 613558.28220858891, 863)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6053294e-e165-43dd-badf-581eac57e422', 1, 1399, N'1001289', 232800.19546048343, 506)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b4784663-e8b1-4688-ac10-585735cca686', 2, 1399, N'1001650', 48468.468888656927, 2870)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'313f38ea-dfd2-4e46-ad30-5857c22b1d4f', 1, 1399, N'1001439', 30137, 11)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9b1b5392-8be7-443b-9f68-58710c4ffece', 1, 1399, N'1001052', 87578.49326198388, 2251)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'597d6aaf-dad6-4387-92ab-58945b72aca8', 2, 1399, N'1000105', 72212.198577918083, 2514)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6f3deaf3-5b95-458d-91d3-58d5994e8361', 1, 1399, N'1000026', 16530.987042864017, 6992)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e1b1aa15-4afa-4b17-9739-58dfa14ee397', 1, 1399, N'1001338', 31517.850000000002, 2837)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3d625745-4ade-4393-8fec-590196b8260a', 1, 1399, N'1001495', 52306.422568541224, 3304)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'51079574-935e-451f-a321-5932906fbd1d', 2, 1399, N'1000700', 110984.20259770406, 4731)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'beb7d204-5b7a-4abc-ad03-5942e95f8a3e', 1, 1399, N'1000421', 240909.02000000002, 102)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f4feab39-49d5-4d34-a7d1-598ed7ae3bc1', 1, 1399, N'1001542', 20910.874013604553, 7069)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9c19d8a0-843d-4fcc-8e9a-59b780a30559', 2, 1399, N'1000629', 13942.555790488888, 7636)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6d1dca6a-856a-4ade-8ae6-59bccca8cffd', 2, 1399, N'1001630', 161982.3924623825, 2151)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1a7d3820-42a3-4e5e-81dc-5a03383c7524', 2, 1399, N'1000234', 80288.800888990911, 1092)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd1f6e1c2-18ad-4dc4-995f-5acd624575ba', 1, 1399, N'1000609', 35550.829999999994, 11295)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da56e08c-7c07-451d-b227-5ace4171a2f7', 1, 1399, N'1000936', 16722.550000000003, 315)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0155bf6e-a949-4d81-908e-5ae033ffc6c8', 1, 1399, N'1000807', 754948.288015395, 366)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'25b7b551-1970-49f8-bfa6-5b02b4687dd0', 2, 1399, N'1000209', 823964.98054474709, 1097)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e7e2a940-2c18-44f9-b977-5b0a9e76ecdc', 2, 1399, N'1000781', 59925.283522982572, 1834)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a9c324b7-054a-4664-84dc-5b2abcf09f25', 2, 1399, N'1000582', 14139.105891015317, 2014)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7f1ca453-c5ec-48b3-94f6-5b413be06c2a', 2, 1399, N'1000699', 277530.33821137343, 1496)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'909c5e9f-24c6-4bfd-86e9-5b44d7b1ac9d', 1, 1399, N'1000668', 61852.84616859274, 2647)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b2d4750c-178e-49ce-a29f-5b4764964bb2', 1, 1399, N'1000949', 223347.95027010873, 1699)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1938b59e-742a-4ad9-bb3f-5b7c2754214b', 1, 1399, N'300003', 156642.9, 19900)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cd9fb61a-ad86-4116-9aaa-5baa8b841729', 1, 1399, N'1000470', 6605.42, 97)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'15328785-c647-4832-8255-5bb637265f4b', 1, 1399, N'1000973', 14133.333046229351, 1543)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'856db83b-ba9c-4309-b239-5bba07237f5d', 1, 1399, N'1001382', 210963.11, 18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6f4fd973-f770-4a52-bb51-5bc198650f92', 2, 1399, N'1000291', 41152.028002154009, 225)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ae78f7a2-fbfe-47cc-a5f4-5bd1a9682bf0', 1, 1399, N'1000300', 24272.206249750016, 2919)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bc2c5224-2a71-4df8-b7d1-5bf4e1a1ab9a', 1, 1399, N'1001141', 45000, 51)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'87292da7-9753-490e-8960-5c1842723a81', 2, 1399, N'1000605', 164873.7000260916, 2613)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c4843ecc-fae6-4105-a768-5c3cdffe5ce9', 2, 1399, N'1000272', 19503.126721664485, 4153)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2ed5403a-af8c-4c46-8c1d-5c6910e7a606', 2, 1399, N'1000467', 69304.730211552174, 6119)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2470d3b0-d9cb-46bb-98ff-5c735a2206f8', 1, 1399, N'1001392', 44011.490865764928, 495)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'505b13d9-ad7a-415a-bfc9-5c737644152c', 1, 1399, N'1000017', 42375.57, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'47f4dc49-180b-4d8a-9fe6-5c7f90907865', 1, 1399, N'1000135', 54800.526517671511, 1771)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'25471720-3d55-4845-a4ab-5cadbf4fc8ef', 2, 1399, N'1000238', 51387.7460384565, 1849)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'355cb744-eea7-4e46-a3a2-5cb12ec55be8', 1, 1399, N'1001402', 118569.17999999998, 50)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bb59c444-116b-4cad-b956-5cda491a86e4', 1, 1399, N'1000717', 24220.319761541967, 3592)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ebe94d08-3b30-4936-bcc7-5cdf3fb9abc6', 2, 1399, N'1000674', 10606.170004130656, 6225)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5265d501-5a39-45a2-bf03-5cf6002a284d', 1, 1399, N'1000471', 16514.135831619536, 8057)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dfb9a1b6-96e5-4e13-b79e-5d240ef72211', 1, 1399, N'1000958', 221744.94000000003, 18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ead904be-4e6e-4ed5-8c4e-5d34e6819f77', 2, 1399, N'1001037', 77981.651, 1275)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a318086d-5b52-4c26-bdda-5d3f96b2d99e', 1, 1399, N'1001022', 393144.69999999995, 18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'efca5413-a304-4c40-bc69-5d4760105537', 2, 1399, N'1000886', 293737.99577123334, 3232)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0cb648e6-1f04-4977-b777-5d90587e570d', 1, 1399, N'1000662', 167074.69280392482, 3716)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'64f85afe-84b0-4e2e-b2e2-5d9d6ba0ece7', 1, 1399, N'1000935', 16553.199999999997, 796)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cc4ee775-d3b7-472d-b0b8-5dacbaa310e4', 2, 1399, N'1000626', 11834.862, 8726)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ef9bb416-8b34-454a-a6ad-5db4c45111ae', 2, 1399, N'1000287', 17000.754532462663, 1413)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'52a0446b-7b3a-4ef7-ba60-5de7188b7098', 1, 1399, N'1000268', 22254.04914795496, 1497)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a3aaa135-e4e1-4241-a9ae-5e06100dc523', 2, 1399, N'1000959', 287202.02108100953, 2175)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'35509001-ea4b-4088-bd1d-5e2e33844c78', 2, 1399, N'1001677', 66056.221476711929, 2076)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a45a4fec-3370-4692-8c40-5e5587e39e3f', 1, 1399, N'1000199', 35000.708179728434, 85)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd3cac53a-11c1-4a0d-8b1f-5e767ab77741', 2, 1399, N'1001707', 1376146.789, 642)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8573b4c5-f5c6-4cce-9271-5e8bf03de975', 2, 1399, N'1000258', 72898.723416530644, 1464)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e9a741c3-9d74-4580-a57e-5ef890fde315', 1, 1399, N'1000157', 196029.39838927376, 1508)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d3e1aa4-e521-4540-896b-5f112aecd5fa', 1, 1399, N'1000095', 23119.02, 8)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b73e4083-fe4f-4b54-a143-5f6da986ed99', 1, 1399, N'1001446', 309646.40396363643, 268)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd5f07c7c-6b98-444f-bb9b-5f81e85a4d5f', 1, 1399, N'1000340', 286562.1888831465, 1164)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6339dc42-02cf-4e95-b243-5faf7402700c', 1, 1399, N'1000527', 102300.54083151814, 3291)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'db07eadd-edc5-4a85-b53c-5fc10ce03e5f', 2, 1399, N'1001395', 65137.615, 13)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'12fc344e-f653-4c42-8de5-5fe1fdd9c0a5', 1, 1399, N'1000257', 107692.84496833169, 1831)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e5ca2e78-a4a3-4688-b663-5fe47e4e7979', 1, 1399, N'1001496', 100617.77944936937, 1883)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a79b8b6b-1616-433f-85be-5ff50a0aa772', 1, 1399, N'1000021', 39636.792837162007, 1772)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'54be44ef-ca62-4965-a074-6022fcae9f99', 1, 1399, N'1001374', 55233.063507095751, 7106)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'beae9e51-e62d-4e77-9288-602686386d6c', 1, 1399, N'1000050', 118771.61868382612, 3793)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e948793a-bfce-4e91-87e7-602e979d1e97', 1, 1399, N'1001130', 219300, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0496d367-1b4b-4d41-9c21-60cb00e5126c', 1, 1399, N'1001233', 268375.6341649433, 519)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'72c96952-a578-457f-9dcf-60fd1327089d', 1, 1399, N'1000149', 126025.38362563234, 500)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ced7926a-b084-4813-b8e4-611b2f420564', 1, 1399, N'1001448', 85136.75, 184)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'978eadb9-50a9-4702-8107-612b6426cb58', 1, 1399, N'1001142', 67999.94, 6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a1f26603-b0ab-4c47-b34a-61328ada00f3', 2, 1399, N'1001653', 392044.12989175686, 2744)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'73e77f83-91c5-40f5-8f42-6137044fe0d2', 1, 1399, N'1000287', 16995.03625985303, 2116)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'98c3cc08-2e24-47b1-af7b-614349e1de56', 1, 1399, N'1001561', 321387.01174293988, 236)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'222d524f-e619-4611-8889-61673fe63138', 1, 1399, N'1001430', 722083.67904091417, 204)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6420e05e-d834-4e91-ba56-617f69da3ac0', 1, 1399, N'1001107', 87638.737973001465, 15516)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'57ecf167-493d-4f2b-acde-61b243576c0b', 1, 1399, N'1000406', 24827.032439187307, 3469)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5017ce8b-d939-469a-a8e7-61d91fca0263', 2, 1399, N'1000767', 54357.517276294631, 783)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'de833afc-2bf6-4f23-9442-61e35ab6cb40', 2, 1399, N'1000148', 152339.01543169378, 2904)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'df71d11c-4db9-4482-9231-62193c963636', 1, 1399, N'1000214', 19597.906327137687, 14861)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'382d06f8-f021-450e-959d-6228bf013bf7', 1, 1399, N'1000487', 230496.47148680393, 456)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e7d36fc9-300d-4eae-961f-6249db1b93c1', 1, 1399, N'1001087', 242915.9420289855, 1650)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'31ad1dd2-d825-4e6a-938d-625fe89ddede', 1, 1399, N'1000909', 119634.64014380824, 2118)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8b977476-89fe-499d-ab9d-627129c5671e', 1, 1399, N'1001370', 28659.179999999993, 416)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da64148e-9645-4ddc-acf6-6298e635d4a7', 1, 1399, N'1000264', 69767.339952575028, 2739)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e736d09c-2848-40d0-adaa-629bca67c965', 2, 1399, N'1000487', 230703.21138211383, 146)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f52edc0a-0e5b-47d6-9ff2-62bf3d9671d6', 1, 1399, N'1001252', 76453.130123893789, 137)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'efdc00bd-2148-4c6f-be12-6334ae2d16dd', 2, 1399, N'1000251', 85345.948132403777, 1138)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6b522d55-1d82-4261-b76e-634a75180dba', 2, 1399, N'1001545', 105504.587, 532)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'773a2053-3e05-45b5-8741-6361f2619744', 1, 1399, N'1000892', 82195.34, -14)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'14ba287b-74d3-420b-a33d-6379bbef170e', 2, 1399, N'1001194', 23394.495, 4375)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a1d2ed4d-e7e2-4ee9-a975-63805d0a33dd', 2, 1399, N'1000765', 176324.70677044059, 948)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3f075419-720e-4df1-9395-63970526205c', 2, 1399, N'1000471', 16522.322264185153, 5279)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1f62743f-fe3b-4a23-a2e6-63c8b91dc1b1', 2, 1399, N'1000662', 168765.405478343, 3598)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9f069920-9f05-4089-8ed3-63ce9a4776e3', 1, 1399, N'1000750', 52460.659556280596, 1130)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd2d4595a-afcb-49da-85ad-642afd35bc63', 1, 1399, N'1000731', 74015.737844253046, 1532)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a650286c-c461-4fda-881d-6445cbb46d8d', 2, 1399, N'1000045', 77991.852114570531, 3155)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4cc3ff57-f52e-4597-8e06-6466639da455', 1, 1399, N'1000183', 22501.101483330887, 1021)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'37649157-dbff-4471-9dd0-64824367e634', 1, 1399, N'1000521', 48310.18659640423, 580)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'526bebda-cf3f-4e1b-a97e-648753dc1c6f', 2, 1399, N'1001750', 220182.89531337947, 1248)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3c722da9-47b4-4b52-8a22-64a85f8d3c5f', 1, 1399, N'1000059', 158537.89054756906, 1066)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e08f7542-6af3-49b7-b400-64ae298da003', 2, 1399, N'1000043', 7555.87768879868, 10070)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'23d4f9ec-d8e2-42a6-9d52-64d26e4758d6', 2, 1399, N'1000570', 78998.264317923182, 4777)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ecb7b112-1bd9-46a6-9b0f-64d661b27dc6', 2, 1399, N'1000485', 140461.43568691047, 19)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9989e56f-a8fe-41fa-9dde-64e21c030e14', 2, 1399, N'1000201', 17890.685358024752, 5889)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c42694a3-c32f-4b9a-94eb-655fbc52594c', 2, 1399, N'1001683', 131395.39048728781, 1530)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ec445086-7a34-4bdf-9a27-65e9ade2c051', 1, 1399, N'1001540', 349678.1017941953, 223)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'474ee7bb-a2fd-4e1f-ad8e-65f4da54c696', 2, 1399, N'1000995', 19439.489491384305, 1094)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'570c0ea4-1ac7-433e-a412-661398d1469b', 2, 1399, N'1001088', 170193.5038009675, 7813)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5f7fcb98-fa3a-4d49-91b5-661463e15d15', 2, 1399, N'1001673', 98463.466045114488, 2475)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'139a6f1b-a977-4a71-b24c-662230782fb0', 1, 1399, N'1000108', 78110.139116882565, 2137)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'13f65f4f-fbb0-4858-9321-6626100e5f4b', 1, 1399, N'1000629', 9448.59, 13905)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'105c5676-b914-47af-ab02-662d8aaac1e9', 1, 1399, N'1001589', 610090.81000000017, 96)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1064c3be-9bdd-4ccc-8ceb-663784e9b627', 1, 1399, N'1001587', 317063, 570)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5c1cb121-414d-4dd4-819c-66698b08497e', 2, 1399, N'1000895', 28623.129046849361, 2636)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5691e892-80fe-458c-9bb5-666c57e447b5', 2, 1399, N'1000716', 146899.17909134971, 1168)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd04ec6b5-2465-4ec8-9e64-668f4f5ee54b', 2, 1399, N'1001064', 206141.59910506636, 1220)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'59c52846-3ce4-4787-a99f-66bb12efc259', 2, 1399, N'1001477', 137651.48908883467, 1214)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'28b0c4e5-82c1-4332-b7ae-66c98c9904b4', 2, 1399, N'1001282', 52540.852819659958, 3763)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9cebf8b0-4f79-496a-ba10-66dada073867', 1, 1399, N'1000141', 54770.389999999985, 1055)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'11dd31aa-f90c-4066-80fd-67005cdd7e57', 2, 1399, N'1000203', 36694.880205742578, 3412)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5922299d-3a22-4e08-ac34-670544c48b3d', 2, 1399, N'1001555', 48532.11, 63)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6bcf62a6-6dbe-45f4-93f8-672b97036e56', 2, 1399, N'1000110', 11567.261453190176, 8025)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'84e768f7-7967-45da-9fac-672ba5639a62', 1, 1399, N'1000883', 38533.383697025551, 4543)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'764cf094-385e-47df-8282-674a031b9280', 2, 1399, N'1001060', 749000, 48)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7b0eb851-3781-4df1-bca2-6753711ad4d2', 1, 1399, N'1001109', 106516.39853147575, 64)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'07f15a70-d705-4857-9f30-6754c2cc49df', 1, 1399, N'1001161', 218917.42999999996, -17)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'08312e03-58cc-49a8-81d4-675f266cab51', 2, 1399, N'1000760', 38546.259243183238, 14652)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'83acceca-5b63-457e-8dff-677774ffc032', 1, 1399, N'1000708', 424337.93127109, 1193)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9143d31c-4e41-4360-911c-677932c89cf2', 1, 1399, N'1000056', 44301.2448309486, 1182)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'408365ba-cf0f-4cba-a016-6789418994f3', 1, 1399, N'1000459', 13763.831565837092, 13290)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3e78a275-4ccf-4271-84d0-67aac58f7731', 2, 1399, N'1000875', 61164.820715623267, 22600)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ae55e7c6-07ef-42e5-8c8a-682890be5d05', 1, 1399, N'1001577', 50767.200000000012, 4730)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'41c1dc90-f28c-4590-9352-6865482c3bba', 2, 1399, N'1001413', 80035.408338079025, 1137)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'07418e03-67ca-4526-9c78-6876572293ab', 2, 1399, N'1001261', 171559.633, 1489)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3da9d52d-0540-4784-bc06-6897fb8c23f1', 2, 1399, N'1001233', 268435.53964472591, 1080)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eb434be3-159a-4898-beb1-68d715a0f7f7', 2, 1399, N'1000057', 46132.640656792326, 3286)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'437ba9a4-e178-4fd2-9780-68fbf5a82f5d', 2, 1399, N'1000899', 33027.186569862286, 2310)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'109fdb59-152f-4124-b31f-690131f3905c', 1, 1399, N'1000771', 72688.227150977, 1099)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5e329163-0b32-48a7-b0bc-6903e750d8a1', 1, 1399, N'1001167', 48799.99, 26)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ceed584d-d416-48b1-a530-69156fd034c0', 1, 1399, N'1000895', 26003.516853998655, 1658)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'106ca7e0-acbe-4792-9d2b-6923e4ba2b9f', 1, 1399, N'1000023', 14006.262871370143, 6905)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dbba483f-e527-4e83-b2e8-6934c525439c', 2, 1399, N'1000228', 17890.320569630247, 6937)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3d35406e-185f-45e3-b007-693ec43a8957', 1, 1399, N'1000655', 7083.3470805871548, 18206)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'80140f80-48cd-41ab-8b12-696d31df2e18', 2, 1399, N'1000213', 29357.940510963039, 11999)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5aafcaa2-7db4-4ca1-85a2-699bbb2d30a2', 1, 1399, N'1000015', 28031.56, 23)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3dfb4e42-cedd-4ff1-a44c-69addf7f8b6e', 1, 1399, N'1001266', 330827.38255033555, 562)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'45240f9a-d97b-432e-9fae-69c000854770', 1, 1399, N'1000767', 53017.873464518, 833)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cd7c075c-f609-41d3-a403-69c3096f4795', 1, 1399, N'1001260', 29368.560333333335, 1398)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4bd1d50d-5bde-4962-ac7b-69d63051c3f2', 1, 1399, N'1001431', 46704.392372505557, 1409)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fb481b3f-da40-4083-ae4e-69d9003b4ca5', 2, 1399, N'1000281', 16401.021365083467, 6588)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5e0b6472-22dd-4e4c-841b-69da2458ba29', 1, 1399, N'1001199', 20606.242184915529, 11316)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ea131e0f-b37e-462b-af65-69fa7b671cab', 2, 1399, N'1000877', 179990.30422390765, 2357)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c3c971b3-6efa-4346-8d81-69fd74b7a514', 1, 1399, N'1001651', 209171.1468679971, 625)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a51c9331-a667-42e5-a3bd-6a26e5f74124', 1, 1399, N'1000054', 105081.60191340208, 4370)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b5546473-61c4-4ce9-bf25-6a4c43a1538d', 1, 1399, N'1001514', 89457.652035194886, 4317)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'17e1abdc-3992-4585-a4ed-6a566fe433de', 1, 1399, N'1000179', 80893.389106761577, 4055)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'84237ce2-e625-4028-a86c-6a5880b765a0', 2, 1399, N'1000519', 49000, 217)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'aac769f3-0b3f-4117-a6b0-6a96de0fab39', 1, 1399, N'1000256', 305590.66865384614, 18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'72438355-e7f7-4db3-aae5-6a9ba23da052', 2, 1399, N'1000411', 72569, 2042)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b0c73163-7cfd-4ed0-84c0-6a9e4ac75069', 1, 1399, N'1001632', 16101.63974821649, 12796)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'807f6fda-e723-4bf7-99ee-6acb7b15f26e', 2, 1399, N'1001290', 65137.396517900786, 4464)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7c910847-f97d-4619-b764-6ad8cb9ea7f8', 2, 1399, N'1000512', 14129.727627131158, 6198)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a65df30e-fc73-4d24-b9a4-6af9c19d468c', 1, 1399, N'1001339', 220690.80886864243, 1387)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'55ae841e-24e4-4923-97bb-6afd9ddfe5b4', 1, 1399, N'1001126', 104999.98000000001, 5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f877e662-b8bc-41f4-8419-6afe8d867526', 1, 1399, N'1001219', 572189.21342354524, 400)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'09898e35-3636-4d83-88f0-6b0302ffb067', 1, 1399, N'1001355', 79999.914535759279, 1424)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3fbfeeff-3cef-465e-80da-6b1b61ff6685', 2, 1399, N'1000183', 22503.458611943741, 1014.99)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8a44e35e-dfa6-44f8-bf19-6b3d79495678', 1, 1399, N'1001290', 64938.391211243877, 2774)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b3ef3568-a468-4a50-ba2d-6b536879e954', 2, 1399, N'1000836', 90825.688, 1610)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bd0670a1-72b3-4c70-ac29-6b6116e54eba', 1, 1399, N'1000790', 52491.119999999995, -2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b777a45c-0eb8-4bea-8944-6b7cebf8b126', 1, 1399, N'1001513', 119271.11299127276, 3328)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'937dd050-d049-4c53-b9dd-6bb86c66cc47', 2, 1399, N'1001183', 187200, 2235)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5ed34223-57a4-461f-89a0-6bc5104209c2', 2, 1399, N'1000173', 57631.132826690809, 3781)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'67e79552-ac2d-48c5-ab62-6bc89be95099', 1, 1399, N'1000465', 25044.714564144706, 1145)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7a821572-965f-41c1-9d43-6bdef690a250', 1, 1399, N'1001177', 131950.66, -38)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'213602f6-3423-4b8c-b384-6be01054eea6', 1, 1399, N'1001104', 2793526.1257310789, 384)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'25813951-f615-49f4-8ad8-6c0e350db40b', 1, 1399, N'1000802', 148775.48, -1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'94250ab6-9828-43df-a2c0-6c27fdd5d7eb', 1, 1399, N'1001618', 19763.78446336761, 7910)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'176f9fb2-455e-47fc-9d23-6c36c4c10cfd', 2, 1399, N'1000774', 36120.107629189828, 897)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f9ef901c-2e4b-487e-9771-6c469d761b91', 2, 1399, N'1000863', 54586.949106554988, 1528)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'70fe3304-6153-4a88-b63a-6c5e518b24c4', 2, 1399, N'1001340', 33039.313798134375, 2280)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b842bd67-bad5-46a8-934b-6c6540ec56ab', 1, 1399, N'1001051', 87579.0681693909, 2196)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6b0c6e09-8d90-4a89-baaf-6ca4e91f35fd', 1, 1399, N'1001628', 2606.0518825766217, 129233)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1918953d-73ce-45de-bf70-6ccf794a4a44', 2, 1399, N'1000769', 26795.658572627392, 555)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9c92c0df-50e0-48a9-9f34-6ce5839cb15f', 1, 1399, N'1000542', 128226.31700942213, 1028)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eda10b50-91bd-479e-8bad-6ce6696ac24b', 2, 1399, N'1001736', 116014.79519703695, 60.845)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3ad2638b-fb2e-4d80-b2b0-6ce67fa39e6f', 1, 1399, N'1000163', 42890.602176529595, 270)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7f6fef4e-8b9b-42b4-abe4-6d64d8907015', 1, 1399, N'1000646', 1071190.5900000003, 171)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5ff5f68c-b7d0-4db1-a320-6d695ab95f63', 1, 1399, N'1000009', 33142.86775949382, 6447)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5990ccb5-f856-48cd-ba1a-6d8ab70f15b9', 1, 1399, N'1001623', 313735.12481644639, 1637)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'68c670b9-b1ae-4c85-9e56-6db24ed96dc6', 2, 1399, N'1001050', 88990.826, 2170)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'71526cb3-c2c1-462b-810d-6dcfb5e2d62c', 2, 1399, N'1000920', 68807.339, 42)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'30b5fe7f-817b-48ef-b967-6dfa67cbb4b4', 2, 1399, N'1000731', 87999.7226414852, 2386)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'21d094ee-bf54-4f70-ac0e-6e1226826088', 1, 1399, N'1000584', 14133.221759093, 1731.99715111)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'42129bca-a482-483b-a454-6e1ae6b30335', 1, 1399, N'1001298', 63885.685351170541, 329)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9bbf9c33-733a-4fcb-a51d-6e3a0b75ffa7', 2, 1399, N'1000807', 814423.46583807, 367)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'80f3e30a-c932-4ae2-a128-6e546faab8a6', 1, 1399, N'1000463', 14310.986739082728, 6007)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dd29f9a1-4821-42c2-bff8-6e8e91bf4a8f', 2, 1399, N'1000407', 26508.305514683798, 2936)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'89753e44-47aa-48ff-a754-6e9bd8688ddf', 1, 1399, N'1000254', 67135.05, 9)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5e4eee9b-8213-476b-bf5b-6ebda703a12b', 2, 1399, N'1000882', 38533.909796953936, 4425)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'633049d8-fe6e-4088-aec5-6ec8e6eee8c2', 2, 1399, N'1000023', 13973.950759476165, 8787)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cdd95c5f-4dc2-4872-ba34-6ed31e450c38', 1, 1399, N'1000042', 14010.062755427405, 8429)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd21c20b5-eb80-4c07-8c5a-6f03af01da06', 2, 1399, N'1000214', 29357.878707371146, 13855)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'13af7913-91e6-4f6b-8571-6f364ea2f64a', 1, 1399, N'1001029', 19266.18, 83)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'903a2ed0-826b-44d5-87b5-6f5f38f50ec5', 1, 1399, N'1001634', 22069.440000000002, 1148)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c93565e0-3e64-4789-b77b-6f7d2877593a', 2, 1399, N'1000202', 34252.526228348324, 10184)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd065f52e-0352-4fae-af92-6fc7a5b59c07', 1, 1399, N'1001168', 48799.95, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3981ad2a-35d0-40e4-b283-6feeb1ca1dcb', 1, 1399, N'1000758', 76234.30415384614, 4116)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1597817c-07fb-453f-8c8d-70039304a0af', 1, 1399, N'1001306', 67025.48461538463, -128)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'64f2bfe2-58d7-4c67-92f9-700fb124d3d7', 2, 1399, N'1000934', 36481.867196375191, 8929)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a00f358b-8705-4735-beec-702019c284bc', 1, 1399, N'1000098', 52843.37000000001, 45)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'757a8f5f-6370-4f98-a9dd-7073e4c4a6ee', 2, 1399, N'1001370', 35779.817, 95)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c9929aac-fd0a-4691-973a-70aceee70dcd', 1, 1399, N'1000049', 70577.780000000013, 21)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'64bd5395-bed3-4773-910b-70c1589c391c', 1, 1399, N'1001060', 728406.42, 58)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7baee7f8-d5f6-41ca-8b25-70eb8291ff08', 1, 1399, N'1001181', 34941.089999999982, 28)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd4d514df-331e-4492-9cd5-70f0a7197d3e', 2, 1399, N'1001084', 175000, 129)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b640015e-d0ef-4e69-81e0-71162fd438ac', 1, 1399, N'1000859', 50835.506600973924, 2502)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'73914cfb-7481-468b-8101-717f8c737693', 2, 1399, N'1000750', 59960.266362753107, 3003)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3a06ee63-45df-4402-a7bd-71aeb3c6341e', 2, 1399, N'1000176', 240000, 140)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ea45dc38-b6e0-4af9-adc9-71bf15094c24', 2, 1399, N'1001238', 96931.043362136683, 1643)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5d4eb88a-d465-404f-9b51-725598aa8614', 2, 1399, N'1000874', 44691.752713801543, 13977)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1f0abbbe-7977-4157-b89e-72bdbe0bb43a', 1, 1399, N'1000765', 158363.84238970873, 1451)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dd97fa4d-24ca-465c-8a58-72c74e440d41', 1, 1399, N'1000868', 41284.589999999975, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'17d01893-2ce5-449a-82bc-72d374bfb635', 2, 1399, N'1001273', 18780.685936253845, 46454)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'036ce6d1-452d-48e3-b586-72d5c780f96b', 1, 1399, N'1000352', 24032.74, 27)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'23477ba6-4bab-4e97-ac55-72e0e20a7b9b', 1, 1399, N'1001202', 205871.23, 655)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'617a3357-7958-43bd-ae3d-731a8bc6b618', 1, 1399, N'1000900', 29993.77903312444, 2150)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f9bc1388-51f9-42b3-b8e4-734d9004d830', 2, 1399, N'1001303', 31800.682500261679, 535)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e3e536e4-29f7-45e4-a172-7352a8775312', 2, 1399, N'1001661', 106952.45941652569, 1471)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cbded86c-92f9-4ec0-a144-7380bab79ab0', 1, 1399, N'1000552', 82782.767504033414, 1902)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'274314ab-11af-45a8-8abe-73854db17a24', 1, 1399, N'1000215', 19259.303279927, 7162)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cd31537d-a88a-44d2-a7ec-739281ce744e', 1, 1399, N'1000144', 195932.37038971478, 1733)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7c984ba0-2fae-4207-af67-73c2ca9234a3', 2, 1399, N'1001295', 81420.088447488874, 370)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'12be8da7-167f-429a-b0d7-7414b2af7239', 2, 1399, N'1000141', 54803.496825842085, 1316)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1e425818-9470-4e98-88c9-7418964eede9', 2, 1399, N'1000013', 28358.550031505245, 5800)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1c1bc1e8-a44c-460c-9b0e-743958fd9554', 1, 1399, N'1001579', 61451.241207754785, 1599)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fea00d69-7921-4044-9bb5-7456e0c70977', 1, 1399, N'1000475', 11139.729999999998, 5290)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a213b0eb-949d-4d10-8037-74642133e999', 1, 1399, N'1000120', 233057.566413745, 1276)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2705ddf6-5972-4a0b-83b2-74923e655f33', 1, 1399, N'1001237', 90745.094428549972, 2229)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'51cb9e96-bba9-4dd9-b460-74ae6e0eb06e', 2, 1399, N'1000086', 50703.161612557931, 5756)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'61b77477-fac0-4911-8cbd-751158b0bad8', 1, 1399, N'1001637', 85275.466576323975, 2332)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e0597380-f5d4-428d-8c56-751ddcf90a29', 1, 1399, N'1001245', 309634.01, 46)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8acb94d0-3b8c-46bc-8229-756390e7bf84', 1, 1399, N'1000368', 126156.48192628023, 975)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c1245e02-0093-46e6-b190-75aa02fabaef', 1, 1399, N'1001478', 90459, 3360)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b27ffb9a-9159-499c-b289-75e6493ed59c', 1, 1399, N'1001277', 640161.21393134876, 649)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dad63249-f441-4b76-8d42-75eeee4382e5', 2, 1399, N'1000647', 442639.98676333163, 193)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5f12f551-8568-4b32-b263-75fbfd3fe966', 2, 1399, N'1001654', 105504.587, 148)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6dc1096e-a414-4605-877c-76049b937d3e', 1, 1399, N'1001666', 240000, 3000)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'af4a290e-a24e-4ed0-84af-7624b9213a4f', 1, 1399, N'1000627', 12675.119999999999, 9489)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f77a58cc-8572-4629-8f8c-76649ec1c495', 1, 1399, N'1001423', 94013.976631390455, 1884)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c6b34beb-ef22-47df-b380-76883c1a3499', 1, 1399, N'1000835', 82492.469999999987, 917)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'13b3de65-d1f1-4c59-be2c-7688eebbb488', 1, 1399, N'1001241', 187268.09, 165)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e5cccb3c-dee2-46cb-95ac-76a75a939942', 1, 1399, N'1000442', 38893.47, 2814)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'63b854a3-bd87-44ed-b3c6-76ad14abce3e', 2, 1399, N'1001724', 171770.72140619814, 146)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4184d10c-b2f6-49ec-a5f8-76bea273a588', 2, 1399, N'1001267', 235000, 888)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9b541318-1bd5-4e7b-ab92-76e9fca67392', 1, 1399, N'1001405', 6972.32, 10225)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'21f7048b-3644-4779-a305-76fbd3d1add1', 1, 1399, N'1000485', 139393.40045265958, 678)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2bab62c0-38c1-42da-8574-770974d33c24', 2, 1399, N'1001411', 111481.83514434964, 1462)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2290841d-8da5-4e14-8519-7736b701999e', 2, 1399, N'1001735', 36330.280337040327, 7978)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd4c45016-f4fa-4899-89fb-7772de9ad393', 1, 1399, N'1001485', 45484.85, 177)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c99d094f-8df5-4447-9ddd-777b09bc32d4', 2, 1399, N'1001363', 185088.44686181564, 841)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e586d452-24c6-4397-b17a-782484d71cab', 1, 1399, N'1001105', 2732211.6412272323, 362)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6d619cfe-6b7f-40d3-8931-782d57aa5ccd', 1, 1399, N'1000137', 112886.75381949914, 5396)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f39bd6bd-4cb4-4fcd-8606-782d804be787', 2, 1399, N'1000111', 53669.200511057614, 1028)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'63322b33-0921-4b18-805b-7838e4057af2', 1, 1399, N'1000563', 875000, 12)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e231b299-a74c-4fd6-9d71-785af8e2ba88', 2, 1399, N'1000602', 67154.60169989214, 2806)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b4ea534f-8434-48ad-88dc-7866fc7f31c2', 2, 1399, N'1000136', 41295.44730501857, 1870)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'44a29ab7-3b95-42ae-ac67-78681b9f7279', 2, 1399, N'1000574', 7113.0734264791536, 2256)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'35b694fd-94ac-4668-93ab-78708cd0bc3f', 1, 1399, N'1000273', 17995.07698652468, 2971)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dfce360e-1f35-4429-8fd2-788f6a639c84', 1, 1399, N'1000920', 61817.325694999992, 88)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8e3d9737-cafc-4f81-8080-78a93451ed98', 1, 1399, N'1001146', 61904.55, -6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e6048c44-7de9-4350-9aa8-78bff56cb48e', 2, 1399, N'1000451', 69753.494420917908, 2250)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7048fa14-c151-44db-a0ce-78f8fdd62dc5', 2, 1399, N'1001266', 379000, 317)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'085a0d62-89fe-4924-b3bb-79121fd1a8ae', 2, 1399, N'1001270', 58806.557224393451, 2615)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'38f525fd-c390-403e-8892-7912ceac759b', 1, 1399, N'1000187', 48752.6382423942, 894)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c4c9b817-276d-4e44-9eba-7931f652fb3c', 1, 1399, N'1001223', 506882.6149375, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c0e44457-a7cb-47b2-bf67-793535b30025', 1, 1399, N'1001379', 41859.23000000001, 823)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc102801-729c-4e01-93dc-7947b1599c79', 2, 1399, N'1001652', 218236.36363636365, 2062)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b6ab6700-c20e-4254-a30c-7949287e6707', 2, 1399, N'1001262', 30759.890132824657, 22498)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'06e4addc-adea-42ff-84cd-796ef9bacbf5', 1, 1399, N'1000773', 139114.6941101547, 2040)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'31234ec1-ef2d-458d-a7e2-7974fcc2c82e', 2, 1399, N'1001308', 89914.206677708833, 2135)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a913ca4a-93ae-4258-9819-799b0a1ca17e', 2, 1399, N'1000205', 1259285.0194552529, 4324)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'21a6a5f9-52d0-4f05-b8f8-79b343b5bac9', 1, 1399, N'1001207', 34090.03016036893, 6302)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'90074e51-a4ab-4417-a6c2-79b7caab40f6', 1, 1399, N'1000371', 126327.76916853931, 134)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'97fd8bda-881a-4076-a794-79cd13e8d0c3', 2, 1399, N'1001579', 64684.633124039421, 3929)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8fc0fe56-c09e-4eab-925a-79f97da0d4e0', 2, 1399, N'1000660', 46794.472230118474, 4409)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'723a5a4a-0f02-4215-92e7-7a12dc468859', 1, 1399, N'1000743', 126165.59000000001, 276)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd95139ec-5e90-4891-9325-7a2207d065ae', 2, 1399, N'1000055', 349000, 1983)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'41d2893b-64f8-4754-a92f-7a4df4aaafce', 1, 1399, N'1000119', 210857.8887035122, 1179)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3965edcc-d9e5-4608-a0ac-7a878578795f', 2, 1399, N'1000372', 155871.56, 182)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8fdd7c21-8056-4527-8ae9-7a98e7941163', 2, 1399, N'1000982', 340366.972, 15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e912cf5a-5e85-40c4-b177-7ae121ca3f34', 1, 1399, N'1001282', 46570.549999999996, 3608)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'288dbae1-85a8-4d88-b1c3-7af84064a0b1', 2, 1399, N'1001684', 210091.743, 637)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ad4b54f5-cabe-4889-801e-7b1f64b0e78b', 2, 1399, N'1000227', 11926.636410506757, 5153)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'592014a8-0f15-447f-a580-7b55dc97311b', 2, 1399, N'1000806', 845338.20311592775, 460)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5f4ae770-7dc7-4b74-aa2b-7badd0d31f95', 1, 1399, N'1000335', 98119.050000000017, 9)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a7a64e56-52af-4077-b533-7bea9d57f851', 2, 1399, N'1000650', 904999.98594324838, 411)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd61a2b88-f53d-42d2-98ee-7c00050a5df6', 1, 1399, N'1000697', 56320.010151644063, 3710)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ba4b50b1-3cf9-4fe4-b327-7c0a07dd3713', 1, 1399, N'1000677', 12864.351228227932, 13687)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dbde1118-1340-4527-9ac2-7c15e0a20931', 1, 1399, N'1000432', 19806.405977653634, 620)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8992f9ab-d676-49d3-b31f-7c39809fec67', 1, 1399, N'1001272', 60912.806806742527, 2146)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'42226edb-9404-4258-8ac0-7c61da9bc856', 2, 1399, N'1001514', 127522.936, 3974)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3211331d-190e-44c2-be40-7c79f8c667e1', 1, 1399, N'1000796', 56744.439999999995, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'95c80e79-18cb-49c8-a939-7c9687a1aff8', 2, 1399, N'1000245', 35092.997593523047, 928)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6c41ea6a-aff6-49ac-bdc1-7ca35ef48e07', 1, 1399, N'1000970', 464635.85630220815, 3500)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f9980788-c2b7-4a9f-8158-7ca6b418f13a', 2, 1399, N'1001616', 177247.92833167975, 2824)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f3298822-f230-4d8a-b8b3-7cb3642a82fe', 2, 1399, N'1000172', 78017.6975970962, 2358)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6d2eff87-30c9-4924-b227-7cbc5c3647b4', 2, 1399, N'1001578', 48168.801832760088, 3259)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'386bc9cb-04ec-4927-8361-7cdce3150e96', 1, 1399, N'1001436', 5963.1207222011508, 2424)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'549b08fe-ac01-49bd-af34-7ce52c8caa74', 2, 1399, N'1000865', 51344.28753360486, 2556)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e9c22d94-7c26-40cb-8d80-7d306baa1254', 2, 1399, N'1000188', 15001.597869507323, 1379)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'87307534-9fa6-4ac7-80e7-7d34d382deee', 1, 1399, N'1000985', 23118.850000000006, 66)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd9e3d864-af67-449b-ba57-7d89b49f5025', 1, 1399, N'1001401', 39632.74, 355)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'55f9e3b7-3de1-4b12-a208-7dc8538981e3', 2, 1399, N'1000084', 104410.26763215578, 3165)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e31c8851-a47b-47b3-ad4f-7ddf72274a2e', 1, 1399, N'1000086', 47924.327037789772, 4202)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'477ac05f-4a4b-4ae1-97e5-7def7e3b4c55', 1, 1399, N'1000478', 61813.801771249447, 1693)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a07ee4f9-2c1b-490e-8700-7dfe5b9b7f79', 2, 1399, N'1000987', 35779.817, 4749)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd2f8ba8a-75bb-4f44-917d-7e21c4e01a15', 1, 1399, N'1001259', 29462.265299206476, 3552)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d1637e8-4985-4b5a-9f0a-7e2744482c2b', 1, 1399, N'1001387', 485000.06, 90.79)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'92ad1151-c3a7-4a00-a224-7e432acccc20', 2, 1399, N'1000246', 92845.745046422846, 6373)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d238f3f-c3a7-496a-a5df-7e432bdb246c', 2, 1399, N'1000933', 50208.385007573692, 13783)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0a7bd296-c86e-4c24-99b4-7e56b219561b', 2, 1399, N'1001694', 39836.799657880314, 2408)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'68cc8f91-d455-4892-b027-7e621cedbd06', 2, 1399, N'1001720', 243449.19265430479, 19)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd95e0301-f658-47d8-b643-7e6335a936c3', 1, 1399, N'1001283', 55588.69798077648, 1940)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0905bbee-4e6f-41f6-b4b4-7e8b14c07ca0', 2, 1399, N'1001213', 22763.024307951204, 3385)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd2ede99e-927b-4b1d-b527-7e93a73df42f', 2, 1399, N'1000640', 251972.89976656836, 4635)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bc48b06a-d285-40ee-90ee-7f0790ad6306', 1, 1399, N'1000710', 422121.70538356347, 733)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b22726e1-be4b-4f20-a423-7f1cf056994d', 2, 1399, N'1001305', 115531.62489562387, 603)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c289319c-6581-4a1a-bc1a-7f37d71d70ad', 1, 1399, N'1000914', 258060.29532827961, 1122)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4e3ba51f-ed8e-43de-b0e8-7f3885bb62b3', 1, 1399, N'1000091', 107177.91564142486, 11675)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'802fc827-b19a-4bf3-8581-7f4bf1ca7e81', 1, 1399, N'1000190', 42187.183704081639, 565)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e96fe473-bffd-40d9-bedf-7fa6065aa01c', 2, 1399, N'1001108', 83237.258813025648, 14648)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c2710285-d4f6-463a-b5d1-7fc80d51490a', 1, 1399, N'1001359', 75032.25, 4730)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2f4d3584-1f68-41a9-8caa-7fd465b2139b', 1, 1399, N'1000118', 183609.52439099617, 1269)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a7a63ddd-5d9d-456f-8cd2-7fdfb56f4e5d', 1, 1399, N'1000889', 14161.569999999998, 234)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'916bd5a8-adc4-4a9f-9c9f-801c18cfec52', 1, 1399, N'1000724', 76723.933689751546, 884)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'621d3130-e0cf-4271-959e-80369a3e3a9a', 2, 1399, N'1001385', 73394, 1627)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cd25e596-0132-4535-9566-807be605d3c4', 1, 1399, N'1000302', 45142.177078094028, 621)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ee6cd193-ed0a-4414-a948-808875f4fdd5', 2, 1399, N'1000021', 44954.128, 322)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'23cb2b92-1755-41a1-9293-808f899c7e2d', 1, 1399, N'1000545', 116122.11568649039, 585)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'830dc9f9-b362-4e24-982d-80b7c6dcc524', 2, 1399, N'1000276', 20896.759618941738, 3809)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'60c8fac2-ce9c-4580-a7fc-80bc0946a09a', 2, 1399, N'1001668', 419000, 68)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c5e20036-ff1e-4c12-86e4-80c2ebf4a77d', 2, 1399, N'1000703', 175731.47681958965, 2393)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ef7fe5dc-2dc8-4e20-ae77-80c713bb6dc9', 2, 1399, N'1000292', 28554.130542045536, 464)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a965b8e9-7330-4844-9842-80c867acae5d', 1, 1399, N'1000812', 744077.45, 13)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c836d512-73f7-44b6-8ecb-810cc0b7ad7d', 1, 1399, N'1000839', 78423.946232172471, 253)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b1189d02-1a7f-459f-bd08-811aa27bda0d', 1, 1399, N'1000139', 163901.84851450028, 4304)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dad6ae1b-e937-427b-aa6e-812250fe05de', 2, 1399, N'1001337', 90858.9020002757, 360)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e0461d78-a357-4b8c-b559-8128c01907d6', 1, 1399, N'1000127', 158256.15, 8)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd4392d85-20e1-4170-8da3-8130aac56389', 2, 1399, N'1000569', 23854.3453155272, 2917)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3bb3da04-2205-4302-82e9-814d07b5aef6', 1, 1399, N'1001493', 59000, 219)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'33a69921-d357-4482-876d-81760997cf92', 1, 1399, N'1000982', 319097.96, 15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c1b30742-1e51-4861-b1bc-818d9a529d7f', 2, 1399, N'1000091', 130016.46179968033, 11084)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4292c698-9d36-4bcc-8118-81b4cdfaff68', 1, 1399, N'300002', 155712.18398568017, 41900)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e8a28d5d-79e5-477a-9aa2-81e825034216', 1, 1399, N'1000123', 173386.50847000946, 1237)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e9791138-bba9-4827-9143-81f314758127', 2, 1399, N'1000008', 20560.289946431945, 6967)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'77daa96c-5861-452a-85f9-81fb5669014b', 1, 1399, N'1000999', 195221.88000000003, 19)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc71168b-f029-4017-aa92-8223672188d4', 2, 1399, N'1001655', 127598.31865065837, 1203)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'16c19ebe-c32d-4dcd-a3bc-8228f03a73f4', 2, 1399, N'1001715', 319999.96418553783, 6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b73da45c-ba2b-4de5-94fb-826d73886a9c', 1, 1399, N'1001343', 34997.389999999992, 18072)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2a1a1e65-3c3d-4f4c-82fc-8273ca5e3a59', 1, 1399, N'1000200', 12357.95, 309)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'12cbdd89-3a3a-4f86-8402-82d6f69cd064', 1, 1399, N'1001275', 153957.07000000007, 89)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'02c08a5f-23d7-4063-9a49-82f0bbc73b62', 1, 1399, N'1001547', 73005.63, 600)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4f217304-df7e-4a82-8285-8324cedb231d', 1, 1399, N'1000978', 7065.2740449994426, 2344.999455)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7e971fee-d628-4816-8e84-833d62f732e2', 1, 1399, N'1001190', 50792.097889269418, 1490)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e4301604-8dee-4188-a0ad-8357abec4042', 1, 1399, N'1001023', 383808.69999999995, 36)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fa44bbb6-8918-40d4-a8ea-8375cb0df53c', 1, 1399, N'1001047', 120000, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'74bdd6d1-cbb7-4148-abe6-83875c2f28c9', 2, 1399, N'1000356', 136731.95876288659, 1649)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e438499a-e771-4844-9bc8-8391e2f84f4b', 1, 1399, N'1000431', 224250, 15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5c9bac57-93a5-439c-a204-8396674558c7', 2, 1399, N'1000550', 138570.83728844754, 1246)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dd047f9b-41d7-4e59-bf80-83d10daec169', 1, 1399, N'1000762', 259272.65000000002, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'66caa09d-4a60-4ed1-a68d-83e9efd8e186', 1, 1399, N'1000995', 21193.125883890432, 1152)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b8cde8c9-fab0-4ad8-9f3b-83fb104f0a60', 1, 1399, N'1001482', 51000, 102)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'52cf5d7b-a7a5-4444-bf80-83fc81c1c061', 2, 1399, N'1001756', 199211, 544)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1287924c-7545-4477-996d-841accdb4c43', 1, 1399, N'1001445', 199541.11, 503)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c90f03d3-4159-4a8e-bade-847a8d224dc8', 1, 1399, N'1000954', 30832.680000000004, 84)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'026e726f-4cac-4629-b6a1-8489a9eb1403', 1, 1399, N'1000444', 19542.191689071016, 6027)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bf1b2a3c-368f-42a5-a371-84936d97c1b5', 1, 1399, N'1001435', 11926.215554673774, 1606)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'79a76e50-c4aa-4e7b-ab70-849c9dc0d935', 2, 1399, N'1001286', 128750.3638617301, 987)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e71dfe6e-c042-40e9-a858-84b762824543', 1, 1399, N'1001083', 180275.66085351195, 5015)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b5a633dd-2787-4e69-a6b7-84b7a47f634d', 2, 1399, N'1000463', 14311.371729847, 5845)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a9ca4781-dc31-4c0b-a9d0-84cb197a0fb0', 2, 1399, N'1000355', 117000, 1663)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'27397cd2-e48e-4665-890e-84cb25e65d96', 2, 1399, N'1000137', 123146.34141590868, 4394)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'becf098e-dd99-4c05-b0b2-84e024dabc5b', 1, 1399, N'1001021', 44593.142813947234, 3428)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'628259ec-4a20-4666-905b-850b958f270c', 2, 1399, N'1001021', 50305.810666666664, 535)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0570f6fd-8313-4fa8-885f-851676846b17', 1, 1399, N'1000248', 26455.809883213857, 5413)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c4141932-8409-4708-a8ce-851aa2db97b3', 1, 1399, N'1000018', 42516.299510299104, 4752)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'35a3a443-fe20-49b6-8213-853eb44eceef', 2, 1399, N'1000190', 60841.052732551412, 3342)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6f66b4a1-4930-407d-9cfa-85448788d6d4', 1, 1399, N'1001297', 178618.45166528586, 373)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc5da38b-c820-477f-90a0-8546e16ef059', 2, 1399, N'1000501', 20391.052931575654, 9022)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bf567c5e-e3f2-4a7e-8683-85592fa31b9e', 1, 1399, N'1000143', 69963.05720431263, 1672)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c9130fe8-46b0-49ea-ab55-857435884540', 2, 1399, N'1000763', 7064.5599267852567, 9486)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c2936bfd-5ac5-498a-9854-85994420d898', 2, 1399, N'1001424', 1239958.6431318175, 252)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6f4b540b-14a5-4472-ac85-85b38a300ab0', 1, 1399, N'1000103', 52924.080679861763, 2280)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2704b4c1-8356-4604-8775-85cc4fc83cfe', 1, 1399, N'1001131', 24499.98, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3c507738-4a50-4414-a016-85f93d6c087d', 1, 1399, N'1000005', 13118.262630605537, 12471)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0fdc671e-e452-4ca8-a802-8607de1d1af2', 2, 1399, N'1000947', 170251.64748544828, 5798)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f1cde307-4b51-441e-aa1b-863c2b765f14', 2, 1399, N'1000215', 29358, 6718)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ae8c9fe3-dfac-4a2e-ac69-864d0c2ac2a1', 1, 1399, N'1000516', 84786.1353764734, 723)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8d987911-9b6a-4297-8b89-865bde877015', 2, 1399, N'1001738', 160000, 4534)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4f259f74-1d1c-4e06-8d5b-865d30a57053', 1, 1399, N'1000407', 25531.253697796608, 2322)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd3c315f8-afc6-4c05-a859-868601730064', 2, 1399, N'1000689', 333412.62210543762, 1491)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cf3ef879-dd48-4540-8e9b-8698ac6908d0', 1, 1399, N'1001571', 54041.24, 8)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'649da1a8-c2cd-4e56-a290-86cbe05274e5', 2, 1399, N'1001362', 145009.03417354298, 943)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'04be49d8-8c15-4af8-9df5-86e47daca281', 1, 1399, N'1000523', 73410.569999999992, 2179)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'59be69b6-123d-4569-aa5d-870c09294a9c', 1, 1399, N'1000367', 29446.07930523347, 2305)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dfbbff69-d80c-42fd-9d43-8713f830155d', 2, 1399, N'1001222', 90847.397621515891, 2140)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8737f2d4-c051-477e-a4c6-871aad6f6680', 2, 1399, N'1001083', 220000, 3951)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'46e83013-40a1-4293-8f00-872768116919', 1, 1399, N'1000800', 148775.48, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dcab499a-dbed-4b9a-93d5-873a007545ed', 1, 1399, N'1000414', 376589.15000000008, -7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'144ba87e-9b12-42d0-ae7a-874676a440a6', 2, 1399, N'1001678', 271878.08673949557, 1075)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'32e2dfbe-f803-4e0a-b3d1-874b2cb48f08', 1, 1399, N'1000555', 184017.930289604, 719)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'17d55b41-e99f-4c57-85d0-87500fe7a15a', 1, 1399, N'1001186', 49653.061246931778, 625)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6663693b-ce88-4dd6-904c-8768de4c5c32', 1, 1399, N'1000976', 28237.424335495438, 1471)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd0fd978e-defc-4a7e-b907-877f947b1c30', 1, 1399, N'1000816', 252199.10617021276, 45)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9cf5f580-67d9-4002-bc7b-87ead872c6f4', 2, 1399, N'1000138', 220000, 1091)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'83ba06e8-ad4f-4158-bce3-8800fed80d28', 2, 1399, N'1000240', 78381.872440091669, 515)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'aa8a38a5-ba4f-4ff1-96f6-8809e3059f96', 2, 1399, N'1001623', 340000, 398)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'59d549f4-520c-42fd-9628-885071381ccb', 1, 1399, N'1000344', 78970.82, -14)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f03aef53-8b10-4087-9156-885b91218798', 1, 1399, N'1001251', 104770.21061188517, 16439)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a991bf2f-8c5b-4774-98a3-88d75651d540', 2, 1399, N'1000324', 266432.18028897949, 1275)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'338e1192-2ba8-494e-9913-88dc6758305d', 1, 1399, N'1000946', 194965.73100624239, 3720)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'08074b95-4b7d-46fa-a7b1-88debc44ac52', 1, 1399, N'1001026', 199958.98656666669, 19)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c189f868-77b3-4cbd-8a09-88dfd127bb0f', 1, 1399, N'1001519', 202752.06000000006, 1265)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8018fab2-eb90-455a-9f71-88fc6c5a0bb5', 1, 1399, N'1000822', 49383.23000000001, -1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4ce0fc56-f449-48ab-a2a3-890b2fc1dc6f', 1, 1399, N'1001033', 48600, 432)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1b84132a-3576-49dd-acf4-890e013f3ee8', 1, 1399, N'1000919', 119285.17238931297, 384)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0c2ea2db-279d-4de0-9def-891d1bb814b0', 1, 1399, N'1001498', 44689.001265044753, 4843)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'85ec1874-81f1-4855-bdee-893df5cf5c5f', 1, 1399, N'1000915', 63850.579999999994, -36)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ff711c31-ab51-4d33-906e-8964592997a4', 2, 1399, N'1000006', 33675.400493514127, 10206)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3c82f0a8-e241-46c3-aac5-89728fb63de0', 1, 1399, N'1000088', 56255.847794573645, 773)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e53239c2-9a76-49f3-bf4d-8989676a7a43', 1, 1399, N'1000468', 26422.26801404385, 10206)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'661b5e4d-5e2c-41a6-a10c-899a17fa248b', 1, 1399, N'1001286', 128704.9650855316, 937)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0fcd1693-b979-411d-90e4-89c2488676bf', 1, 1399, N'1001472', 51029.647604508194, 306)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'934f1a94-26f3-40ed-84cf-89d46c5c304a', 2, 1399, N'1001333', 48206.453902681227, 2848)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ed2b96ae-2eed-4a4d-857c-89df3ab9626f', 1, 1399, N'1001050', 87577.948221924351, 2421)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7575820a-1d27-4f8b-aa8f-89e641ef2564', 1, 1399, N'1001215', 193944.45, 222)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0975e0af-88ea-40a6-bea0-89e656fe04da', 2, 1399, N'1000547', 114000.17885885364, 411)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'82a81892-629c-4377-8f00-8a273b3b4f1c', 1, 1399, N'1001399', 7063.9700000000012, 106)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a34ce37a-15bd-4855-aa3b-8a2d47f1f5f3', 1, 1399, N'1001180', 39388.009999999995, 98)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'151ca2db-0d47-4e97-a109-8a2e0b9bab7d', 2, 1399, N'1001301', 126750, 1712)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9573e046-56fb-4945-8270-8a3ce3048d24', 1, 1399, N'1000140', 175824.68379581149, 2139)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'78e48456-9472-45f8-9162-8a46695d6162', 1, 1399, N'1000324', 261216.16097489779, 1459)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'64a8bedd-4a44-4a8e-9f1e-8b065e93f41f', 1, 1399, N'1001576', 61028.250464291581, 5443)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'683f04c4-8dc9-4163-9026-8b2780f234d1', 2, 1399, N'1000722', 75979.676383599537, 1288)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'963c99ea-dee7-410a-90a3-8b2c1d2f5cc7', 2, 1399, N'1001032', 48665.22104809848, 2075)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'66061504-849c-4d1f-a45f-8b2c1f87a446', 1, 1399, N'1001268', 205976.39520463, 1189)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd108a327-e1b4-4d7b-a415-8b6375982021', 2, 1399, N'1000932', 100798.07202390929, 1024)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fb6a2ceb-1a07-4620-8784-8b653b91ac20', 2, 1399, N'1000283', 55932.242905316234, 2339)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cb05b2b0-deb6-4875-ac6d-8b67309d0d45', 2, 1399, N'1001225', 137541.03963639564, 2205)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'16706ea8-6ced-4499-b718-8b9a0e0bac98', 2, 1399, N'1001511', 86928.697090562, 4588)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e0c7643e-aeaa-41ae-af1e-8ba2ded7893f', 1, 1399, N'1000498', 26168.591301181594, 4078)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6894842c-0cbe-4936-9fe4-8bad3030b53c', 2, 1399, N'1001697', 145695.99624401063, 750)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'aaded51b-58f1-47b2-9462-8bb554bcb538', 1, 1399, N'1001461', 36000, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cbb06de8-bda9-4c9c-94a2-8bc6506392f1', 1, 1399, N'1000507', 21193.668261569004, 4878)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dec9a5b1-4f99-4fff-ab4c-8bf24d0914f1', 1, 1399, N'1000840', 48716.46, 30)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'738a3c9b-80d3-4715-aef8-8c027251c4d7', 1, 1399, N'1001470', 114440.27695351242, 558)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'081d5fdc-7a00-496e-946b-8c25082808d4', 1, 1399, N'1000289', 45894.238981329916, 1091)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'621230f4-260c-4ec9-8e3c-8c43b339d847', 1, 1399, N'1001317', 61323.604007684029, 1905)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'20731d3f-fb60-4219-92ac-8c78e74b4397', 2, 1399, N'1000029', 78174.236604394289, 2332)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2c31e942-10ff-4b26-aa66-8c9f224a48b8', 2, 1399, N'1000250', 70316.130853382841, 1823)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'570465dc-cd44-4cb4-a1de-8ca3b8dd731f', 1, 1399, N'1001685', 114322.18379204893, 2998)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1b78672e-f272-4cf9-9079-8cb91ead238d', 1, 1399, N'1001582', 38511.4369679511, 3021)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'503f0168-3238-449d-99fb-8ce419df26cc', 1, 1399, N'1000698', 313499.71790971037, 97)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6cb045e9-57ef-4a12-9d1d-8d0cd75fafd6', 2, 1399, N'1000946', 181980.72840289003, 3678)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0c9a1f7a-80a9-4a28-9908-8d11e3b9b171', 1, 1399, N'1001278', 419092.69326348032, 599)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e500f704-5707-477a-b6d4-8d296b62aa54', 1, 1399, N'1000307', 97851.8385168879, 828)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c39851e5-e705-4bb5-867a-8d3f3f4dd606', 2, 1399, N'1000624', 174341.0579898796, 887)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1cc1eb16-ab32-420b-a089-8d751e70cd20', 1, 1399, N'1000082', 39302.717068254256, 3771)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'db8cd7bb-3d50-414a-91d2-8dd16d4add6b', 1, 1399, N'1000006', 33676.825059922492, 5595)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e78d2d83-db5b-4483-801c-8df77b9fd6ef', 2, 1399, N'1000169', 64800, 2033)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e1c39827-7f69-47e1-a393-8e086fd76c72', 1, 1399, N'1001301', 126765.10538641686, 1745)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'29491e51-69ad-4647-981b-8e1c2ac501b4', 1, 1399, N'1000940', 33884.93, 15608)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8814eee2-dedb-463a-ad71-8e203f072adc', 1, 1399, N'1000221', 62243.371189263467, 2770)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ffdfc1f8-b91a-4757-a203-8e29b7fa0d64', 2, 1399, N'1000515', 25300.420985675984, 6378)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3126a26a-846d-47f0-a668-8e2c191fc035', 1, 1399, N'1000052', 111251.3849510304, 1120)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7598121c-fd50-472d-af31-8e2d6d0d9a0b', 1, 1399, N'1001543', 20787.24702330229, 6417)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a629bc56-fe42-4294-aec2-8e4bd38b8997', 2, 1399, N'1001593', 431100.917, 160)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a01df3e8-0029-4a7c-b5de-8e5019647b3a', 1, 1399, N'1000948', 210424.57417022163, 1697)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'68540dce-e30e-4484-9374-8e90580ab033', 2, 1399, N'1001682', 80743.538658907957, 1826)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9eeb124f-622c-476f-9c97-8e94867a687d', 2, 1399, N'1001034', 86974.351641825328, 2295)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8f3b810f-13b9-41e8-b6a5-8e9f536fce3c', 2, 1399, N'1001358', 74314.7513518827, 5544)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2d7becc9-9b22-4b3f-a67c-8ed178c6c831', 2, 1399, N'1000943', 299000, 1126)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'65e90e27-d9b3-4a2b-ab93-8ed6f8825411', 1, 1399, N'1000333', 29931.860000000004, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'047aabeb-224e-4b48-b97e-8efed1500fa9', 2, 1399, N'1001280', 63963.292698954647, 2178)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c819ad52-171c-4c3b-9fb9-8f12ff3b08d7', 2, 1399, N'1001198', 22850.97771377442, 7934)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'596e1f2a-8fec-4d0b-930e-8f14676bd695', 1, 1399, N'1000569', 22706.653394100878, 2202)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e610b45e-b8cd-472c-8d60-8f16e20c32e2', 1, 1399, N'1000586', 21348.03, -69)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2044f7ef-9edc-48b6-877d-8f92d09a1f6a', 2, 1399, N'1001686', 23853.016992462675, 1916)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'709996d7-e7e2-4fff-bce4-8fbbcb31ca00', 1, 1399, N'1001595', 225430.45000000004, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b29cfe1f-6923-4c22-b0d6-8fc3e28ddede', 1, 1399, N'1000299', 54368.2560017537, 1270)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ac5ce3a2-24bd-4b2a-a2d8-8feb97c302b7', 2, 1399, N'1000565', 99567.258405222863, 3162)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ffa9b724-f25a-461b-9ef0-8feef323bff6', 2, 1399, N'1000323', 263181.13140572072, 1606)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'02db5632-bc98-4aa7-a9b9-8ff270433c9e', 1, 1399, N'1001553', 386132.6765, 14)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5fb3f7f6-5f9c-47e2-ba3c-8ff624dbb58a', 2, 1399, N'1000280', 18808.42113881158, 5599)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'89de32fc-99e4-4516-921d-8ffdaa1feb12', 2, 1399, N'1000536', 77040.704311841342, 1968)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0ae1cfee-08e8-4e7c-acc0-900b11bf5b39', 1, 1399, N'1000380', 233351.79016977217, 1860)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9d252cec-d9c2-4459-9b8f-903b39448331', 1, 1399, N'1000029', 77944.901499305546, 1552)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e176b064-7a83-46f0-abb3-904b0eb79445', 2, 1399, N'1001311', 110443.10621702226, 3762)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6e0fc183-3f6b-4c44-897b-905b4b8f20ef', 1, 1399, N'1000873', 92085.350232117358, 4138)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d8fd4ab-2304-4ecc-87cb-905ce1e796a4', 1, 1399, N'1001631', 7064.01641918637, 8749)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f3bc7ce9-1764-4991-9f07-906bf4831229', 2, 1399, N'1000773', 134531.76939343463, 2012)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'90d85fac-ca9c-4198-b30f-907e925e183b', 1, 1399, N'1001512', 417331.96063214197, 418)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4a73f606-243b-4e12-a14e-9091359e881f', 2, 1399, N'1000580', 14131.739654604246, 2450.00072666)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'035bf11d-3370-4bf2-9f3a-9091eb6cdfa4', 2, 1399, N'1001664', 118021.01078932425, 2170)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4c657655-c745-4c15-a37d-90c184c36237', 2, 1399, N'1000225', 17889.247026298792, 3333)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ff725f6b-7bf0-479c-a53f-90db67c57007', 1, 1399, N'1000397', 104982.36246929131, 2190)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3073bab1-8c9b-4ff8-ac76-911f95f45ba1', 2, 1399, N'1000300', 24222.441572191205, 1550)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e79b73e7-ba1c-47a3-8478-913c15267d05', 2, 1399, N'1000135', 54821.985932557458, 1988)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'61064a42-a692-4da7-926a-9171e35d1948', 1, 1399, N'1000401', 38017.662788987036, 7119)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5a3c3850-48a5-405e-8f0b-919d69af2438', 2, 1399, N'1001347', 77889.13201871395, 1890)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5342433a-f240-4d5f-a4a7-91a067db782d', 2, 1399, N'1000942', 116330.72994815407, 958)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3f5635cf-7685-4084-b4c7-91a75498d017', 1, 1399, N'1000327', 57741.066100448181, 6390)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ed4fb0c2-d636-4186-9535-91b59e399a44', 2, 1399, N'1001271', 58815.657649826142, 2454)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c85c1915-277c-42c6-8c00-91c66dc04572', 1, 1399, N'1001149', 77611.11, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'963188f2-ed18-4a19-8ade-91d76d60c859', 1, 1399, N'1001408', 98679.05, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'18af614c-0b73-4f19-8b12-91dd05653050', 1, 1399, N'1000815', 243874.67470214912, 2184)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1b7a4dde-b680-4687-8f93-92218af90ce6', 1, 1399, N'1000546', 136830.67368713289, 718)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da8f9217-63c2-4972-bc52-925250c30c2e', 1, 1399, N'1000012', 8555.11540980485, 5148)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'246ca1eb-f74a-4c3b-aab2-9288b67ba28a', 1, 1399, N'1001225', 127793.1288077592, 2485)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ed77adff-8c91-4639-b692-929a71d86873', 2, 1399, N'1001382', 254839.13357842309, 969)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'903f6f60-6054-4773-b5be-929f0e80d8d2', 1, 1399, N'1000228', 17418.563148527362, 1982)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f4507c6d-bf11-4648-b607-92bc0c7bc0f9', 2, 1399, N'1000194', 49468.883014520477, 7873)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6035327c-b771-4e44-9ef7-92cf3967d9f5', 2, 1399, N'1000975', 14133.849258323937, 1942)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5d3a9013-de82-4b44-b436-9316ddda8572', 1, 1399, N'1000160', 26131.67856783254, 7608)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4ee10180-c52f-4e1a-9ce0-9356967860f5', 1, 1399, N'1000537', 76073.607839848861, 1990)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4716f53f-8cfe-440c-ae6f-9389e2673fc8', 1, 1399, N'1000916', 44767.270451229058, 5096)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6617073a-ad49-426b-bc65-939ed8cecce1', 2, 1399, N'1000056', 46106.422018348625, 1882)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'be8a5bb7-d62d-4722-81f4-93af6b3381c7', 1, 1399, N'1001086', 83500, -18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f56dd2f3-6832-4388-8982-941a5cf251b2', 2, 1399, N'1000297', 26039.317802295151, 2244)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da780bb3-9a43-422c-a80a-944e33cbf9a9', 2, 1399, N'1000167', 57752.888418906405, 2447)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'aecee8de-6642-4069-9dd6-946ee032146d', 1, 1399, N'1000227', 11925.351670391219, 4185)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9ec5567b-a7fd-4b81-a34b-947d9465dae3', 2, 1399, N'1000589', 42118.426054032949, 1401.00036333)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'444b8bda-4972-4824-a04e-947df444cfa9', 2, 1399, N'1001427', 1240221.8644774163, 81)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d9c8d70-18af-423d-9000-94b8fdf37b09', 2, 1399, N'1001660', 20892.75498267158, 8677)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9dcc3591-6314-42d9-b2dd-94cb6bd5e120', 1, 1399, N'1001388', 499013.58999999997, 186.885)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ee926231-03c9-41d8-a460-94f12a6a941d', 1, 1399, N'1001412', 109819.89274727716, 965)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b5005f3e-5d9b-43a2-882f-94fa5febba5a', 1, 1399, N'1000675', 4946.2677040671224, 2306)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dc7be156-59c8-4e3d-9141-94fe310224d3', 1, 1399, N'1000053', 97035.329717866683, 1104)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4e2fbf7c-4df4-4f37-ab71-95063b562caf', 2, 1399, N'1001219', 570439.38050569082, 368)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c9c46c43-417d-4fe3-900f-95072e28f34f', 2, 1399, N'1000156', 266095.46319724066, 1738)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fa28cd49-3a53-4598-86d7-95533b901819', 1, 1399, N'1000803', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'32964bf8-0d84-4b39-b825-95537a0ed7eb', 1, 1399, N'1001467', 44000, 6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0d5e1b06-ee8e-4931-820c-959636f6c9f7', 2, 1399, N'1000772', 45294.647806267429, 1242)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6aa42787-1df6-43a0-8e08-95af6bdf820e', 1, 1399, N'1001138', 57999.94, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0086d3ed-05b2-4aa3-8407-95bea525ab7c', 2, 1399, N'1001392', 52810.903471205485, 442)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'75f66954-c236-40f7-a897-95cfc15ff6cf', 2, 1399, N'1000285', 23521.45853456041, 3037)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b4764043-4a35-41f9-ad42-95df845f0988', 1, 1399, N'1000944', 307300, -10)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'59835b33-8a5f-4a4a-aa5d-95e904f7ac7e', 2, 1399, N'1000140', 221965.17404190442, 2011)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a3c9acc6-1d6a-4f53-bf05-95fae6825746', 2, 1399, N'1001019', 114110.96542857146, 15243)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'78992c02-80ba-4a94-beb6-96175f0e6a8c', 1, 1399, N'1000060', 158542.24586707083, 956)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3159ca4d-6c9f-492d-89f6-963279272b7b', 2, 1399, N'1001078', 177064.22, 2005)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5b124e9e-041f-4d1f-b580-96404b3149bb', 1, 1399, N'1000412', 58159.75, 54)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8aede459-f373-438f-85e9-9656867949cb', 1, 1399, N'1000196', 95858.88, -11)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ec5a5717-6045-48f5-b0d3-96847ee9525b', 2, 1399, N'1000408', 37357.078384085507, 2483)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b99ea9ed-78c9-46d9-a969-968941d08892', 2, 1399, N'1001450', 159673.24870653512, 986)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a084fd12-ce04-49ee-8389-96a76f6f60f0', 1, 1399, N'1000818', 51976.15, -8)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'43390557-f9a8-440d-9e1e-96e9c920cce4', 2, 1399, N'1000675', 4950.8761429503593, 7004)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'951db77b-b6cd-472e-ae88-974564022733', 1, 1399, N'1000349', 27426.523411198603, 13346)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8d99ea2d-8e61-4eee-93f6-9787efef5bd6', 2, 1399, N'1000224', 29371.065558444679, 15197)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fd016576-0076-44dc-9e8b-97ce95b90ee8', 1, 1399, N'1001449', 60918.13260489254, 1019)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5c2f5627-4dcf-4ab2-a417-980b2dd05d35', 1, 1399, N'1001305', 71556.966152849782, 413)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a7873e56-6969-498c-bf69-9841500bfd4e', 2, 1399, N'1000962', 199183.50204535737, 1778)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3c8e0e7f-8fa7-46e9-9b56-986ade55f2c1', 1, 1399, N'1001090', 34586.35, 2941)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4aeda651-cd40-4509-9196-98a66b1d946b', 1, 1399, N'1001367', 10952.380000000001, 1546)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9d49792b-5a5e-4262-a032-98b035b3ccef', 1, 1399, N'1000821', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b56d4b6f-6c2e-4688-97e0-98b799049be9', 2, 1399, N'1001608', 82598.003327787024, 243)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'972ccf57-2530-44f9-aefa-98d20ef09be4', 1, 1399, N'1001613', 39010.02382016911, 3197)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ecc13975-d3fd-46c1-b1d3-98e4121c2b3c', 2, 1399, N'1001629', 330116.95591567946, 1564)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'04f873f3-701a-4e08-b7b5-98eb1a64d35b', 2, 1399, N'1001284', 55597.871839475541, 1002)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b1674752-28e1-436e-9018-98f28c45c801', 1, 1399, N'1000529', 110301.3644913671, 1836)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'43c12f40-65dc-4145-b2d5-99202ca72bca', 1, 1399, N'1001006', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8fba5070-a6c6-4e38-92f5-992d8d90f244', 1, 1399, N'1001354', 80018.203838926172, 407)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9d667c03-d0d8-470f-92e2-9937ce31c3d7', 1, 1399, N'1001137', 26499.97, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'81f79338-6324-4106-9c12-994c7c6daf27', 1, 1399, N'1000888', 11252.35, 211)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9627793a-3ca9-4f65-86d2-995859e3c1ab', 2, 1399, N'1000350', 144282.09980567329, 6782)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da6526c6-1dde-4d42-915b-9991791fdb86', 1, 1399, N'1000524', 43378.67, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4b3fcef2-c234-49eb-b478-99b75faec83e', 1, 1399, N'1001489', 41231.669999999984, 197)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5857ca1d-cd65-407a-b10f-99e1ecd9130f', 2, 1399, N'1001423', 121132.6369312114, 2492)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'984fbbcd-3090-49df-869b-99f1aea82a62', 2, 1399, N'1001211', 22751.859946900106, 3433)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6a1acb02-7986-452c-8dc0-99fa536c371c', 2, 1399, N'1001107', 86430.893815319185, 21307)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5c5c6ed0-610d-4d75-a749-9a27304f2be0', 1, 1399, N'1001619', 136701.73999999996, 2269)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'21139c90-4652-4fdc-865b-9a2a72901cf7', 1, 1399, N'1001668', 390000, 2498)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd55262ea-67ff-431d-8d29-9a47aed13fc2', 1, 1399, N'1000124', 100995.13000000003, 206)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bc14c313-8425-4778-bcbe-9ab9173ea860', 1, 1399, N'1000602', 67152.7259030063, 2793)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6a75191f-d742-4984-8150-9add387f3760', 2, 1399, N'1000009', 33675.446622092226, 12243)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a0b355ff-3078-4381-97fe-9b0a30c88999', 1, 1399, N'1000504', 50408.077957343507, 2057)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7e4768cb-7224-4c13-bac6-9b200184eb36', 1, 1399, N'1000535', 76387.577417978639, 2153)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0e3d1a6d-e967-4334-8724-9b3126ad22d2', 2, 1399, N'1000361', 114885.27320481843, 3469)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c356fa23-b042-446a-8f4d-9b4cc28a7cff', 1, 1399, N'1000294', 45588.219999999994, -65)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd5226eac-419c-4422-8943-9b507e0777f1', 2, 1399, N'1001573', 190053.67793240555, 7652)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ac0ee9ca-8155-468a-afee-9b55de418205', 1, 1399, N'1001669', 22935.779816513754, 1296)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd60b1ec5-ea69-4b45-9667-9b7fe866a87c', 1, 1399, N'1000427', 115623.61154853272, 308)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e32a257a-e43a-490e-9c60-9b8c9a2bb6a8', 1, 1399, N'1000850', 686717.3141007059, 424)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6fefe836-4aed-4a3e-9bb4-9b8cc871bd77', 2, 1399, N'1000441', 66745.023155835661, 3091)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7030bac7-3f7c-43d5-9746-9bae0e31db67', 2, 1399, N'1001753', 59036.894600004707, 1664)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'aa237270-11b6-40c3-afbf-9bb0a238bbd6', 1, 1399, N'1000224', 19249.209624536168, 18792)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5e9fc9d6-5c95-4b53-8325-9bbc6c8ab983', 2, 1399, N'1001663', 106200, 2359)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'451e27d9-3c3f-40d0-8659-9bbc76dc090c', 1, 1399, N'1001357', 106764.08847488741, 3515)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6456be42-08ad-4176-ab78-9bcbb9e8a99b', 2, 1399, N'1001220', 223677.99126835814, 659)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'39563645-bf2d-4271-886c-9bea1c9421e5', 1, 1399, N'1001378', 56383.382597106211, 2391)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'64913c2c-f14c-4566-af81-9bf2546c314e', 2, 1399, N'1000112', 53669.201044226429, 949)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a88bb380-e8e0-4364-b187-9c065977a8cb', 2, 1399, N'1001331', 40185.992437258945, 4123)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'78b15886-72fd-47f7-a084-9c1376703d83', 2, 1399, N'1000103', 54766.177484142987, 2404)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd7fa8401-6b24-4b6f-9f98-9c3fb11dce9d', 1, 1399, N'1001250', 119000, 10)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ebcc7c11-4f38-4ff0-9d91-9c8a5cc9f2ba', 1, 1399, N'1000541', 142486.00955671683, 849)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5f218e53-939a-4992-965c-9c942ae30ecd', 2, 1399, N'1001714', 70279.846153846156, 5596)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f342df4a-c5d5-46c0-9e2e-9cb9c5c86252', 2, 1399, N'1000288', 22019.290512113326, 472)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'081e6869-e665-4095-999d-9cbdb2095176', 2, 1399, N'1001248', 330815.46926602168, 1261)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'26b5696d-6280-4171-8d18-9cca17f7d235', 2, 1399, N'1000621', 30974.520119559886, 10653)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fcb0139f-61db-4b21-9468-9ce570fc0d0b', 1, 1399, N'1001383', 108495, 3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'51823b71-a728-42a4-9d39-9d1a3e982164', 2, 1399, N'1000405', 39449.541, 1043)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'471bcac9-326e-4561-a2c7-9d2b67b3c363', 2, 1399, N'1001740', 10596.014951332061, 438)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dc2700e0-d9d7-41e6-ab3a-9d31489a4e93', 2, 1399, N'1000988', 98256.78575074648, 712)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b8c4f173-896f-4421-99c8-9d3b3448ed87', 2, 1399, N'1000117', 129934.64054976424, 1642)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'734bbb60-56ed-4d56-a0fa-9d4f4e27eadf', 1, 1399, N'1001020', 110964.10068284519, 3460)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5ccb4509-36f1-496e-bc34-9d566a0da7c0', 1, 1399, N'1000197', 67770.690000000017, 8)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd05818ff-0f4d-4f1c-9e7c-9d56c5f6b0f2', 2, 1399, N'1000101', 55232.714499876936, 2449)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c14a1802-d4d3-43d0-8ac6-9d5975e30999', 1, 1399, N'1000014', 28168.21, 32)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b8ac7b24-b70a-4d69-ada9-9d76a7ee6231', 1, 1399, N'1000844', 145463.97000000003, 3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'511e977d-3d07-42fc-99fe-9d7c0dc37c02', 1, 1399, N'1001635', 125053.14743235782, 4837)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'24626b3a-39bf-42e1-a2c5-9dc7593ff14a', 2, 1399, N'1001344', 33202.408244393671, 4959)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2a13352f-a8b4-46f2-84ac-9e0f27ea971c', 1, 1399, N'1001347', 67841.594584556035, 1891)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'105d9439-0b88-486b-ae26-9e1e3fef8d3f', 1, 1399, N'1000583', 14133.536392364053, 1848)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'38602017-c69f-4084-b652-9e3a01d6965c', 1, 1399, N'1001057', 232150.79, 15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'439ed0cd-2efa-4b31-b923-9e3bb1fd269b', 2, 1399, N'1000184', 15000, 306)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'01e4a19b-c496-44e5-a4b0-9e43833be2bf', 2, 1399, N'1001221', 84788.644048433227, 1606)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5d7dee06-b470-4805-9f53-9e54f5de958f', 1, 1399, N'1001070', 13394.839999999998, 7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd0180b8a-bea9-40c5-9567-9ece8b787ade', 2, 1399, N'1000007', 13116.832173686171, 13139)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c87a67fc-1049-4145-b07b-9f1f88d31cb4', 1, 1399, N'1001323', 20550.485796304638, 9430)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8dbedc4a-dfea-4189-a69a-9f2b88a6394f', 2, 1399, N'1000590', 70851.830299443885, 902)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a4f4836a-2444-42f8-b6a8-9f39b9d19dbe', 1, 1399, N'1001517', 347029.08000000007, 550)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b478face-8fd5-4336-8e10-9f62aca1e334', 1, 1399, N'1000606', 315390.77051334566, 1389)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6362554e-646e-45bb-b7bb-9f708c32b80c', 1, 1399, N'1001373', 3352.3569956606043, 5061)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dc769aaf-d62a-4adf-8793-9f97b773f04a', 2, 1399, N'1000186', 30003.286470695635, 563)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'734c276b-7541-4553-9fec-9f999aea76cc', 1, 1399, N'1000322', 261265.34398223442, 3598)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ee60d55a-c750-4df3-ae09-9fad6d0e0047', 2, 1399, N'1000163', 45144.214515835134, 1640)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cf4860a3-eeb6-491f-adca-9faf6c10b4cc', 2, 1399, N'1000332', 123853.211, 4128)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'724e1347-1862-4e1a-b75a-9ffbd0e87b97', 2, 1399, N'1000442', 36303.82336605413, 2486)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5524e64e-6675-420d-a0d5-9ffddff25b93', 2, 1399, N'1001681', 45525.529956409278, 2657)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ee7b2bd9-9bbb-4800-90b0-a02fd2370679', 1, 1399, N'1001129', 54999.94, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8a592cbe-d1a0-470c-8e87-a0576aea0162', 2, 1399, N'1000274', 19505.047429274353, 3649)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f704a8d4-8d19-48bd-b95b-a08435e7f7c1', 1, 1399, N'1001346', 27024.108827880213, 5374)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b1c641cc-1a0b-43db-9f1c-a085fe2684a6', 1, 1399, N'1001127', 193500, -18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7c9da6f6-f6d0-458f-a1da-a089746964de', 1, 1399, N'1000506', 7065.1353209022191, 23293)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'66602f4b-01d5-4d52-ab7e-a0b5efc62aa8', 2, 1399, N'1001752', 53670.063728492059, 3120)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0058a47d-240e-481e-a6dd-a109288a099e', 2, 1399, N'1000476', 22800.970266491189, 4266)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'199b402d-867e-4e7f-8759-a115741f813b', 1, 1399, N'1000988', 115620.08695989761, 859)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d9117df-8ea0-43c2-a264-a146420914e7', 1, 1399, N'1000115', 474482.7572175879, 6563)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'27a8df17-0e8b-47e2-bbea-a194b39bd743', 1, 1399, N'1000908', 86654.309999999983, 55)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5c597afa-64e7-4599-8f43-a19ee093dbfb', 1, 1399, N'1000245', 35093.876933859588, 1165)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'65b8f7c4-ac85-4c90-a84e-a1c7d896f6c9', 1, 1399, N'1001427', 1166860.9411448552, 64)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8917b948-c544-406b-b3f4-a1dcecf74507', 1, 1399, N'1001369', 29172.435390820974, 532)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'652fa33e-2ee7-46ff-a4ec-a28b7a2f1f42', 2, 1399, N'1000583', 14139.131254915204, 1777)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0475f5dd-8701-4010-9975-a29c51437238', 1, 1399, N'1000409', 48601.149999999994, 2775)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c6b5f619-05ae-4b7e-9c20-a2a83cee3fcb', 1, 1399, N'1001655', 127539.66934250762, 646)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'617eaf2b-a879-46a5-b564-a2ae88ba28ef', 1, 1399, N'1001206', 33747.383898575958, 2687)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'df376b4b-a2af-4064-a1a6-a2d1471f8ad7', 2, 1399, N'1000546', 136734.07704260625, 539)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'749659f8-91c3-48d9-97e6-a2dede8ed6aa', 2, 1399, N'1000221', 99285.368464918662, 3012)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'34ac707e-2dc9-48d8-b2f1-a363f228e767', 1, 1399, N'1001166', 38889.96, -1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0c27e57b-0f83-402c-a8c6-a3669bc6f7ca', 1, 1399, N'1001078', 146839.64027862117, 3554)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'788d2813-a704-451e-9692-a3854301479c', 2, 1399, N'1000312', 75398.172812249744, 747)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1b4273a8-e897-448a-ad2e-a3e780e0575f', 1, 1399, N'1000838', 52614.626228979367, 3210)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bc13fb89-4d42-480d-b64e-a405d506a25c', 1, 1399, N'1000874', 44706.558855659467, 6539)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b6a01822-f538-48a3-8adf-a410ad2def9f', 1, 1399, N'1001386', 76639.042986101354, 1964)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5b8354c8-76c6-4a7a-a822-a4276f9ac929', 1, 1399, N'1001424', 1190779.4739927002, 228)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b0059912-c776-48a5-ac2a-a441b6bd59f4', 2, 1399, N'1000858', 56657.660039427145, 2599)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'13169852-8ee5-411d-b14f-a447498a2c3c', 2, 1399, N'1000185', 26250.344014153725, 174)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'50ce1fb2-0b9a-4910-886d-a44c645b3cd3', 2, 1399, N'1001618', 26000, 4393)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d869030-d403-4b09-9531-a49e81c85b1a', 1, 1399, N'1000476', 22907.14071180778, 3510)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a370a171-cd0e-4bc8-ab96-a4c98197f3cc', 1, 1399, N'1000027', 78481.222196442817, 991)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ef7fd84b-32c8-434c-9853-a4d832a49a3b', 2, 1399, N'1000872', 293736.66495203675, 2819)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c93989e8-69a6-4efb-8931-a4dd50d366a9', 2, 1399, N'1001499', 71100.917, 3470)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0129165d-514d-40c7-95c4-a4df025d235c', 1, 1399, N'1000937', 50906.310000000005, 252)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'45086fed-e584-4171-86d5-a5133234b8e8', 2, 1399, N'1001422', 44938.703828540478, 1928)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c540ca0f-b4fb-443c-949d-a5579fd56b5c', 2, 1399, N'1000052', 140109.45272131651, 960)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'64608810-307f-4ba3-bcf5-a561793b84b9', 2, 1399, N'1000622', 73394.495, 2340)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'04661211-4fca-4fdd-a710-a5c7c87285c0', 1, 1399, N'1001381', 72329.93, 23)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0b301cf6-1772-4414-aa12-a5c9f42c9508', 1, 1399, N'1001063', 27438.428000103024, 3293)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'efd23e55-440f-452b-a98d-a5dbe56fe180', 2, 1399, N'1001209', 34181.977368717366, 4595)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'93a8eb06-4c56-40ce-b234-a5e31ed6f242', 1, 1399, N'1001660', 16613.750863748966, 1666)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3d66c2a1-7a34-4497-89b9-a605b87f41bf', 1, 1399, N'1000182', 67464.837705174286, 1542)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c254be98-2c90-406e-b786-a61ae63e5f81', 1, 1399, N'1000020', 42603.012845169767, 4518)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'702899d8-9859-4945-ac35-a6244e507c59', 2, 1399, N'1000046', 57754.33892134724, 2782)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ea61a0b9-ac3e-4fcc-9183-a62f2a35b03a', 1, 1399, N'1000413', 134547.97, 7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b6ae2a51-d35c-45e1-95fb-a632facdc1da', 2, 1399, N'1001476', 137615.26485417137, 657)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c8be6df0-0238-43ec-b788-a6379c32215e', 1, 1399, N'1001271', 50138.299300946688, 2391)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8a9f7d2c-8086-4959-b1af-a63bab4ce0e7', 1, 1399, N'1000312', 67783.177958622284, 1030)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ba368fd2-e65c-4f64-a958-a6424b82ac33', 1, 1399, N'1000701', 104605.70536353652, 4416)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8184bab6-ccbe-4a2d-869d-a646085f8d6c', 1, 1399, N'1001515', 208217.11978409829, 1533)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ddee59fb-e927-4559-bd66-a68f173a7407', 1, 1399, N'1000533', 54115.57751391545, 1948)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e4760d25-f37e-43b0-9e02-a69dec67c93b', 1, 1399, N'1000278', 123721.12999999999, 10)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ad2daedc-7194-4665-93be-a6adf2edc03c', 1, 1399, N'1001085', 239616.76139410186, 321)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'779ca3e2-41f2-4051-a6da-a6bb9413e7e7', 1, 1399, N'1000720', 36558.142889123126, 1340)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'28cc437c-c3ab-47e8-b6c7-a6ce5eef77cf', 1, 1399, N'1001363', 185012.2237352716, 859)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b5fc95f4-5fe4-4408-a21c-a6d8bf59b238', 1, 1399, N'1001356', 180913.16506008268, 1278)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd583b99e-ceaf-4a5c-a72b-a6f34ff8ba67', 2, 1399, N'1000968', 25928.948959574667, 3718)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4de86b84-4e47-471c-8043-a706f81c23c9', 1, 1399, N'1001419', 36941.7161881385, 7071)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'22290364-d488-4645-95ea-a72212c51d74', 1, 1399, N'1000996', 21202.768242600847, 862)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'71527833-5ab3-434c-a12c-a73281557dad', 2, 1399, N'1001087', 243010.52631578947, 1796)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bc4a87c3-1eec-40ab-a325-a7620d79de5e', 1, 1399, N'1001315', 125405.29278641706, 3330.728)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'505d9e48-5ad9-4ebc-84e9-a779fb9ea8ac', 2, 1399, N'1000860', 81651.376, 1882)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7b8319ab-0ff7-44c8-b069-a7961fcb7e78', 1, 1399, N'1000526', 50977.211889400925, 3731)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'327f8fd4-b878-4005-bc25-a7a7434880bf', 2, 1399, N'1000168', 79212, 2171)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9bdd6ad1-0ddb-4fdd-98ee-a7b173e1cfb6', 2, 1399, N'1000483', 72619.187382885691, 6569)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3899bb06-184a-45b7-8fe1-a7b8b84a3da9', 2, 1399, N'1001106', 3908000.110981524, 44)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6b2be49c-baa4-4149-a67a-a7d007fdaa09', 1, 1399, N'1000282', 60861.591463478027, 2385)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f372ff46-966d-44f0-b00c-a7dadbd9fcd4', 1, 1399, N'1000975', 14130.277836693091, 2060)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'95d5f671-a59f-4bf7-a746-a7f94de98051', 1, 1399, N'1000033', 40545.622189574577, 2328)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f331f94d-609b-4dec-9035-a7fb68c7fc88', 2, 1399, N'1000708', 522477.064, 928)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c2487cae-95e2-4eac-9512-a803c0d02bc0', 1, 1399, N'1000270', 22270.292341523749, 883)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cc26cb7b-d08a-4acb-af9b-a807118802de', 2, 1399, N'1000542', 123235.02189119261, 530)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'91eabeda-03f9-4b2d-831c-a81e69f18c32', 1, 1399, N'1000283', 57354.106570122691, 2138)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c4615ff7-a9ef-4c9a-b49e-a8207c3a4bf2', 2, 1399, N'1000972', 14213.347978669863, 1542)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'12a1ced1-125f-43fc-b742-a82e6fbbdc4d', 1, 1399, N'1000355', 117836.55370129868, 1768)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0fe4561b-591a-4bd5-99ba-a840d7d54171', 1, 1399, N'1000791', 48905.384598096069, 2765)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ed5697e9-bd96-4464-95f8-a845bfcacb9a', 2, 1399, N'1001368', 13761.468, 603)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f58b471d-4c58-4bc7-b934-a878fac6a0b8', 2, 1399, N'1000260', 86913.342410515717, 1717)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cd1753f8-5117-49bb-93fb-a87dff0303e4', 2, 1399, N'1000862', 50751.9507318717, 1590)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd5aafc97-6948-4f28-ac90-a8881984f744', 2, 1399, N'1000743', 155045.872, 228)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6844ca88-f1d2-4470-ac63-a8dd2810f889', 1, 1399, N'1000417', 54835.77, 59)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2ece4528-cb41-4c60-af22-a8e0f0fda69f', 2, 1399, N'1001360', 98359.282406296144, 913)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'77a89984-1191-4b3a-b0da-a91618815bb0', 1, 1399, N'1000011', 14501.75, 5014)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'93356bab-ac58-4a73-9dbb-a94f7a26bb42', 1, 1399, N'1000927', 84583.49000000002, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'da33be39-649f-41c1-93b0-a95c09eae37b', 2, 1399, N'1000924', 224852.61775493916, 1100)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'160f6960-7668-4943-bf5e-a96267182b88', 1, 1399, N'1001450', 159927.90481263871, 1168)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'17e2ecdd-81a4-48b1-84e3-a979354d4c46', 1, 1399, N'1000621', 29507.67, 10989)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c44da66e-d2c1-4009-a07d-a99ad28a25be', 2, 1399, N'1001417', 141275.34069018404, 1568)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'89287227-44ac-4d56-a0f8-a9a9fbde1377', 1, 1399, N'1000666', 35229.12, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'00a66443-a40b-4965-99f7-a9e3e4f867fc', 1, 1399, N'1001630', 153877.37281857454, 2617)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'19aa102a-741f-438c-8d29-aa22027d19b1', 1, 1399, N'1000116', 302965.62592857139, 3938)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d6654cf-cdf0-4092-9a8c-aa87f7972d24', 2, 1399, N'1000160', 29852.869372612658, 9961)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'07e3aa85-c277-4715-8bc5-aa8fd3587b04', 2, 1399, N'1000341', 63236.736777899139, 14457)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b6d506ca-8508-43cb-918c-aaa2484430ac', 1, 1399, N'1000601', 21761.7241033701, 3435)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'90c237fa-9020-456d-809b-aacf56692fea', 1, 1399, N'1001656', 127539.66934250762, 670)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6de5f1a2-a0b4-4552-8bbe-aada4b2a5d6d', 2, 1399, N'1001539', 123853.211, 523)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'31a065b5-abc8-45bc-b3d5-aaddbf06d577', 1, 1399, N'1000886', 280899.80251687526, 1693)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f8fdfb8b-d0fd-4d6e-ae60-aaf831286e89', 1, 1399, N'1000155', 67387.188423246131, 1563)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c04db55a-37c8-4a35-b480-aafea5723b88', 1, 1399, N'1000295', 44701.3757441279, 91)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2f430ba0-f927-471e-822c-ab0c51f88c0d', 1, 1399, N'1000642', 560055.9782722512, 243)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ce212e77-2123-4be1-bbde-ab11f3c62aae', 2, 1399, N'1001649', 117431.193, 221)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd427a39d-0b97-4e15-aecd-ab19893cb141', 2, 1399, N'1001287', 60203.927497535464, 691)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4609b23b-5c46-479d-ac32-ab1ab4f21193', 1, 1399, N'1000339', 205673.57999999996, 58)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c6d3682a-eb14-451d-95ba-ab216316002a', 1, 1399, N'1000484', 115558.17453045376, 1001)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e9208766-6aea-47a7-9e2a-ab268f8ca411', 2, 1399, N'1000543', 129695.9632710116, 417)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0941990d-6e8d-4ef5-9af4-ab8d888bcc16', 1, 1399, N'1000008', 20560.533218950164, 5297)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d8ecaa3-738c-4628-85e4-ab8f67228057', 1, 1399, N'1000424', 193703.14999999997, 208)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'535a6460-dce1-4cb9-8a80-abb701d1d4e4', 2, 1399, N'1000900', 33028.294959510262, 2288)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4bfc37e3-bef2-4303-aff5-ac1940665f13', 2, 1399, N'1001239', 108770.66951753834, 1253)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'99e0f88d-6397-43a5-adfe-ac29e4978ef9', 2, 1399, N'1000552', 88601.3427035845, 1184)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3eec7e66-539a-42ba-9ab8-ac3518ba4b8c', 1, 1399, N'1001324', 59266.060000000005, 17)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ab6d6b12-ab38-445d-abb0-ac5a9300c4dd', 1, 1399, N'1001246', 92926.59867021277, 27)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bda5ada0-1f1e-4036-914c-ac5af65a1c9a', 2, 1399, N'1001543', 24409.469764223268, 5055)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'26127d8a-09bc-4db0-94dc-ac862f140d14', 2, 1399, N'1000704', 175724.82040538266, 2989)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'88ac3eab-d1a9-4d8b-b46a-ace598cdb60b', 1, 1399, N'1000210', 529440.947601476, 1037)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'41fbc481-6de6-4752-9029-ad052dfe0fee', 1, 1399, N'1000122', 124517.17705606147, 1559)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7778cfbb-bbf6-4509-9f02-ad0d95f73e2d', 1, 1399, N'1001134', 39999.96, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a71ad4f9-fba0-40fb-a295-ad4e3bc0c749', 1, 1399, N'1001307', 49738.320109652966, 2289)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd6b0a005-f9ce-4d86-be9c-ad511448337c', 2, 1399, N'1000534', 61000, 1460)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'15540f38-e71a-4dcf-9b3b-ad6ad5b48bc5', 2, 1399, N'1001281', 75388.151699102324, 3281)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2bc3d615-aaea-4a72-a370-ad6f7404e97f', 2, 1399, N'1001656', 127577.8201104911, 1137)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b5462a76-d2a0-4a31-bf2c-adaf3e7896f2', 2, 1399, N'1000024', 13949.87786294633, 8127)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'815c3786-aece-4220-9ac4-adcd2f1fd7c8', 2, 1399, N'1001646', 126616.31138253918, 11867)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'abcfe016-f20c-4f5a-a518-add18747845f', 1, 1399, N'1000309', 106825.65999999999, -10)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9fe396f8-1757-43d1-8830-ade26cf160d6', 1, 1399, N'1001641', 116621.60361355312, 6691)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'880a95fc-a080-4619-a22b-ae0e2020de2f', 1, 1399, N'1000809', 446988.65, 115)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2dd2288e-3ee8-4d08-9ccd-ae179b5f2094', 1, 1399, N'1000863', 53531.821180635518, 1630)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a43f5bf3-6633-4f7b-9951-ae193010ffff', 1, 1399, N'1001480', 122290.35999999999, 92)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2319fe09-1c5d-4fb6-a157-ae2bd7d1370a', 1, 1399, N'1001375', 53337.963602776537, 5601)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4c9ff453-1414-4328-8283-ae3240544c11', 1, 1399, N'1001056', 153218.58468163176, 1701)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2ea03f42-3297-487a-8935-ae5865b6b611', 1, 1399, N'1000967', 11401.809258452453, 5054)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'95e3d3c1-bd22-42dc-9dcd-ae768023ef33', 2, 1399, N'1000949', 219843.91034607848, 1716)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9f89cce0-3a89-4d10-b39e-ae7c172afdf4', 1, 1399, N'1000987', 29724.925290136849, 8156)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7ca67d36-f366-4df4-aa90-aea2ec353ddb', 2, 1399, N'1000815', 234814.99300059603, 2129)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7dd5cb5f-5932-426a-88d5-aeb09b32c21e', 2, 1399, N'1000038', 61489.024085890778, 1515)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fffabdf8-fd41-4924-b215-aed26c54a83e', 2, 1399, N'1001709', 47709.833403734832, 1720)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8b80adcf-5087-4b04-b111-aee8c084346d', 2, 1399, N'1000028', 95320.947777494788, 2519)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a6829096-1e74-4f1b-91d5-aef1618af345', 1, 1399, N'1001274', 36744.731631245537, 23684)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8d1d1444-efb5-442b-a15f-af0d4b6b07e3', 1, 1399, N'1001240', 90475.92663910221, 415)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eba716e6-df1e-4104-84fd-af2fbfc6344d', 1, 1399, N'1001024', 850000, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9d439a3e-4b27-4f96-bb2d-af5050f1c37e', 1, 1399, N'1000871', 84596.499117057785, 4028)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4a8ad248-d009-4e4b-af2e-af90df129489', 2, 1399, N'1001099', 353244.15094339621, 1842)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'63854293-f12a-4b29-b31d-afb77ef12b4c', 2, 1399, N'1001381', 90413.000066160865, 1687)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd0b48dde-77c2-491c-8cd8-afff2557fcc6', 1, 1399, N'1001497', 211053.86534927943, 293)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b4ec6a14-de9c-405e-a3ef-b0002e840099', 2, 1399, N'1000107', 86567.90235023071, 2043)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8263c55e-75c2-4026-8ddb-b017a8c11ba4', 2, 1399, N'1001542', 24409.335186378543, 5711)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8cbbc634-7288-4433-a1b3-b030e52fe268', 2, 1399, N'1001617', 215000, 5308)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6bd12d81-02e1-4546-9673-b0579843e620', 1, 1399, N'1000334', 66891, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'62011373-96fc-47dd-9271-b066646383ff', 2, 1399, N'1000507', 27394.701788895105, 5160)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e1c9c8ec-d2a1-4ece-811e-b0bbe7a8c254', 1, 1399, N'1001534', 519072.44805821171, 4109.118)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e2855479-1781-41eb-b6f3-b0e92cfd85a0', 1, 1399, N'1001400', 7064.0100735863589, 3879)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f330e6c9-8059-4f5c-9955-b0fedc5963b7', 1, 1399, N'1000891', 69459.65, -7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'88f8b52f-3fc3-46f4-bfe0-b1184949abde', 2, 1399, N'1001685', 136697.248, 1781)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2affa0a2-2526-45d6-86e6-b12292cc65a6', 2, 1399, N'1000058', 107526.47512296736, 5587)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'382d3298-0da8-4784-ae9d-b1587a2c6ac1', 1, 1399, N'1001413', 82224.87076690096, 1334)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1b0e5ab2-feef-4e06-bb6a-b1b49c489c95', 2, 1399, N'1000199', 41000, 40)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eb2e21b2-01dc-4c16-9fdd-b245c158484d', 2, 1399, N'1001627', 38840.400007422068, 11644)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd7fe5ae5-0291-4a19-80f0-b252b3ec8a44', 2, 1399, N'1000424', 164220.183, 192)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2e1a9add-f619-4fd9-9f60-b2d0379edcd3', 2, 1399, N'1000880', 163261.81392171152, 2306)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2f3dca13-9f35-4ab6-9b58-b2f4acfccd1d', 1, 1399, N'1001337', 90917.779134034412, 689)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f3b444bc-474f-40b9-b39b-b3519ded9754', 1, 1399, N'1000443', 96822.77807547171, 876)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'043e1cc1-2289-4e3c-93af-b35e039e8939', 1, 1399, N'1000687', 75403.5, 20)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2cddac61-16c1-497a-88db-b376bf3b478c', 2, 1399, N'1000672', 38437.441460177783, 15584)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'808e45c0-cc1d-42af-a89c-b3a2703f9141', 1, 1399, N'1000538', 59692.522430837576, 1807)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'855e91dd-bb15-4c3c-8143-b3d02a58e136', 2, 1399, N'1001563', 45556.815065628914, 939)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5e64cf87-726c-46a2-9d26-b410e37f2e8f', 1, 1399, N'1000942', 98394.399948682112, 489)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5f80f167-47a5-4d88-b7e1-b42f624f8a9d', 2, 1399, N'1000747', 44954.128, -3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f9a5c3b1-2b3d-4e90-801e-b44b9a11f402', 1, 1399, N'1001036', 65774.921027881544, 2392)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'069b6e7e-7d96-4a34-98fa-b45c085deda1', 2, 1399, N'1000560', 40240.23947656629, 3844)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'db05264c-0f36-4f97-91b4-b46d37477632', 1, 1399, N'1001302', 85877.447815999985, 2697)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd595b73e-af5b-4884-87f5-b4827578f21c', 2, 1399, N'1000452', 70508.909090909088, 8470)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8b1d2433-be2e-483c-ad33-b48417ba9b64', 2, 1399, N'1001446', 311880.734, 232)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8b551b82-472e-45d5-aeb1-b4981a6f3877', 1, 1399, N'1000396', 87669.39, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'49978645-2843-454a-989a-b4b550ba98ef', 2, 1399, N'1000850', 753277.30513880681, 444)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b8ba0f2b-c3f4-4b1e-a482-b4c85286db1b', 1, 1399, N'1000292', 28560.358193806864, -62)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e1f461ed-dc52-4bf7-ab77-b4caf3a72001', 1, 1399, N'1001414', 79134.4771989891, 1471)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'34980857-a940-4f54-aba9-b4e198dbe7b0', 2, 1399, N'1000290', 41665.539332388646, 999)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'afe25259-fdea-408b-a0ae-b4ebb002b753', 1, 1399, N'1000497', 106221.73235724749, 936)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'995d7025-894a-4f03-8725-b4f904571839', 2, 1399, N'1000938', 49456.796109631556, 2032)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5b457054-0186-42c1-bae1-b52cbe15fd79', 1, 1399, N'1001238', 96898.836125500879, 1205)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bed17eaa-bb5a-4599-af0b-b53f3a1269ab', 1, 1399, N'1001326', 33488.61589722371, 4265)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5d1728bc-bf63-4488-83b4-b54fa242b73e', 1, 1399, N'1001334', 17873.29905906101, 2624)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'06417319-b24b-4726-a5ac-b58b87991e3a', 2, 1399, N'1001722', 57876.781599579968, 90)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'46f9847f-1cf0-4e4d-922a-b59bbdfbbd28', 1, 1399, N'1000964', 120915.3873308139, 4830)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'10b11c16-3bc5-447e-96ac-b5a90b99383c', 2, 1399, N'1000585', 14133.636555659041, 1201)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'87dc622c-e623-42f0-bf9d-b5c344b887a9', 1, 1399, N'1000258', 72864.151174941391, 2546)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ed8fd796-bbd6-4f08-86ad-b5f041c19492', 2, 1399, N'1001572', 19949.735821541828, 7821)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'36efe7e4-a30c-4288-9c28-b603638a7a1c', 2, 1399, N'1000410', 57798.165, 2078)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'48a7389d-89c4-4daf-9f53-b60e17e3bda2', 1, 1399, N'1000643', 1080662.8900000004, 210)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4b7b737d-024b-4fe3-a806-b6115f7c96df', 1, 1399, N'1001649', 108273.29900189459, 2189)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'62e54f39-04d6-442b-a344-b62e29152102', 1, 1399, N'1000416', 54830.450000000012, 221)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4170cdf2-8dcc-49cb-a52a-b65627931fb0', 1, 1399, N'1000776', 177408.93, 8)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fdc37183-abc4-494d-9b33-b66c2ebc3701', 1, 1399, N'1001247', 94609.84, -1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8bc3eab9-e30a-4c19-a00c-b686f0327786', 1, 1399, N'1001569', 100379.90695930275, 1191)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'385464d9-008c-4a7c-8e0b-b68b260dc1e3', 1, 1399, N'1001293', 60665.570025906738, 477)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'13cfc0e3-d2e0-4cab-9ca0-b68f33e29b80', 1, 1399, N'1001638', 22069.440000000002, 4357)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b883c776-317d-41fd-9a92-b691cb89dbe9', 2, 1399, N'1001048', 109601.68108909798, 2578)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9dad2a35-2653-4d4e-b885-b693d97bec8a', 2, 1399, N'1001705', 38500.194924766962, 2260)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5c36f9fd-d796-4b0c-adc9-b6bf11a54b74', 1, 1399, N'1000977', 21193.946181963496, 538)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0171d720-7b49-424f-b95b-b6d9f1c7d72d', 2, 1399, N'1000102', 113467.66162919517, 2704)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3fb10b02-9aa2-4354-9d97-b6deb7f77f79', 2, 1399, N'1000607', 57985.0699596689, 8920)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fe48a1e3-835c-4946-b7f2-b6ed7daa7ae4', 2, 1399, N'1000320', 48168.199001864828, 3139)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6270a147-7f74-40d5-994c-b6fb15ebcb3e', 2, 1399, N'1001500', 34265.845752217021, 2397)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1ed96906-908e-4f1c-ab4a-b7274e942193', 1, 1399, N'1000226', 5963.3870375123406, 729)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ed0e7490-78e2-48cd-96a1-b738e8e6ebed', 1, 1399, N'1000721', 54443.552077964727, 1046)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4ae671d1-9eb5-45f3-b01a-b73dbb256669', 1, 1399, N'1001555', 48376.920000000006, 84)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'794541ff-6a21-4480-b32a-b764ba90a3df', 1, 1399, N'1000801', 75645.37, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'568502b1-0772-4289-aec2-b789d90b2630', 1, 1399, N'1000772', 46179.154127701935, 1177)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'002e5210-e865-4bd6-a7fe-b79763d52105', 1, 1399, N'1001640', 49852.332569501494, 423)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9f1976c8-f918-4864-bee2-b7998200b5c9', 1, 1399, N'1001284', 55586.989999999983, 754)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'edaa20c5-3bd2-4814-87ff-b7a9a6658424', 1, 1399, N'1001263', 30593.367644846006, 18881)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c99620b9-5703-46df-91ef-b7b5aba20835', 2, 1399, N'1000931', 100780.03716688846, 2798)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8f6c43d5-f09d-4cc1-82e2-b7bcf8a206a0', 1, 1399, N'1000971', 35336.370144143068, 907)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5a43595e-ddc2-4470-99de-b7c332a8c89b', 2, 1399, N'1001351', 50130.051311811731, 1622)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc5e4e92-bb10-4611-ac0f-b7c82555a0b1', 2, 1399, N'1000270', 22295.972487465115, 915)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'34562fd4-181d-493d-9fa7-b7f053da58b9', 1, 1399, N'1000365', 110122, 418)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd919aeab-ae0f-4afd-97fe-b808503a793c', 2, 1399, N'1000081', 71564.685732745667, 4331)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'49feddfa-e454-4f9f-8afc-b8131bc51900', 1, 1399, N'1000356', 135467.93746978242, 1837)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f72f7c81-9377-4e92-ab43-b8452b8d6d8b', 1, 1399, N'1001364', 27523.807955166478, 9383)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'98f909d3-c660-405d-9a95-b8a110be76d7', 1, 1399, N'1000882', 38532.009999999995, 4022)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b46a8e4f-a459-48d0-8b61-b8ab6bbbb8ae', 1, 1399, N'1001406', 46449.48000000001, 7736)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fdf0a477-3e83-471b-8bc4-b8d810dc0a23', 1, 1399, N'1000534', 53722.897031489309, 2001)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c7463b55-4100-4d36-9a22-b8f489a60a73', 2, 1399, N'1000578', 7065.3793127804274, 1425.99606111)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'99668a03-f2ab-47b9-859e-b8fed3fc6025', 1, 1399, N'1001058', 76139.349999999991, 74)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0a6586af-b620-4d6c-b347-b93efe524432', 2, 1399, N'1000628', 28400.43001020591, 6599)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cfa1071a-2c77-4f02-a96d-b941b066e50a', 1, 1399, N'1000811', 796187.265338854, 220)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'73aafb1d-9e88-42dc-aae2-b9457674b839', 1, 1399, N'1001550', 270641.48259712232, 434)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3c17bfb0-1106-4ad3-8f31-b956fc147daa', 1, 1399, N'1000089', 138171.888922129, 3457)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f5f93aaf-4de0-4308-974a-b973b778d4f3', 1, 1399, N'1001524', 127568.25095399308, 136)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1922c5ed-c685-4677-b236-b997431304c7', 1, 1399, N'1001191', 43838.718233580978, 6458)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cac95217-48dc-4972-9a45-b9c995ce209c', 1, 1399, N'1000712', 53523.069999999992, 80)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'40548b8e-d51e-4332-9f92-b9d2dec67f1a', 2, 1399, N'1000833', 142049.92162446617, 309)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc619964-6f9e-4572-b560-b9dbc355d232', 1, 1399, N'1000694', 88527.57, -15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f0c0dd96-d7da-40fd-94a5-b9f2e01ef006', 2, 1399, N'1000973', 14128.945862344728, 1207)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'617c06e8-4d60-4d7d-810c-ba027741e3ef', 1, 1399, N'1000097', 21138.32, -3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e37d6261-9350-4625-9def-ba0fbb5bbddd', 2, 1399, N'1001033', 51000, 177)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9e648523-03de-4e8e-b35c-ba1ea6818d63', 1, 1399, N'1000419', 244464.92000000007, -121)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'69964c63-3209-4a27-86c8-ba2682be6257', 2, 1399, N'1000265', 168355.469140123, 1041)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f004638d-eaea-43e5-be96-ba3f7354ad83', 1, 1399, N'1000862', 50401.95399299475, 559)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'659fe136-2e5f-4baa-a3ba-ba76ca652f11', 2, 1399, N'1001744', 72203.345745696817, 1720)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'21555b80-5f05-42fd-9ada-ba81b7ad8226', 1, 1399, N'1001521', 184953.35286352356, 791)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f712b23e-2a62-4fef-8ced-bab788ab354f', 2, 1399, N'1000517', 48705.162930396669, 2322)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'de496247-ef5b-4ba3-8294-bac531bf4aa9', 1, 1399, N'1000559', 150626.3698168706, 1291)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7bf7c593-b6e6-4083-822f-bb2628b37976', 2, 1399, N'1001206', 34131.527117433965, 5486)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b25b329e-b407-4ccc-bbe8-bb394267b41d', 1, 1399, N'1001235', 39011.65758137298, 1381)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4c2f388b-4d8c-4358-9e64-bb3f440b9a1d', 1, 1399, N'1000531', 53761.079585673077, 1933)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1af58412-9b57-4e04-8132-bb4d8dfae382', 1, 1399, N'1001548', 74259.739999999991, 309)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7933727d-697d-49e6-bf77-bb540a232c9f', 1, 1399, N'1000732', 106647.44000000002, 76)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cdac6207-9d9a-494a-9e5a-bb5d0a760ecc', 1, 1399, N'1001093', 270000, 8)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'81572a89-ba03-4da6-a9c1-bb5f3c777b97', 2, 1399, N'1001257', 29724.999999999993, 4801)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'05d654f6-a469-4721-9a37-bba7b282e8cd', 2, 1399, N'1000247', 23708.049635881809, 2683)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'126971bd-a39b-4038-8441-bbae23a7dd8b', 1, 1399, N'1000515', 28300.097870212761, 7475)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0580a36a-156a-49fd-ab4d-bbb2644c011f', 2, 1399, N'1000620', 154128.44, 426)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e8d32722-d147-4f7b-baeb-bbde5c44c1d9', 2, 1399, N'1000537', 77024.927204760417, 1585)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c0014480-4a77-45be-be8d-bc33caef3a92', 2, 1399, N'1001227', 49991.099754554445, 7578)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'81bf3608-f41e-4996-8253-bc42a2708195', 1, 1399, N'1001255', 31963.019999999993, -255)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b88f1b38-aa8a-48ee-aaf9-bc459a4dc5d8', 2, 1399, N'1001637', 85142.010163325176, 230)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1443515f-ed96-4892-88fc-bce96a03389d', 2, 1399, N'1001508', 151376.147, 786)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'59aef59e-c5a5-405b-ba7a-bd0ab45379d9', 1, 1399, N'1001522', 135632, 711)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'78f16893-b04d-4ed4-9779-bd12c4e40c54', 1, 1399, N'1001458', 23000, 17)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9097e4b6-aa43-4275-8b66-bd43ece80eec', 1, 1399, N'1001389', 417380.93, 168)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'410814a8-a122-4d43-966c-bd44ba57e95b', 1, 1399, N'1000265', 155247.53412570886, 1134)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd94934ac-8401-4a24-81ca-bd5acebde08f', 1, 1399, N'1001080', 73094.958894894909, 3132)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e9c6e487-5c99-4fc8-a643-bd5fa712859b', 1, 1399, N'1001377', 127588.98000000003, 533)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4a180f10-fb47-433f-bd82-bd62dd6a932b', 1, 1399, N'1000823', 85364.207741965234, 2093)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e825e983-66d6-4d5c-9c5c-bd8dce17ee39', 1, 1399, N'1000045', 86634.524844509928, 3774)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e87668df-2fd7-4212-9728-bdb0c76e9c5e', 1, 1399, N'1001198', 20595.210685347527, 10458)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8ef33ecf-6ff1-4e54-9644-bdfe30f95c0d', 2, 1399, N'1001345', 33792.049000000006, 1871)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'24c1f171-02ea-4bc5-b54c-be26bcd23623', 2, 1399, N'1000123', 175436.73159346363, 1522)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'743665c8-3ffa-41fe-b97b-be86a190e1f0', 2, 1399, N'1000656', 8715.596, 7868)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'15d1e833-74dd-483b-a12e-be8af187edeb', 2, 1399, N'1000548', 79147.286360442347, 575)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3cde257c-8399-41d7-8d6f-be9d53356815', 2, 1399, N'1000720', 40041.852247886913, 1221)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1acc4096-1147-4dca-bd6d-beb75e2f6207', 2, 1399, N'1000248', 26402.004267314027, 3006)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'34aa2ef3-d0b1-4215-9d1f-bec725cc6bfa', 1, 1399, N'1000938', 33885.604596124809, 3635)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2628e24f-3382-4512-91ae-bf002146862d', 1, 1399, N'1000645', 762679.0024314709, 523)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b77b7406-9535-47ec-9ff0-bf200dac6697', 2, 1399, N'1000155', 80539.654670868418, 2043)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b32f5e39-87a2-4626-b336-bf3899cb5dd7', 1, 1399, N'1001403', 40182.999912144485, 2561)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6b9c864a-4c11-4dcb-89a7-bf39d4515ea3', 2, 1399, N'1000477', 52155.078252595187, 2592)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1f0bea6e-2467-40c4-afcd-bf4ab32e332a', 1, 1399, N'1000016', 27660.07, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9645ad92-099e-4f16-a2c0-bf777d1d23cf', 1, 1399, N'1000572', 3532.06, 13)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ed70c697-f315-43f3-b12a-bfa1956b0437', 2, 1399, N'1000053', 123140.51667869175, 1050)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd8fa61d2-f0b1-4f42-ae89-bfb34e767c7c', 1, 1399, N'1001345', 28556.125912098778, 5332)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd61f7fee-1dc4-468d-99be-bfb815f28d19', 2, 1399, N'1000462', 10733.954961457432, 9038)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'15a8520e-7128-4c17-a19e-c01aae5722c8', 1, 1399, N'1000234', 80282.350159083464, 1532)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'989c40b0-4a51-43c6-a22e-c0538ee0b29b', 1, 1399, N'1000277', 29050.31, 9)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8af6d7ef-c084-4429-9221-c067de4ea45d', 1, 1399, N'1001580', 280157.09433962265, 1181)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4b9fa0da-7464-4848-b090-c06f39143ea1', 2, 1399, N'1000499', 27909.716446741844, 5543)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d852ed1-1d2b-4f38-927b-c079daf9049b', 2, 1399, N'1001574', 122664.06108069469, 2478)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6eb7386e-99d3-4df8-b80d-c07b41658108', 1, 1399, N'1000887', 824729.03999999992, 223)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd463c22c-343c-4ae1-bd71-c089c733bbd4', 1, 1399, N'1000679', 157688.95, 11)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a1802be9-c015-47b6-a5ba-c0c5d996ed50', 1, 1399, N'1000423', 38532.29, 57)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'63e4844a-e5d4-4ca3-b74a-c0e500033847', 2, 1399, N'1000171', 14400.211127176381, 5492)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b60c8d1c-5d55-4c4f-9c6e-c1017ae0dc79', 1, 1399, N'1000650', 907712.81872531318, 444)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'86a70859-c7e7-4ea1-844f-c132901ce848', 2, 1399, N'1001634', 23857.315313653475, 1978)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d480385-b815-4149-80e1-c146f692e7ab', 1, 1399, N'1001303', 22475.918824638593, 482)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'13bbee6d-52a5-4efd-ae34-c1548d08372f', 2, 1399, N'1000099', 56568.6206509852, 2797)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'67ebd710-af01-45a1-ac60-c16dc4d371f5', 1, 1399, N'1000573', 7068.1946078223555, 2613)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8f23b324-b91e-4b0d-ab10-c16e40f06418', 2, 1399, N'1001000', 47330.460588210786, 13801)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7452e13e-6755-4f28-900e-c1806734efe3', 1, 1399, N'1001265', 499977.44, 214.488)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e5fe0b59-f824-4911-9c46-c180adff0340', 1, 1399, N'1001567', 57902.735731821813, 4792)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'46ce1f3e-398a-4681-ab8b-c18645f9fc57', 2, 1399, N'1000562', 745000, -131)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0b8482d0-6aa8-4899-b10b-c1886a8a0ceb', 1, 1399, N'1001292', 40000, 45)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2b28b17e-9ee0-4f85-bd48-c1a2661cae62', 1, 1399, N'1000154', 151629.51765086205, 1830)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'76553cf8-4728-4ed2-bd20-c1c45fee3520', 2, 1399, N'1001226', 137921.62759069834, 2436)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd541da80-74d4-4898-86d3-c1cf66f6d362', 1, 1399, N'1000825', 39909.49, -2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5c7f60cd-98b7-498a-b94d-c22fb9b9fcb8', 2, 1399, N'1000575', 7161.6023110539472, -978.99854667)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6a93b994-a63f-4686-9b31-c239c387ed27', 1, 1399, N'1001563', 45554.7040600345, 1143)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f57a2e16-93ba-436f-a7c8-c2754b63ed73', 2, 1399, N'1001269', 58829.204665118443, 2724)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'adc4c37a-06e1-48ea-afe4-c288f695ce5c', 1, 1399, N'1001528', 635780.828550885, 399)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'accd06e1-1b48-4aa3-b302-c2d19476f084', 1, 1399, N'1000660', 46790.392577245526, 2880)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c79a33b1-51fd-4562-a660-c2ef8a5cf5fc', 2, 1399, N'1001375', 56941.618592314924, 5686)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'888558a2-8a16-4cff-a0cf-c313483f5139', 1, 1399, N'1000570', 66002.74112869885, 5110)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'411afd1a-2b7a-4ad7-9a45-c31a77581eec', 1, 1399, N'1000402', 34373.19, 7859)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'daae79f8-ff09-4c3b-96c3-c324138c8cbe', 1, 1399, N'1000044', 64162.656845740174, 2432)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6a0bbd1d-97d9-4af9-80c2-c340c008532a', 1, 1399, N'1001139', 7999.99, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dc1e3cf8-9377-4d8f-a87a-c3500bab4dad', 2, 1399, N'1000606', 329697.73033673124, 1699)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dc72a98c-36cd-4097-84b9-c3519a17b6a6', 2, 1399, N'1000545', 116150.31060291446, 446)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4c4f2a9d-b3cc-4343-894e-c35fef131ca4', 1, 1399, N'1000641', 552773.704332425, 72)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0c4caa71-d503-4fc0-bc6e-c388f62ec99b', 2, 1399, N'1000489', 419835.78622470715, 951)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'55db7298-de4b-459a-89a9-c38e7af1206a', 1, 1399, N'1000121', 404843.60308267456, 1126)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5f07109a-9e25-4ba8-86f4-c3a45c3d9bc6', 1, 1399, N'1000051', 97543.627755969777, 609)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'547d5de3-1088-4f4c-9d68-c3a52bbe9aa5', 1, 1399, N'1000170', 14367.867218916374, 3596)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'238cc164-ca75-480d-8d99-c3b5ba074976', 1, 1399, N'1001575', 122539.93287688986, 2206)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'63b7978a-83e2-4a6c-a318-c4281e583442', 2, 1399, N'1000511', 14132.461530864239, 40086)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8a5ce3ac-4f81-4801-a36d-c432c553782f', 1, 1399, N'1000156', 210038.63547816471, 1194)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ba48377a-a248-4c9b-bd6f-c43c01558d6a', 2, 1399, N'1000527', 103315.25799889033, 2637)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'418d289b-0b20-4f1d-bea0-c4605849be58', 1, 1399, N'1001410', 836417.87718017935, 7107)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4b851d69-e269-44c3-bd8d-c46110fb1184', 2, 1399, N'1000139', 209459.45945945947, 3450)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'73ab1823-62a2-485d-aabd-c461f3ad30e0', 1, 1399, N'1000564', 96000, -3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c4d1c47c-29e8-4ba6-8d9d-c46cd7a3a572', 1, 1399, N'1001288', 36959.070529871904, 7058)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0e14d9cb-e92b-4a06-9ddb-c47f83df0e85', 2, 1399, N'1001348', 34226.7389591156, 7003)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'71759e79-ba33-42ff-9dfe-c49492fed358', 2, 1399, N'1001613', 63302.752, 2300)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd431fa96-7773-468f-8d66-c517dc1fd4b6', 1, 1399, N'1001194', 20825.460000000003, 6540)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7ce28021-58cf-4199-b6e5-c531c313325b', 1, 1399, N'1000169', 64240.85914179105, 1493)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'53ec5724-2c3a-4d04-9df5-c545386c52d2', 2, 1399, N'1001293', 52465.968342447995, 474)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'586f78d5-c610-4a4b-8493-c592bd1768ee', 1, 1399, N'1000956', 122845.1365463961, 1801)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c203fad2-f37a-42fb-93fa-c5a09b016c7a', 1, 1399, N'1001048', 113648.20755633546, 2888)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'014c5d54-3a11-46e0-80a0-c5eb18921515', 2, 1399, N'1000601', 22711.309124145359, 2930)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0581f0ea-b93f-4518-8d55-c6639ad2b685', 2, 1399, N'1001055', 54123.0057021074, 8569)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c5e6eba6-4adb-4982-a6e7-c6d7377ca6bd', 1, 1399, N'1000293', 26875.318469937985, 1084)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd908ad17-7a8e-44f3-888e-c6e2d6d61308', 1, 1399, N'1001236', 47172.419885145959, 680)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f630a72d-ef63-4558-b8f4-c6ef46d95233', 1, 1399, N'1001195', 11995.312025647112, 18617)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8bc1700d-f27a-4366-94e8-c759151dddce', 2, 1399, N'1000791', 74595.659786742966, 3169)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'98e0953e-be18-46b3-99fb-c77c51c4548f', 1, 1399, N'1000719', 158888.38, 404)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'72c38038-f9fe-43d2-bb9c-c78af998cc66', 1, 1399, N'1000203', 25369.448548191194, 9233)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7fc60b6a-b345-44c6-8eea-c7a2f1034623', 1, 1399, N'1001310', 67271.3234418441, 2107)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a9dc21ef-b090-4958-a301-c80fbaa01549', 2, 1399, N'1000909', 136697.248, 1962)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f8305aca-3545-46fd-9edc-c81c51a25e0d', 1, 1399, N'1000653', 1111728.26, 50)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'80d53d17-43d8-4d98-af57-c82e7fa9f68f', 1, 1399, N'1000176', 206581.40831295843, 231)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'db10d5ca-18e3-42fd-a761-c837b5c1a4d8', 2, 1399, N'1001614', 82568.807, 847)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'53817e72-c640-4101-9391-c8619cecd655', 1, 1399, N'1000274', 17891.858149976761, 2794)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd81c6447-4868-410d-acee-c862c7f6020b', 1, 1399, N'1000702', 142130.92427586205, 338)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'92b26d92-b202-4093-9797-c8837cfae166', 1, 1399, N'1000332', 85348.462704632373, 4417)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e22ffcaf-732b-4add-a088-c885ec3975cd', 1, 1399, N'1001500', 34265.820000000007, 3546)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ad2f38ff-478a-4de9-9804-c8868e46f4b8', 2, 1399, N'1000811', 801899.987058996, 210)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd03273c1-a6be-4c23-bcd8-c89795ee2c8e', 1, 1399, N'1001014', 142560, -47)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a97cf1a4-4d79-46cb-8614-c8a12636ca98', 1, 1399, N'1000420', 144166.44, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f0e7b083-3e9b-4bef-ad38-c8b025da6762', 1, 1399, N'1001624', 313702.12660731951, 1940)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'555053f1-fbbb-453e-8895-c8faaf2b01cc', 1, 1399, N'1001261', 157093.81899940965, 1568)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b354a7e7-a257-48e4-9102-c9073796460e', 1, 1399, N'1000525', 46234.36, 3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b33c51ff-62fe-4fe5-87ee-c907577bcc82', 2, 1399, N'1001541', 24406.808013936792, 5266)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4e7267a3-aa89-42f8-9164-c93f1103b744', 1, 1399, N'1001653', 392022.07413577678, 2209)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fb7fd332-be0a-48df-afc9-c952539dda9f', 2, 1399, N'1001309', 80300.910308004881, 1476)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'681fbbbd-cdc1-4952-9a5e-c9570a310de6', 1, 1399, N'1000654', 21220.050000000003, 314)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b7667efb-4c01-43bc-93a6-c95b72b90c6a', 2, 1399, N'1001674', 209000, 100)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'462709ae-306d-45f3-8b1a-c97a3d7139cf', 2, 1399, N'1001510', 153189.23980113876, 1115)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'33ef0d3c-89ab-4247-b48e-c993bd5c93ff', 2, 1399, N'1001546', 720097.33092514554, 802)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5b083fa5-ace4-4115-abd4-c99d314abc1d', 1, 1399, N'1001328', 36485.99, 117)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9972f7a6-abde-4f72-8435-c9a25ee6813c', 1, 1399, N'1001552', 64219.890000000007, 661)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a779d17b-d0b6-48b1-b63e-c9bc0641143c', 2, 1399, N'1000851', 399000, 4346)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'78d3a23d-4f73-4823-91e0-c9cc60fca0e6', 1, 1399, N'1001234', 51989.760506367296, 1762)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d7ea32a-c45f-4313-8f43-c9cf6bf7603a', 2, 1399, N'1001258', 29726.783913238593, 4510)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1cb4fbc2-3b85-43c1-9306-c9f5a552b66b', 2, 1399, N'1000380', 233410.93477327551, 2276)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ac7554b5-2da5-4172-823f-c9f942ff885b', 1, 1399, N'1001143', 56000, 5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd8fdbeb2-e796-42f5-8e6d-ca052f8b0dbd', 1, 1399, N'1000102', 112024.09390762927, 2459)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7747b719-d7d2-4f95-84bc-ca29f4136b0b', 2, 1399, N'1000586', 24770.642, -69)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7097174e-d224-4358-968d-ca36f001f2ec', 1, 1399, N'1001426', 874163.9879063135, 239)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bf1ff838-65a0-4411-a336-ca3f85666bdb', 2, 1399, N'1000083', 46851.205216799361, 3661)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dfdd946a-d8ee-465e-a011-ca5904ebbcf4', 1, 1399, N'1001313', 76324.649583904888, 320)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7764aff0-dd7d-4454-bc7a-ca67a072e2d7', 2, 1399, N'1001733', 79319.055419899771, 1321)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e79ade3c-fe6e-429c-97a7-ca6e2dbd2b09', 1, 1399, N'1000866', 115941.57648547423, 1387)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'535b4c2c-a5aa-4bf5-b2d1-ca8279a9da0f', 1, 1399, N'1001042', 318891.19999999995, 18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c35f6e79-6696-4e1f-8fa5-ca8a98c4637c', 1, 1399, N'1001116', 67335.108565039554, 1619)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'390914d6-2021-4b91-b55e-ca9ac9dc8993', 2, 1399, N'1000941', 45825.688500000004, 650)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5e24e31a-7ff2-4a0a-8742-caa2d27f3979', 2, 1399, N'1000984', 56280.730974207509, 3465)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1bc49ce5-5527-436c-be57-caf93f4e39d3', 1, 1399, N'1000633', 378964.82562600757, 157)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'01a1ec67-676c-4f43-8eb8-cb2a7ef34ae6', 1, 1399, N'1000276', 18227.797224978578, 3012)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8fccb32d-b451-435d-9f1a-cb2cb8757679', 1, 1399, N'1000979', 45690.374476233184, 1022)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3678f4dd-06a5-4ed8-9133-cb32107c742b', 2, 1399, N'1000004', 20560.580567274847, 12135)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'524e127a-65bb-4f41-9677-cb44930f92a7', 2, 1399, N'1001651', 209227.18012455519, 966)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e304104a-dbc4-4b04-8c81-cb4adea75660', 1, 1399, N'1000158', 138610.19277596995, 2291)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'155537d1-b7e8-4af4-a1df-cb5c5cbca413', 1, 1399, N'1001098', 104886.29898928205, 5570)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f6d8548d-cbaa-4400-a2e1-cb935c772b0a', 1, 1399, N'1000223', 14679.32, -38)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'22dab813-2034-49d5-a479-cbd333d298ef', 1, 1399, N'1001331', 40207.356358490557, 44)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'13316621-19cc-495d-8591-cbde382ea704', 2, 1399, N'1000638', 282805.67797389237, 786)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a6203462-36ca-4ffb-904c-cbea6390db84', 1, 1399, N'1000511', 12463.001176432983, 3474)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8224950b-affe-403f-a11f-cbfb4c202713', 1, 1399, N'1000703', 161277.96588453787, 1161)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bdf7bc3e-f9ff-4ca5-b13b-cc0bfa91a618', 1, 1399, N'1001614', 63706.358491094164, 885)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eae2ff0b-2b16-4d05-a0ec-cc38e91284f3', 1, 1399, N'1000225', 17882.870394987069, 2952)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e6c80787-950e-4f77-b0fd-cc3a9503f680', 1, 1399, N'1001294', 25000, -2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'768d54c6-a0b5-4906-bb91-cc6e7943be5e', 1, 1399, N'1001549', 132770.13, 7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'901d461f-42f7-4a7d-a228-cc8b156f8780', 2, 1399, N'1000443', 98141.963791688453, 991)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9706f142-6b4d-45f7-b2ad-ccfad9678043', 2, 1399, N'1000766', 50733.780620370933, 1270)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'33dc860f-391d-404b-b54b-ccfdd816c707', 2, 1399, N'1001279', 59633.028, 3119)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'12291b20-fae5-49e0-8e2a-cd77e116afb5', 2, 1399, N'1001386', 76633.333844765264, 2266)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0695523b-e9fe-498c-8189-cd84a71b3bfb', 1, 1399, N'1001366', 109342.2339552464, 1270)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'33125e2f-c992-435d-b729-cd94c941e7cc', 1, 1399, N'1001526', 79314.498413259658, 843)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a8665776-6a3b-4ff4-856f-cda2df72ae4e', 1, 1399, N'1001368', 10671.842778723401, 1667)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cc02877b-cc4b-4347-96a5-cdd76721af49', 1, 1399, N'1000966', 391111.37888115691, 2049)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cb2acec5-dc25-44cc-88f5-ce0105a50d52', 1, 1399, N'1000112', 53553.555043241235, 1054)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a434cc73-ad33-4ef2-bd78-ce03d67a02b7', 1, 1399, N'1001053', 495560.75000000012, 69.594)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'632199eb-2a46-4775-af62-ce067e8a574d', 1, 1399, N'1000280', 17906.104035409233, 6439)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'963f1dd1-9c3f-41bd-b91b-ce1b472cb2b4', 1, 1399, N'1000398', 104964.64, 2337)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'689b54ad-7f6a-48d2-aa2d-ce24ed6ac2f2', 2, 1399, N'1000293', 26869.436649214658, 1596.86)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'141d3aa6-3fdd-4213-8f89-ce4f15da2925', 2, 1399, N'1000535', 82000, 1559)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0b7d29c3-7df5-4df9-99e4-ce64fb0a9744', 2, 1399, N'1000264', 62948.7047829055, 2768)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7ffaf8c0-5c76-4485-b98a-ce658a8c77e4', 1, 1399, N'1000994', 30728.919999999995, 48)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2f8cb633-d952-40a3-8cbc-cec926163c88', 2, 1399, N'1001396', 299000, 2041)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'96289786-0921-43a8-a772-cf0daa6b8aea', 1, 1399, N'1001201', 239400, 17)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b4da70cd-271e-4554-9cc4-cf1677767371', 2, 1399, N'1001647', 143154.74433866135, 1947)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e58dd602-c072-4be0-a6c1-cf8f959b5453', 1, 1399, N'1000415', 45000, -115)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6530f572-5e9d-4095-992e-cf95e284edd5', 1, 1399, N'1000151', 138389.25712719298, 174)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'11eefa64-29ba-4df9-901a-cf99dc2c60d7', 2, 1399, N'1000479', 105504.587, 632)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2207dd09-feaf-457d-8102-cfb5145ebdc1', 2, 1399, N'1000960', 260444.13665390643, 1798)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3e580eb4-a107-4b7b-8185-cfbfc55ce36c', 1, 1399, N'1000728', 171000, 5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bda3179d-1fab-4b08-91d8-d00185a9f581', 1, 1399, N'1000205', 1063524.2365583177, 4899)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'96e7284a-a8c6-4b91-a9c6-d041c87de6fc', 2, 1399, N'1001302', 85900.970799130824, 2538)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'afc14fef-4445-4e95-9f14-d04c5cf2f264', 1, 1399, N'1000884', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b39a6406-c9cb-4b73-b0fe-d06034bf3ee0', 2, 1399, N'1001657', 66972.477, 1733)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'52b3cc62-932f-4fb6-9bea-d0a5ebb90537', 1, 1399, N'1001183', 181000.91579379028, 1490)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a96b4930-0b2f-4b24-ad2e-d0b82a5e23a7', 2, 1399, N'1001699', 120000.00035709026, 228)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'14e0ff3c-e045-43bb-85c7-d0f657787f89', 1, 1399, N'1001398', 7064.0983568748888, 31376)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bcb84f8f-646a-4ca6-bb6b-d1086a7bbd90', 1, 1399, N'1000869', 41284.450000000004, 55)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3ebbe0cd-91c5-43bf-a19a-d10e74d81e7e', 1, 1399, N'1001673', 98393.9937909695, 4759)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b6e684cc-c7f4-4bb0-8e23-d129dba50144', 2, 1399, N'1000723', 65128.360927896676, 1660)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'418e6297-1fde-4420-868b-d15c7e242bc8', 1, 1399, N'1000213', 19355.269653383169, 16037)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4156e18c-33e9-4c69-8183-d15da8240f25', 1, 1399, N'1000106', 101128.52677295965, 1810)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e2039adf-582e-4c91-a29a-d162945d69f4', 2, 1399, N'1000012', 9747.9130423103688, 11498)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2fc9263d-52f4-4738-9be9-d1a299e26d21', 2, 1399, N'1001700', 156016.30901287554, 1118)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2a6a9f38-3cff-4ce0-998a-d1bd7fe40994', 1, 1399, N'1000451', 63011.747320205672, 4695)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'74d62ee2-60a2-45ad-abab-d1ced94c75c9', 1, 1399, N'1000910', 14653.18, 29)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd2794729-dc7e-40e3-9bfe-d1cf06bd7621', 1, 1399, N'1000477', 52466.851746046508, 3160)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b07bf2d4-d173-460b-9b7d-d1cf43072a72', 1, 1399, N'1000130', 96329.66, 215)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6878e3ec-5ad4-4279-93f2-d25abcbf9a6b', 1, 1399, N'1001217', 46592, -6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a8a4a6d8-cffc-482d-85d6-d268ab481dd1', 2, 1399, N'1000059', 158568.80592891574, 1458)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'49b4f02d-2213-4f0d-b841-d2737a645c22', 2, 1399, N'1001455', 132935.78, 1777)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1a34987c-c66f-4a23-9f73-d2a6e9a83d5d', 1, 1399, N'1000557', 222555.55999999997, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc9bf8cb-f060-46af-a151-d2a8f5a2610e', 1, 1399, N'1001100', 334112.1249875623, 2703)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f72172e0-4ced-4400-aded-d2c14c8b1b51', 2, 1399, N'1000273', 19504.227780331046, 3339)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7a321fd9-087a-4526-9538-d2cbaf2be7f5', 2, 1399, N'1001622', 48226.215930443774, 2323)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0e5b0cbf-2417-47af-95e4-d2e119bd9502', 1, 1399, N'1000560', 40237.620334183855, 1120)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'23154cf5-b896-4f55-aacd-d2e167cf627d', 2, 1399, N'1001641', 117152.07124387674, 5630)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5166721d-b745-4bcc-8c20-d2e85a801590', 1, 1399, N'1001593', 431246.78920202027, 164)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b5c86893-1a3b-4b03-b3af-d2efdc1335a6', 2, 1399, N'1001576', 82568.807, 4592)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a8bd2640-7ec8-4e7b-ae0e-d34e26456db1', 1, 1399, N'1000285', 21837.904466683336, 3004)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'85b1cea0-c3c0-4efd-870e-d36696678186', 1, 1399, N'1001205', 117488.63999999997, 14)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e26147b7-80d6-4551-8e81-d37c06f46770', 2, 1399, N'1001186', 52451.285976729945, -548)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a70b42b3-2042-4c31-a36e-d38b817b437b', 1, 1399, N'1000830', 1738333.4899999998, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a80503b0-c871-4c2f-8dbb-d38ca6751178', 1, 1399, N'1001486', 146475.92000000004, 149)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'68587d20-9597-4c0e-b7f3-d38e3ad36aa1', 1, 1399, N'1001028', 590144.78, 422)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bfaa06e9-f5e0-4c8e-afc1-d38f9d517920', 1, 1399, N'1000057', 46079.553825293035, 3903)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'674594af-41b9-4e97-acff-d392c16bf25f', 2, 1399, N'1000871', 86924.637295589127, 5303)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'46bb5637-363f-459e-b2e2-d3aa909eeb3c', 2, 1399, N'1000189', 22506.324666198172, 1432)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'09f78bbc-24cb-46f7-8f41-d3f175b91147', 1, 1399, N'1001407', 49265.73, 6470)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0a8f1fd4-75f0-4b13-8b80-d4322767c66e', 1, 1399, N'1001019', 100063.46789884639, 24064)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c06c38e8-5e24-4c77-999b-d4339e58fdcb', 1, 1399, N'1001158', 135999.86, -2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ff428ba3-91ee-4295-86a8-d497e5ae8427', 1, 1399, N'1000502', 3532.6862022222222, 19672)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7b1495f3-b5f6-43b7-a928-d4a7304bbe42', 2, 1399, N'1001659', 38215.679096142478, 1455)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7b07ea29-25f0-49c2-bed8-d4a778a6aa52', 1, 1399, N'1000104', 125197.76196914875, 1569)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'167cae49-d988-4b50-a883-d4b556d657fa', 2, 1399, N'1000122', 124770.51574686423, 1659)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a9338084-78c9-4ecb-b1f0-d4b756821089', 1, 1399, N'1000562', 728493.9, 27)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'54a53056-9c93-451b-bea1-d4bd9685018c', 2, 1399, N'1000340', 278720.5467062348, 1250)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'10d41f9d-6660-460c-9759-d4cb0ac28a7a', 2, 1399, N'1000979', 49449.541, 980)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e09875df-e303-4247-87ba-d510222146d2', 1, 1399, N'1001583', 141358.36504263961, 1319)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cebccfd5-b378-4198-a929-d52f6437bf5e', 1, 1399, N'1001262', 30564.857352631112, 17313)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a0099b6e-4786-4f80-9a49-d551bc80474a', 1, 1399, N'1001175', 61658.709999999992, 7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'34930fe5-72dd-4267-92fa-d5889d8a463b', 2, 1399, N'1000019', 42539.13098133725, 4282)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3e2383d2-9cea-4df3-8f2d-d58f52d40f66', 1, 1399, N'1000845', 135520.02999999997, 21)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5209c58f-814d-4512-8945-d59f356f6eeb', 1, 1399, N'1001529', 11926, 9338)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7f97534f-e153-41aa-9552-d5b78f595ed2', 1, 1399, N'1000450', 12624.955385114798, 11844)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8fe2fe5b-b133-4208-abda-d5bc53fe9754', 2, 1399, N'1001251', 126817.67471596522, 54709)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0b6452e9-2559-4212-899f-d5d1838bcef8', 1, 1399, N'1000136', 41295.578272336126, 2334)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dcf3b867-0fc8-4c51-a42f-d5e543edb8fd', 1, 1399, N'1000930', 241761.80735322775, 165)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd1e2f769-9a0b-4af4-8493-d63534ee6d36', 1, 1399, N'1000090', 237006.32690090008, 3261)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'65746721-c0f2-4442-906b-d66385d85aff', 1, 1399, N'1000924', 220419.71534969591, 644)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'de349947-84f8-4d2e-b6f4-d6b9206d1e1c', 2, 1399, N'1000338', 61750.048461630031, 4222)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc1d8bc3-75c1-46df-a01e-d6d225474ecb', 1, 1399, N'1000351', 226655.37000000002, 378)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5fcc9286-b1a1-47d4-92d0-d6f4cfd4cd99', 2, 1399, N'1001346', 32314.142456911464, 4672)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'10b1b969-d557-46ad-b139-d6fcdbb6867b', 1, 1399, N'1000110', 9688.0311351924211, 4145)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd47e1112-c00b-4c1e-86b0-d724628db91d', 1, 1399, N'1000959', 282449.03952450393, 1507)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'529ec083-d3c8-43f5-9f77-d7746a92edf2', 1, 1399, N'1001196', 33027.51, 101)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c96c93e5-f607-47ba-b5a9-d79d2078ac9e', 2, 1399, N'1000658', 3532.331143713483, 2411)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'05da9e10-accc-499d-954e-d7d6263e4b2c', 2, 1399, N'1001533', 529000, 3257.047)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'439c828e-c188-4207-a736-d7eb3b84b4e7', 2, 1399, N'1000151', 277712.5, 1212)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'07c5ab76-6627-4c76-94e7-d7f66d471628', 1, 1399, N'1000255', 90861.96, 8)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b2f45b97-edf4-48e5-b039-d803a14d5bf5', 2, 1399, N'1000673', 14739.955405925983, 16560)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'04c4a56f-9be8-40c3-8eba-d8133c07efcb', 1, 1399, N'1000753', 155101.90088906372, 860)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1d17b2dc-9135-4637-ad60-d817dee5ab97', 2, 1399, N'1000219', 29353.360601303997, 6876)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ac274bdc-a388-46ef-b0a3-d830cc9d3b00', 1, 1399, N'1000286', 21806.604989277897, 3008)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b1941af8-ad52-4e50-a0f6-d85e0cb63003', 1, 1399, N'1000400', 17037.212617710586, 231)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'39bac0d0-2cba-4aef-9172-d8609dde9400', 2, 1399, N'1000692', 31735.43978669112, 3923)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'42f79e15-855d-4185-a2aa-d86b0548178a', 2, 1399, N'1000571', 78999.42660369318, 4978)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3398dc8a-d89e-4db1-8220-d86ecc965c47', 1, 1399, N'1000291', 41314.148436657684, 291)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1690771c-264f-4953-b083-d88a3187a226', 1, 1399, N'1000543', 133946.59882334626, 1282)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f316374b-1594-4d40-905c-d891eb2b1a32', 2, 1399, N'1001693', 87696.929656095745, 5680)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8e3ab959-27c9-4bd4-bc32-d8bd793b4fce', 1, 1399, N'1000376', 44724.740000000013, 107)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'175554f5-c19f-4af0-a92e-d8e408aa6503', 2, 1399, N'1001727', 120006.24219725344, 1388)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f3a1868c-937e-41a7-a08b-d8fc0a89ef69', 1, 1399, N'1001477', 137630.83032549018, 881)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1526c76b-216b-4ba2-8c67-d90b66865ac6', 2, 1399, N'1000329', 64349.925900361872, 4170)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5c8caecd-91f2-433a-a720-d92c82564e5e', 1, 1399, N'1000418', 1, 0)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bfc8b2e4-6132-4df1-8031-d95ab27e8277', 2, 1399, N'1001397', 7065.5270334253673, 13784)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'969daf15-68e6-4167-be6d-d977e159deea', 2, 1399, N'1000540', 96457.485324038149, 394)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2b0376cb-0428-45fe-9488-d992b78bae15', 1, 1399, N'1000100', 19927.840489426628, 3563)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ef6bea7c-af47-4835-a88b-d9ca93bfa281', 2, 1399, N'1000401', 43119.266, 4999)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a066763b-e1a6-453a-a09d-d9ce0c31650f', 2, 1399, N'1001452', 105504.587, 616)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fe25c4d3-c7f7-449d-af91-d9e6a296a8d0', 1, 1399, N'1000769', 26818.804520718772, 991)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c0042259-5ea2-4176-8f72-d9e848b1d3f5', 2, 1399, N'1000366', 143885.34012574275, 2706)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'66d129ee-117a-4224-bfd9-da245c9b4c1f', 2, 1399, N'1000375', 67025.751537027623, 5232)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f7468667-fcfe-4075-82cd-da2d892706aa', 1, 1399, N'1001151', 80000, 6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1b538f4a-8604-4404-89df-da3e76eeb03c', 2, 1399, N'1001468', 66678.467463863926, 1798)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b1e33e8d-2f55-40ca-86e0-da4dc35294b3', 1, 1399, N'1001106', 3843617.9545621015, 50)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e4b5d93e-b6bf-4d86-ba97-da6295dc6cf2', 2, 1399, N'1001504', 343889.51023775485, 948)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4dd7959b-9fee-4991-846e-da64aafd2b9d', 2, 1399, N'1001207', 34139.0643143616, 6102)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1dfdba87-a3f3-4734-852e-da6c74d6d437', 2, 1399, N'1000195', 60537.588493682495, 17458)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c54b635b-edc4-4cfd-b5cb-daac8fc55123', 2, 1399, N'1000001', 33679.422899061596, 12024)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5d6aac6f-7c05-4f11-bd23-dac73dd36ed2', 2, 1399, N'1001512', 418157.0035511906, 1912)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'587b5639-fc70-4bd8-bf9d-dad51610a833', 1, 1399, N'1001279', 56348.019999999982, 5849)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7ac0df8c-b219-4f62-bdc0-dadfa4e70bc0', 1, 1399, N'1000229', 23278.582710828028, 9508)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3519462e-21df-4625-a596-daefab654b66', 2, 1399, N'1001234', 51979.549682309982, 1671)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a96d880e-399c-4098-b834-db13a344f4ab', 1, 1399, N'1000408', 36504.813997245168, 2435)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'27cb7d00-6676-40e7-aa49-db40220c953c', 1, 1399, N'1000467', 68254.072611209966, 3730)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ba167971-1964-4b7d-be59-db79d9db9a06', 1, 1399, N'1001243', 80733.89, 14)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a306cb40-1502-40e5-b5fc-db85938625b8', 1, 1399, N'1000932', 77564.167735474752, 586)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'18fc3993-e955-4ea5-8775-dba3fedf5c4b', 1, 1399, N'1000166', 209375.04528063152, 3562)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'703ec417-53b5-4644-9bcc-dbb1761ffa49', 1, 1399, N'1000860', 64499.60957293438, 2297)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c4c41dc7-d9a4-4f81-a356-dbcad1dd4b75', 1, 1399, N'1000851', 298669.40388251311, 4779)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fdbe00b1-15aa-4baf-b2f9-dbe90623a758', 1, 1399, N'1001187', 133374.01706033372, 96)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'062c3da0-7b3d-408b-873b-dc2ea23c9789', 1, 1399, N'1000587', 21179.88, -34)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3ad87386-54f9-4bd8-b9ea-dc492c7b2a8f', 2, 1399, N'1001399', 7063.9999442533144, 3327)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'47ab5d2b-8a03-4fb5-b9e4-dc6333d4a81e', 1, 1399, N'1000757', 75958.372144241934, 4019)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ad6c97c8-86c1-4ff1-89bb-dcac8d7cbca1', 2, 1399, N'1001494', 31838.525991547496, 2551)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0a468752-a31f-4793-aa9d-dce1f4644174', 2, 1399, N'1001277', 686682.21945981216, 896)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f4c30e6b-24ae-45d7-9790-dcea719aba9c', 2, 1399, N'1001197', 103043.46455528103, 2559)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'97c0cc57-42c2-4af3-90d5-dcf251223c2e', 2, 1399, N'1001027', 626666.66666666663, 410)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1c143bd7-3877-48a8-865b-dd2054223b13', 1, 1399, N'1001253', 153485.80000000005, 17)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8df13bfa-6be7-460f-93af-dd2d92e76886', 1, 1399, N'1001639', 26424.706700226012, 2930)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4c065112-5141-43da-85c4-dd46753957bb', 2, 1399, N'1000182', 67517.23345588235, 1395)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8455af65-9d2f-4e4b-abb4-dd4fccd4e0f3', 2, 1399, N'1000100', 25699.948855730694, 3884)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6a735471-53cc-4970-907f-dd7b0640b327', 1, 1399, N'1000607', 55129.701508153943, 11055)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3901d7a9-48a2-4b7a-a858-dd8afa146fa1', 1, 1399, N'1000362', 65708.040000000008, 15)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9239163e-6339-4007-9478-dda9f5ad6f21', 1, 1399, N'1001244', 90486.9169878142, 869)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'de0e9038-d416-4a9e-b130-ddb9944306c7', 1, 1399, N'1000512', 13347.613013845787, 6229)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1d49133f-2378-4dd8-9f99-ddda82b37ac1', 1, 1399, N'1000852', 70963.290008688084, 2856)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a4d56c2e-22ca-4686-92f4-dde18288a951', 1, 1399, N'1001159', 198839.61, -16)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9f724888-12db-452d-a9ad-dde7af6c983c', 1, 1399, N'1000238', 51372.235618373736, 674)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9b81b04f-95e7-4855-9bef-de390f218fab', 1, 1399, N'1001452', 93578.09, 678)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5d52a893-526c-451a-94c6-de6496144c53', 2, 1399, N'1000521', 48300, 460)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c035ab1b-09da-4a6c-96e6-debef81cb367', 1, 1399, N'1001336', 66752.707147787136, 1409)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'986a184a-0141-4c0b-9115-dedc967f4edb', 1, 1399, N'1000962', 195744.83103988098, 1598)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'777f7485-8fa3-4cea-aaa5-df27b5c08783', 2, 1399, N'1000010', 13116.877690782736, 10832)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8efc5232-49dc-4fcd-9267-df3d4f3b67a2', 2, 1399, N'1000971', 41529.432989706344, 1702)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c57907d0-7a1a-409b-9766-df4a78a291b5', 1, 1399, N'1001239', 108786.1792029121, 534)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1ed9c9d8-2d1b-40b7-833b-df61cdddb2de', 1, 1399, N'1000330', 17065.682551449787, 7698)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'81bd5eed-0da5-476f-8797-df66bbef7b4b', 2, 1399, N'1001575', 122542.3429449494, 1734)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'28ac75f4-a68e-43d3-9e31-df6d712feda0', 1, 1399, N'1001037', 71888.519621020285, 2036)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'16faf71a-f8f5-4c3b-82bd-df782fd1cb2d', 2, 1399, N'1000153', 301509.43396226416, 7275)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9d9a1066-5a56-4a40-a6c6-df83fe615413', 1, 1399, N'1000756', 386664.50179515011, 5270)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a407db74-a40f-4900-8d87-df8a2c9f41fa', 2, 1399, N'1000282', 58919.625211286053, 2753)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f452dd01-b189-4ce6-b8b4-df8d3eac7703', 1, 1399, N'1001484', 69000, 127)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8fa7fffb-c99f-4e58-b838-df94be6cdc25', 1, 1399, N'1000508', 14184.474801832759, 535)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e8eb2209-934d-4da4-a303-df9e98fd7e4d', 1, 1399, N'1000117', 129885.07143319649, 1684)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'84852acf-d16f-453b-b593-dfab034210f1', 1, 1399, N'1000099', 55164.530976927635, 3405)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'767bce3d-bec8-4224-8ee9-dfd3c86c73c9', 1, 1399, N'1000430', 66754.488294670839, 1954)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e3662274-e3e9-46c2-908c-dfdab02a4a00', 1, 1399, N'1001585', 156880.23000000004, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'34fa0f7e-d6ea-4940-9d1b-e031900afa6d', 2, 1399, N'1000756', 459000, 4664)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0cc9ea26-235f-43b2-beae-e04fcd10268e', 1, 1399, N'1000296', 43254.745200469872, -93.002)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2b75cd59-54b0-4d4c-9fd4-e06452dfb7ee', 1, 1399, N'1001349', 48653.129959317885, 1467)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd0e25c41-74fc-4a74-b2ac-e07e06508f26', 2, 1399, N'1001443', 291651.376, 1106)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'16bd3368-e725-4f58-80de-e09ca7af2296', 1, 1399, N'1001172', 73659.04, 3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'63850fb4-32e1-4985-97f3-e0a01636d417', 1, 1399, N'1000665', 90388.77, 3)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'397ae772-e535-4882-ac4f-e0c020dfe0a6', 2, 1399, N'1000503', 14143.207912457603, 16219)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'50d51041-14d1-413d-ae65-e0c0ea224af1', 1, 1399, N'1000145', 115261.29581277378, 2194)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a248b194-2cef-4410-8eb3-e0c4e9265aeb', 2, 1399, N'1000706', 175724.82040538266, 2843)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5caa7ab7-c75d-4512-b3a2-e0d8e2db8892', 1, 1399, N'1001501', 42376.33, 5422)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e13e23fb-e713-4b39-91fc-e0f716580a33', 1, 1399, N'1000951', 157614.49808401224, 1121)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'83d401d4-6d80-4c3c-9812-e0fcf25b2017', 1, 1399, N'1000575', 7065.0146738857029, 3171.00145333)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c2091574-0b3d-48b3-88d0-e1844d7a88bc', 2, 1399, N'1001393', 52659.3784859139, 594)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'61560e0c-be05-419d-86dd-e1904dcce36c', 2, 1399, N'1000302', 45135.767912118528, 685)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'78cec105-d95c-4fa2-98c8-e1ac8effbefe', 2, 1399, N'1000147', 64401.915370416886, 3394)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a2342388-0dc9-4f34-b76e-e1c313f2fe26', 2, 1399, N'1000002', 33678.631251150866, 6630)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b0a6bdf7-9d32-4c0e-90df-e1d9327a98ae', 2, 1399, N'1001728', 45194.585589337774, 1626)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'202c51fa-98c7-4aac-aec0-e209a3309453', 2, 1399, N'1000835', 82289.471207992261, 815)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'579ab68e-94d5-45ce-989a-e22ad38cb5ca', 2, 1399, N'1000974', 7074.426877429607, 850)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4c510157-2beb-4776-9c2b-e2a83809072b', 1, 1399, N'1001627', 34531.444271665212, 8668)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c7ac2836-e94f-4e08-a891-e2b93eaef98d', 1, 1399, N'1001459', 55000, 9)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4c07149e-53f4-4743-8112-e2bd88a4133a', 1, 1399, N'1000184', 15000, -6)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'00c3b831-9124-428c-9df3-e2d97e42d1ad', 1, 1399, N'1001573', 190009.23765979285, 8903)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b38e3012-47e5-4eee-8fc0-e2f16173c76e', 1, 1399, N'1001084', 135757.51073303167, 852)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8a62beea-2bbd-4dcc-b97e-e2f8a5892f2a', 1, 1399, N'1001625', 53903.783418078288, 20641)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4712845e-c4b3-4600-8b11-e33dc803e57f', 2, 1399, N'1000916', 61109.640014917786, 5443)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b35f4cbc-839e-4111-8d4f-e369f813f171', 2, 1399, N'1000106', 108930.6502339709, 2258)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'36876b1a-253f-45f6-a74c-e3951f6cb773', 1, 1399, N'1000797', 21659.93, 13)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c459dbfd-c019-4200-8b14-e3ac39d0047d', 2, 1399, N'1000502', 3533.5504688201163, 6206)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b2454a58-d4d6-41d3-8f2e-e3cdca13eb65', 1, 1399, N'1001584', 156880.22494230772, 57)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b7b38959-38ab-41c2-bf0c-e406c29e1b5a', 1, 1399, N'1000817', 117205.69893541519, 2143)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2174738d-4aa3-4ec3-a29d-e4424237da60', 2, 1399, N'1000523', 64224.332352799313, 3803)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'eadaf959-a4c9-4082-98d6-e48832a2ccb3', 1, 1399, N'1000321', 261171.4869985577, 2953)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f22b0fb1-4072-44e3-8a9e-e4b02ab7b413', 2, 1399, N'1001089', 495570.11389521637, 1510)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'53e7c22f-85c1-44b8-a21c-e4b324a99a7f', 1, 1399, N'1001469', 200353.01000000004, 151)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e263d7d2-bc11-4e87-b852-e4b54ce50d55', 1, 1399, N'1001438', 11926.236346439071, 1985)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e87872ec-1d3c-4730-ae8e-e4c5315b06ba', 2, 1399, N'1001726', 223057.07407771639, 453)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5caf41df-26fd-4e63-8dd4-e4ee0cc10eed', 1, 1399, N'1001348', 28536.270059576098, 7852)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8a1ee62e-a626-4fba-b2d2-e52e8bf8e1c9', 1, 1399, N'1001227', 49985.895090645667, 5544)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c9babdb3-f39d-45d6-973b-e5496462eb61', 1, 1399, N'1001032', 42621.850883737512, 2271)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd5765882-b16a-44a8-aa4b-e55a86272672', 1, 1399, N'1000460', 103209.14029368364, 1720)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ecbc5075-3b91-4d8f-8007-e589f5aeec5b', 2, 1399, N'1000541', 143317.38651194383, 724)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fe8f01a7-eeac-49e5-be60-e5a86823e76a', 2, 1399, N'1000063', 36462.032109696942, 2709)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'af92fb83-0ce5-4eda-abb8-e5cc35bf1cda', 2, 1399, N'1000758', 76731.890091590336, 7061)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dcf5e14c-45f7-4581-bd2c-e5e5a5186bea', 2, 1399, N'1001336', 66617.5911505804, 735)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cf09c18b-b858-4a28-ba5f-e5ea5db0c619', 1, 1399, N'1001393', 44004.729521606205, 520)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f5e3e0a8-f78d-4819-9af8-e5ed7593eb73', 1, 1399, N'1001674', 188020, 6000)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0b4badd5-7486-4d26-9e0c-e60a489dc864', 2, 1399, N'1001698', 138000, 1227)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7e4d4161-d086-448d-a37b-e65613d61d9f', 1, 1399, N'1000540', 99716.311689523485, 1107)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7b9d47ed-5fd3-4572-9771-e6647721d9f3', 1, 1399, N'1000028', 95271.4579769756, 1741)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e828b9b6-d554-442c-a28d-e694a80f83ab', 2, 1399, N'1001416', 146257.26112963128, 1907)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d15c567-9420-4662-8349-e6981af4625c', 2, 1399, N'1000486', 231846.57092445661, 523)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9b29ef93-9a1a-4c39-8c09-e6da4b57070d', 2, 1399, N'1000864', 56834.647926526086, 1473)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'841e76e9-8871-415c-bc45-e6e614c14dd7', 2, 1399, N'1000951', 159335.02606134146, 1123)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'28ad01c1-5fd1-4945-bef7-e719033f49e9', 1, 1399, N'1001432', 93459.581730769234, 954)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b54455c4-b7db-4b51-9e8c-e7245d3fba69', 1, 1399, N'1000961', 255248.17884180325, 890)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'480567d2-ce99-48b1-802d-e73fafba0101', 1, 1399, N'1001068', 33369.115781046938, -10)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e2a1916c-67d3-44d0-9c3f-e7410717ff27', 2, 1399, N'1000526', 51671.603246167717, 3511)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'23c134a4-2bd6-41b8-bab5-e741bcbd40bd', 2, 1399, N'1000430', 66750, 1869)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'010a0439-ee2d-4b70-847d-e7481d4c6e72', 1, 1399, N'1000345', 71990.364468880638, 2261)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bb796b86-70a4-41a2-b4a1-e74b1cdd37c7', 2, 1399, N'1001631', 7065.19220589661, 20074)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f3fa2026-b2c2-4bbb-9dc9-e751e4c272ff', 1, 1399, N'1001229', 66631.084663385263, 3711)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd273a100-49d0-4957-80e0-e7547500502c', 1, 1399, N'1000981', 115016.89130375431, 1607)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9c49a0d6-3411-4f30-b6c5-e75ce39a5ee8', 2, 1399, N'1001528', 688073.394, 386)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'98b3dc0f-55d0-4f54-b5a8-e7856a7a309e', 1, 1399, N'1001385', 73403.58766444122, 2390)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7d3adf51-891c-4a02-9418-e7c22cc989e6', 1, 1399, N'1000826', 62471.61, 1)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8a45d90c-59a9-415c-a1dc-e7dfa08ad6b5', 2, 1399, N'1000887', 875000, 90)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'472cd66a-b8f2-4fd5-9853-e7e1bb8c28f6', 1, 1399, N'1001616', 173116.44170266244, 1869)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e302589d-127c-48be-bce0-e7f89bf9d42d', 1, 1399, N'1000180', 67526.104417670678, 1296)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8d5b8a93-73b5-4a94-8441-e7fbf0affbe1', 1, 1399, N'1000328', 44907.139647161981, 8357)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7eb646fe-2b53-44b9-883c-e81854a445d3', 2, 1399, N'1000757', 76731.890091590336, 4791)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c3ca2b6e-3ebe-49f4-b3ab-e8879902bd9b', 2, 1399, N'1000453', 112474.89227263157, 3565)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8c549708-ec4c-45f7-bce9-e911f3581435', 1, 1399, N'1000952', 195894.4535, -5)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'563f2251-cd8f-4b89-97ae-e96fadabcd4c', 2, 1399, N'1001745', 48380, 10373)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f42399ce-2110-476c-9c9f-e97795c5eaba', 2, 1399, N'1001352', 34219.476105269925, 5833)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cba4e662-5964-47f1-a660-e982a66c5f41', 2, 1399, N'1000120', 234862.50981955859, 1721)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6036cfad-8ce9-464f-9d31-e98c46624bb0', 1, 1399, N'1001344', 26994.189399005216, 5402)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'599c05e4-9ba1-4939-9b64-e98e2fbd0685', 1, 1399, N'1001578', 46888.301677852374, 878)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ffd23679-5362-4e73-af31-e9c5619aad9a', 1, 1399, N'1001155', 28499.969999999998, 148)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'52014770-f9da-4d89-8fc9-e9ce7f12277f', 1, 1399, N'1000876', 489048.78845618025, 1030)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'192f6399-c29f-4aa2-96b4-ea271c5462f3', 2, 1399, N'1000522', 16055.260795456601, 22283)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd3cb6bd7-27db-4b7d-8496-ea37b8811ad5', 1, 1399, N'1000648', 258013.49677777779, 31)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'82a13fba-1e58-47f6-b084-ea60ab027a27', 2, 1399, N'1001315', 115561.47303763632, 3404.935)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd3309523-63da-4dad-b8b6-ea8ec0e214f7', 1, 1399, N'1000479', 84908.8407719072, 2459)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f6308d61-9841-4c66-92c2-eaa9a69c6391', 1, 1399, N'1000126', 23853.189350687437, 9511)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1e03a24b-00e7-4ea6-8c5d-eab1c722a3ae', 2, 1399, N'1000239', 77079.301960335055, 1104)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5486cfe7-1d67-4df6-8ad7-ead8fb9bf9a1', 1, 1399, N'1001072', 274050, 14)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9b226490-7c73-42e6-be11-eb271837ffcb', 1, 1399, N'1000002', 33678.456381991033, 4612)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0f153a1d-c0bb-4174-8edd-eb5fdbb544eb', 2, 1399, N'1000970', 560000, 3227)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'846c8381-5c18-4504-a407-eb75e05420f6', 1, 1399, N'1000814', 559076.164716312, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a44fbfb9-da7c-4456-b2d8-eb88adde5728', 1, 1399, N'1000861', 100483.74494190412, 1484)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6a06de59-6544-42d8-ad36-eb95b9335615', 1, 1399, N'1000314', 97853.946888775288, 600)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'02f53fc5-f5ee-462d-afe0-ebaf6cedd999', 1, 1399, N'1001314', 115595.76002814919, 1576)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'716c6e3d-677a-4ce6-8208-ebaf9af635dd', 1, 1399, N'1000429', 115621.64002929616, 1031)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'031e61dc-b207-4f6e-828b-ebc8580a18a0', 2, 1399, N'1001554', 99495.413, 108)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c5d15f1f-6b19-4c6f-850e-ebca0db6354c', 1, 1399, N'1001554', 94504.809999999983, 127)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd7fc51cd-6984-477f-8bac-ebdc5b55ed32', 1, 1399, N'1000689', 331728.74076095776, 982)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8d2adbb6-ca95-4a00-b47b-ebe7176c42c4', 2, 1399, N'1000516', 57067.64281109169, 1487)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e60ca56a-4173-4614-8973-ebf299d5e609', 1, 1399, N'1000452', 66637.087695013528, 12827)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c44e29fa-90b6-4783-a81f-ec34e328bdeb', 1, 1399, N'1000087', 21801.721078064809, 2087)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'45daa220-a937-4372-881a-ec3c80d355d1', 1, 1399, N'1000647', 437747.734160551, 222)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'187e24fc-fcb5-4b57-92bf-ec793ebcce52', 2, 1399, N'1000450', 15596.33, 7241)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e9619c25-de72-4a76-9962-ec94c83d0c1b', 2, 1399, N'1001349', 49946.061709063513, 1482)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9641a712-afe2-4852-a94e-ecb1918a032d', 2, 1399, N'1000771', 72827.121752545063, 307)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8f6444b5-e1aa-4a1f-a46c-ecd13d33733c', 2, 1399, N'1000484', 117731.32824215495, 3327)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dcc3e91f-88dd-4e23-a608-ecd511583b78', 1, 1399, N'1000186', 29996.855460817274, 725)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f42c3dea-1f31-4b93-b16b-ed381f2c3ebe', 1, 1399, N'1000520', 44807.676766169105, 510)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'75ff0ffa-8ebb-4f0a-8009-ed7ff871bd34', 1, 1399, N'1001586', 363302, 2)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'719a71b6-7daf-4f27-9b0b-ed8aec162c6f', 2, 1399, N'1000896', 33027.063543277865, 2352)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c86109a2-9485-4cc3-961f-edd28907bab4', 1, 1399, N'1001209', 33661.687916693139, 4846)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7610d018-4276-4b79-8654-eddf1c7f36c6', 1, 1399, N'1001468', 61678.368344905561, 1704)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1da72aab-504d-47af-80c4-ede864ceb400', 1, 1399, N'1000010', 13173.329276653474, 6813)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c0d0736f-8a76-41c3-ab10-ee347391e56e', 2, 1399, N'1000400', 19200, 6991)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd5cea3e4-4977-45e4-9949-ee7c4ca8f9af', 2, 1399, N'1000252', 82364.123911303424, 2025)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b88ddd47-6b49-4525-9296-eeae52e82f6e', 1, 1399, N'1000473', 314904.10958904109, 68)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'59adbfb8-f227-4f72-95d3-eeb0c23b419e', 2, 1399, N'1000145', 136541.73981713076, 2745)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'676b15fc-ba2c-416f-96ae-eebaa55d7e49', 2, 1399, N'1001566', 79983.522260411861, 2747)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'322787af-7f5d-4d08-bb4e-eef633f13fb3', 1, 1399, N'1000501', 18913.443056942524, 8154)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'782c928b-e6b9-4f94-b2b1-eefd4d0b6a6d', 2, 1399, N'1001662', 123906.835826548, 2089)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5982813e-e1fe-469b-92f0-ef32dfeabf32', 2, 1399, N'1001560', 71559.633, 1783)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dd85f121-11af-45c9-bc20-ef9f71bbed30', 2, 1399, N'1000210', 630137.29977116711, 2297)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9954c616-d1b9-4b50-ada6-efc4b2bb3b96', 1, 1399, N'1000589', 35327.235744571895, 840.00036333)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'92331865-3744-4bf9-bbe5-efc92daa744a', 1, 1399, N'1001661', 106920, 1028)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'320fbdb3-9e73-41eb-81b8-efd27762dbf4', 1, 1399, N'1000357', 150155.06000000003, 18)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'729737fa-6136-4d66-a6cb-efdc8a1ba3e9', 2, 1399, N'1000149', 245455.83233377486, 3730)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4559e9ec-ff65-4666-b2fc-effdc247717d', 1, 1399, N'1000556', 161007.94999999998, -13)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'08e8cc5d-8cdb-4db9-99df-f005c8f3b49d', 1, 1399, N'1001415', 149928.50929830674, 1139)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cc5247eb-a8e2-4044-a4a4-f044a784177d', 2, 1399, N'1000237', 77063.699005993243, 1346)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2a24bbe9-df68-4e50-9ba8-f056084a1569', 2, 1399, N'1000026', 16656.993549790539, 8058)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'12d59e9c-76a9-452f-a522-f05cb8cc2825', 1, 1399, N'1000142', 30018.159989700092, 2672)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'49552990-f2f7-4560-9f02-f073491e2d40', 2, 1399, N'1000005', 13116.504948057964, 19521)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'77b91dae-e0ad-45f5-8a9c-f0af942f9a42', 1, 1399, N'1000061', 39540.69614262259, 11106)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'24bc037c-8ceb-4681-8b46-f0b30f9b52fa', 2, 1399, N'1000187', 48774.204756022235, 801)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'35757a2f-d172-42b1-ae66-f0bcb947bb4b', 2, 1399, N'1001376', 104182.0800361341, 1181)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2ca829e1-cdbc-4af2-b74a-f0e9b4e22a46', 1, 1399, N'1001610', 86748.810295109259, 1432)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'932f646b-f96a-4994-b70f-f131a7ead334', 2, 1399, N'1001645', 126605, 1173)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5745529f-ad87-4655-884c-f1ac55c0dcb3', 2, 1399, N'1001361', 96918.857637276669, 870)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'61e7797a-8c59-4ac7-91e4-f1be205d8c57', 1, 1399, N'1000004', 20560.119971802433, 5564)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b387b1a9-f7e3-4148-b930-f1c9da78aed7', 2, 1399, N'1000085', 50695.609350562954, 5279)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'df31eeff-de38-418e-95b9-f214047090f5', 2, 1399, N'1000518', 25206.595538312318, 514)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9fc3836e-3979-4fa8-840b-f22aa85abc4d', 1, 1399, N'1000640', 251607.14080882171, 4666)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e8fe3ca7-f767-40e2-84dd-f2566d7b9cf3', 1, 1399, N'1000870', 41284.67, 27)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'73dc87c6-e5e1-4273-82d1-f266c0df8656', 1, 1399, N'1000571', 65999.989999999991, 5164)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'87b359bc-2de3-4491-b0c7-f279712df189', 1, 1399, N'1001566', 79952.13262818208, 2881)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cfa432e1-e28e-4909-847b-f2889607295b', 1, 1399, N'1001226', 127213.53846255699, 2296)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5ac10a89-4a94-445d-a93f-f2af9890e1c9', 2, 1399, N'1001260', 29725.43579243559, 4178)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1826017d-dde2-4607-ac23-f2bd083377e2', 2, 1399, N'1000925', 224815.13631246923, 944)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'03326c90-2e71-451d-a7b4-f3032523ae58', 1, 1399, N'1001453', 29357.260000000002, 121)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ba3002d2-fb11-4024-aa78-f304c2d6643e', 1, 1399, N'1001476', 137613.79999999996, 415)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e3703902-e8c1-4555-8fed-f3297459c4fe', 2, 1399, N'1001670', 53202.149367433005, 9016)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8869f062-c3c8-4996-9695-f33907f1dfee', 1, 1399, N'1000777', 103874.88288673568, 2267)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'291cf974-0bcb-4d67-82e5-f34dc21dc129', 2, 1399, N'1001366', 113433.24663754286, 2220)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b17cdc10-8307-4a44-97a6-f362bb042fe4', 2, 1399, N'1000914', 250017.44615437865, 1161)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5b47aff3-c159-4415-93ae-f37f1610d41c', 1, 1399, N'1001185', 116921.71083217108, 2620)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4c9a3f61-cb5d-4626-87cb-f3b68d516823', 1, 1399, N'1000030', 84463.809566301352, 1388)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'161f150d-cba0-4dac-af22-f3b791efc3c5', 2, 1399, N'1000890', 16901.584184054456, 8251)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e976b17a-748c-483a-b089-f3bf2740746d', 1, 1399, N'1000342', 190450.97999999998, 12)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc681182-4cf9-4d07-9086-f3dbdc38f17f', 2, 1399, N'1000475', 12385.321, 3574)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a4208a3a-8059-4b27-a96b-f45be82bddfd', 1, 1399, N'1000048', 92412.170000000013, 28)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2bead548-eed7-4c87-8337-f47814f94ffb', 1, 1399, N'1000939', 33884.8, 191)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'853eb1d6-cbc4-46e6-a523-f4b46d3f248f', 2, 1399, N'1000964', 151376.147, 4392)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'796cd624-d370-4cd8-9c5b-f4f81864ef49', 1, 1399, N'1001031', 19266.18, 198)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d5029a0-a32c-40fc-875c-f4f8eb109621', 1, 1399, N'1001088', 163166.35702695418, 9676)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1d77a243-7585-4139-be06-f525bc913be8', 1, 1399, N'1000625', 20647.16, 255)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dbda239e-e66d-4a13-bc9e-f53fadd051fc', 1, 1399, N'1001564', 69492.884827283939, 1363)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6a7dad06-ec5d-46e5-961f-f5494dc8355e', 2, 1399, N'1000051', 123486.95264864866, 521)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cd076cf4-d723-41b3-8c9f-f5497aaa260d', 1, 1399, N'1000354', 50564.400000000009, 2777)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'71f96bff-1355-4235-82c8-f554ab3c6907', 1, 1399, N'1000281', 15541.998858563646, 6996)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cc0be607-5515-4308-93b0-f57d89bb656d', 2, 1399, N'1000603', 64793.3000495044, 2175)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'40d0f051-8564-4d52-94ca-f58d151f938e', 1, 1399, N'1001062', 10727.484660010488, 15237)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc5815b1-5032-4b68-a558-f5ce9194abe2', 2, 1399, N'1000881', 38539.0997446089, 4020)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3a3463d6-3997-4cba-817f-f5d007914fc4', 2, 1399, N'1001559', 162293.578, 426)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3a5e706a-5391-4337-a38b-f5d49a8e6914', 1, 1399, N'1001280', 63965.474225819518, 1665)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'44bee3cb-96d9-4593-9cdb-f5e58623e658', 1, 1399, N'1000013', 28303.906193206771, 4970)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4e7c9606-1a5a-4545-abad-f5f26d3bb88d', 1, 1399, N'1000441', 69595.263490291269, 3097)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e07c103e-e901-4cf4-aa6e-f603b621057b', 2, 1399, N'1001357', 118681.3712710454, 3991)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2ed08cec-e37a-4501-8663-f612d56cd9fc', 2, 1399, N'1000950', 169312.18674774954, 1085)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3f58c3f4-6129-4eb6-9631-f6175b18c926', 1, 1399, N'1000403', 138980.58032040868, 3793)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd1ca6eac-e337-490d-9759-f640c49b0a85', 1, 1399, N'1000195', 41503.916400008391, 6163)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'14f370e3-46a5-4ade-95e9-f64641a9387a', 2, 1399, N'1001583', 182568.807, 753)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'2e920954-6fef-46a8-a8f4-f64643a95c22', 2, 1399, N'1001658', 87106.650956904748, 2184)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5e6ff84c-369a-4734-9a0a-f6705ca27110', 1, 1399, N'1001499', 65863.637566738325, 4701)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'78de3964-1b92-4bab-80c1-f6b073f2bfac', 1, 1399, N'1000833', 141948.00534101905, 305)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5ff10b5b-4060-47be-a009-f6c637221583', 1, 1399, N'1001384', 391789.59, 12)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cc2580da-cf85-4e37-b801-f6e8b5e67c9f', 2, 1399, N'1001406', 57186.543999999994, 5056)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'5623d79b-2b97-412b-8c67-f6fcc8c3c78e', 2, 1399, N'1000627', 16055.046, 5842)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7b08ecd0-9c1a-42ef-b460-f726719f2db4', 1, 1399, N'1000770', 39862.633854395717, 4544)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'71e6beb5-4657-4ca1-be45-f745db4a5f85', 1, 1399, N'1000620', 139117.79, 495)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a5e73a1d-a633-4cd4-903e-f75e0ee4b111', 2, 1399, N'1001719', 79197.058099413611, 1761)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'96b61e21-4bab-4174-b1d2-f79350e3068c', 1, 1399, N'1001231', 93829.091024058609, 1448)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bfb4285d-88c4-4499-8fbe-f7a208c2a723', 1, 1399, N'1001173', 69000, -479)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'254e33e6-7e75-49be-b5cf-f7cc845e207e', 1, 1399, N'1001657', 59793.845720136596, 2331)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6e388251-7d65-43cc-9af2-f7d1aa2971f6', 1, 1399, N'1000147', 54616.328903516522, 2100)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'068d1e49-9d4e-4302-b623-f7d3073113cb', 2, 1399, N'1000555', 184154.03517679556, 1144)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'911f2a21-4802-4977-a646-f7e020c99a78', 2, 1399, N'1000109', 37914.13505605785, 2811)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3f54c330-dc8a-4ff6-862d-f8186be35546', 1, 1399, N'1001559', 161546.01000000004, 453)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'341232b0-3e7a-498f-95cc-f81c6e5c29a1', 2, 1399, N'1001334', 19503.129472334978, 3002)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'01331ac8-8145-4934-90b9-f8a2f78dd375', 2, 1399, N'1000709', 462593.92554877332, 1473)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'45f07393-c7dc-4677-b20e-f8d1f4d9a706', 1, 1399, N'1001270', 49645.3787174468, 2761)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'e1289ca5-c371-4e39-b8ca-f8da959d07db', 1, 1399, N'1001069', 13394.83, 32)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b6fc095f-9cf1-47b5-8ae7-f8e0d6ce41c9', 2, 1399, N'1001588', 329357.798, 193)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'49838bce-140f-4cb6-808b-f8e63d432ed7', 2, 1399, N'1001564', 69490.696455855126, 1373)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c1dc0431-fb01-4e4d-a7de-f8f0463597c7', 2, 1399, N'1001706', 28256.833063083479, 2640)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'80df532e-c0bc-4349-b16f-f911c989a662', 1, 1399, N'1000561', 408781.82533559896, 192)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'00cab8fb-1c26-4628-b343-f96f87a31a24', 2, 1399, N'1000976', 28330.72471818958, 317)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'93079a4c-01e0-4d55-a980-f98c959ec01b', 2, 1399, N'1001415', 143725.23951327096, 1675)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'66fa78cd-61ca-4780-86b5-f9a799130c9c', 2, 1399, N'1001080', 74296.1193948887, 2746)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'de4ab473-14b3-414a-b57e-fa03cf0b9ead', 2, 1399, N'1000286', 23523.777405873847, 2982)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8d49bf52-fc9e-4a38-abfc-fa108b860416', 1, 1399, N'1000519', 49000.088739495819, 320)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'94d0a4dc-d34f-4cbe-a1b7-fa12e97db044', 2, 1399, N'1001298', 102657.26971917585, 265)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'73a0456a-fbc0-4d5b-90af-fa1bec19da77', 1, 1399, N'1000700', 104465.60604006423, 4236)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'85eecf19-55b9-405a-937b-fa3de340504d', 1, 1399, N'1000766', 50436.8210137023, 1365)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'7116e211-c5fa-4676-8d8c-fa4381fba50e', 2, 1399, N'1000981', 115051.26640219717, 3280)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'628e297b-a39f-4a2b-8885-fa46355fb3fa', 1, 1399, N'1001463', 45000, 4)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'431e947b-b452-44a2-93a6-fa64c758f3bd', 1, 1399, N'1001034', 85562.543238196726, 1949)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ca62be2b-762d-4d0d-917e-fae74b7cde27', 2, 1399, N'1000022', 46802.85253277835, 8998)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd648ee38-ddd0-46f8-bc00-fae939cf4409', 1, 1399, N'1001545', 100090.08, 559)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4aee9830-8809-401d-a76b-faf0845353eb', 1, 1399, N'1001103', 32110, 35)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd590f16b-94ec-4629-86f4-fb14379f55ee', 1, 1399, N'1000877', 166079.29498994388, 875)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6d023cc6-22ed-4a98-b5cf-fb2217f8cb38', 1, 1399, N'1000957', 113412.11046076893, 1126)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1322fe54-d76b-4ace-93db-fb3554c13d77', 2, 1399, N'1001636', 23857.315313653475, 2678)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'9f2f8d51-f90c-41bf-8b2f-fb40d067648d', 2, 1399, N'1001419', 37139.392793239334, 11141)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c1ecacc0-a574-48f9-a0a9-fb4597d4fc25', 2, 1399, N'1001624', 340000, 890)
GO

In [0]:
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'4d90e714-5bd2-48c7-bfc0-fb50e6f38beb', 1, 1399, N'1000323', 261172.76056664236, 2079)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'1194febb-e5f3-4f9b-8e10-fb5f49edb902', 1, 1399, N'1000024', 14009.175628933404, 6683)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'03de9d56-ae0f-4f1c-b01f-fb63868051d0', 1, 1399, N'1000856', 87832.38, -7)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd239221f-81f3-41b8-971b-fba4c2eb244c', 1, 1399, N'1000181', 26250, 387)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'504e4199-8ba9-4b0f-a628-fba8045b6ba3', 1, 1399, N'1000247', 23696.34351177136, 4847)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'6ea01993-a75e-49de-8d1f-fbea47affbb8', 2, 1399, N'1001687', 152151.62888455187, 6201)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'bc7c3cde-080e-483b-82c8-fbeeed204d34', 2, 1399, N'1000639', 53185.431210624709, 845)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'cefbae0e-6d14-4553-bd94-fc0bf9d087ba', 2, 1399, N'1000472', 9907.94024664443, 12626)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd53d2944-e9c3-45f2-a4c2-fc3fecf8f025', 1, 1399, N'1001013', 118503, -182)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'd6fea4da-06cd-4958-9608-fc6af31d527f', 2, 1399, N'1000432', 20189.600408395978, 3128)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc2e9371-e9fc-402d-bed9-fc7beb6565c8', 1, 1399, N'1000984', 51755.37251037408, 3213)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b0807f98-7811-4dd4-8836-fc9c06f35a72', 1, 1399, N'1001684', 201835.00000000009, 3180)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'726fd7f9-67eb-43af-8ddb-fce91da29067', 1, 1399, N'1000251', 85320.615073112014, 787)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'ba2478ca-23f6-400f-9cee-fd0e3a9e0774', 1, 1399, N'1001351', 49230.108157926283, 1791)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fc30271c-24e6-4656-831f-fd57eda18540', 1, 1399, N'1000747', 41723.73, 42)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3954106f-619a-446f-8198-fd6fc7e7ee9e', 1, 1399, N'1000131', 71284.536162873235, 657)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'f1a1bbaf-9caf-440c-bf29-fd74c21c41ca', 1, 1399, N'1000565', 99561.500023156244, 1692)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'0ce6be72-9110-4e11-b499-fd89f99e0b45', 1, 1399, N'1001295', 77520.729238329252, 196)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'8ba10f01-bde8-4149-82e5-fdc3e3e65952', 2, 1399, N'1000118', 185021.67726146188, 1397)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'381d0ca4-2696-49d1-8c22-fdc4bb63dbee', 1, 1399, N'1001680', 76150.424618883873, 4787)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fece5093-e064-4108-aed8-fe3da2409274', 2, 1399, N'1001105', 2933903.1507969364, 357)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'3995eaf2-bba2-4ca8-a113-fe4fbe9082e7', 2, 1399, N'1000113', 229513.9318885449, 2396)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'85d28f4e-2ffc-43f0-8e6b-fe6da2788ede', 2, 1399, N'1000710', 462659.15127214463, 1312)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'203e5afa-de1d-4dd4-b587-fe97f0ffddef', 1, 1399, N'1000550', 138498.762131134, 1607)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'694021da-9ca4-42cb-a98a-feaed0a7a268', 1, 1399, N'1000950', 167464.81519846531, 1074)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'66faad83-f385-42ae-bf61-fedf437c4f9b', 1, 1399, N'1001591', 132999.87, 16)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'b201b744-6e64-4174-bb19-feef91737f38', 1, 1399, N'1001228', 74670.57, 67)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'c46f7bcc-6ac6-4407-bc9f-ff1b7a011997', 2, 1399, N'1000544', 113944.72673177089, 507)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'638caf96-419c-484e-b545-ff2192c1292b', 2, 1399, N'1000144', 276706.80474762159, 1813)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'97f68538-8688-447d-8950-ff305ecc4498', 1, 1399, N'1000288', 22022.947276583, 586)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'344b194d-a18b-4f4f-9d33-ff3e8abdf6b0', 1, 1399, N'1000425', 160550.68999999997, 11)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'a897ba8e-d940-41d3-bb76-ff4204decbed', 1, 1399, N'1000513', 32879.994254757716, 6187)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'314c8cde-d4c9-4827-bfbf-ff8ed8085d2a', 1, 1399, N'1000361', 115051.87122045597, 1198)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'11db1dbf-7256-41d0-a944-ffa8677aa2b1', 2, 1399, N'1001062', 10734.325972410023, 16442)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'fb3a7b1a-bd54-4605-9de3-ffcc75d376bc', 1, 1399, N'1000503', 10596.420493721376, 22554)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'955c8869-7c99-48ae-83f5-ffe6310fc2e7', 2, 1399, N'1000632', 19522.001177847655, 4151)
INSERT [dbo].[TERP_COST] ([GUID], [MONTH], [YEAR], [CODE], [COST], [LAST_QUANTITY]) VALUES (N'dc6ccb30-b12c-4d74-9bca-fff9f09d0ff9', 2, 1399, N'1000330', 17069.632678122529, 8745)
GO

# [dbo].[TERP_SEMSI_PERIOD]

In [0]:
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'5de184e1-9fd3-4d77-9550-182037e7f489', 1399, 2, N'Ordibehesht', N'April-May', CAST(N'2020-04-20T00:00:00.000' AS DateTime), CAST(N'2020-05-20T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'2fcb18cb-b025-4201-8596-189e34bab12e', 1400, 6, N'Shahrivar', N'Aug-Sep', CAST(N'2021-08-23T00:00:00.000' AS DateTime), CAST(N'2021-09-22T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'40386a79-8aaf-4bc9-8bbf-1ee940142813', 1399, 8, N'Aban', N'Oct-Nov', CAST(N'2020-10-22T00:00:00.000' AS DateTime), CAST(N'2020-11-20T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'5012aa75-a84a-40aa-8a07-20bbde8cb801', 1400, 8, N'Aban', N'Oct-Nov', CAST(N'2021-10-23T00:00:00.000' AS DateTime), CAST(N'2021-11-21T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'16845109-3035-41d2-b7f4-2bea18bd43f0', 1399, 11, N'Bahman', N'Jan-Feb', CAST(N'2021-01-20T00:00:00.000' AS DateTime), CAST(N'2021-02-18T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'99a8bcda-8a67-4b1f-87df-2c9cb7c7a75f', 1399, 7, N'Mehr', N'Sep-Nov', CAST(N'2020-09-22T00:00:00.000' AS DateTime), CAST(N'2020-10-21T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'cd5b1ce1-810b-4c47-8536-37f544a296e0', 1400, 4, N'Tir', N'Jun-July', CAST(N'2021-06-22T00:00:00.000' AS DateTime), CAST(N'2021-07-22T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'b86ebf76-0b7d-49b7-85d6-3cbc86b292c0', 1399, 9, N'Azar', N'Nov-Dec', CAST(N'2020-11-21T00:00:00.000' AS DateTime), CAST(N'2020-12-20T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'c24b2014-0773-49e3-84ae-446a24149b7b', 1399, 3, N'Khordad', N'May-Jun', CAST(N'2020-05-21T00:00:00.000' AS DateTime), CAST(N'2020-06-20T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'02eca2e0-52e7-4f0b-936d-462840ea9250', 1400, 9, N'Azar', N'Nov-Dec', CAST(N'2021-11-22T00:00:00.000' AS DateTime), CAST(N'2021-12-21T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'bb91c14e-d76c-4850-9505-4a0cd599bd5f', 1400, 11, N'Bahman', N'Jan-Feb', CAST(N'2022-01-21T00:00:00.000' AS DateTime), CAST(N'2022-02-19T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'568e1ffc-41ff-4894-b6e1-59d3f77d427e', 1399, 5, N'Mordad', N'July-Aug', CAST(N'2020-07-22T00:00:00.000' AS DateTime), CAST(N'2020-08-21T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'74913b3d-7d20-4a41-ba78-5cd4c373c228', 1400, 12, N'Esfand', N'Feb-Mar', CAST(N'2022-02-20T00:00:00.000' AS DateTime), CAST(N'2022-03-20T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'9d6dff9b-2888-448d-9052-5f8cbcea983d', 1399, 1, N'Farvardin', N'March-April', CAST(N'2020-03-19T00:00:00.000' AS DateTime), CAST(N'2020-04-19T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'7e4dec7d-2b8c-44bf-95a1-61e39c1d3a97', 1400, 10, N'Dey', N'Dec-Jan', CAST(N'2021-12-22T00:00:00.000' AS DateTime), CAST(N'2022-01-20T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'875cdbcf-6ae3-476b-9345-9f358cf0c24c', 1400, 5, N'Mordad', N'July-Aug', CAST(N'2021-07-23T00:00:00.000' AS DateTime), CAST(N'2021-08-22T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'674df1a7-6bf7-4a87-9191-9fdd736b7138', 1399, 12, N'Esfand', N'Feb-Mar', CAST(N'2021-02-19T00:00:00.000' AS DateTime), CAST(N'2021-03-20T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'25bd7072-9933-4200-8d52-b7f123811e65', 1399, 6, N'Shahrivar', N'Aug-Sep', CAST(N'2020-08-22T00:00:00.000' AS DateTime), CAST(N'2020-09-21T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'718cc65a-8013-4452-ada7-b8173dadca5f', 1400, 1, N'Farvardin', N'March-April', CAST(N'2021-03-20T00:00:00.000' AS DateTime), CAST(N'2021-04-20T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'6175be44-7514-4c1d-8a81-baf7684394aa', 1399, 4, N'Tir', N'Jun-July', CAST(N'2020-06-21T00:00:00.000' AS DateTime), CAST(N'2020-07-21T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'7401375e-a0fc-48d7-9dec-c39b93320929', 1400, 2, N'Ordibehesht', N'April-May', CAST(N'2021-04-21T00:00:00.000' AS DateTime), CAST(N'2021-05-21T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'f0e475d9-9bf5-48ce-8400-cd4fd48db876', 1399, 10, N'Dey', N'Dec-Jan', CAST(N'2020-12-21T00:00:00.000' AS DateTime), CAST(N'2021-01-19T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'030dc269-5a55-4f8a-9820-f3d0a9bcfbf1', 1400, 7, N'Mehr', N'Sep-Nov', CAST(N'2021-09-23T00:00:00.000' AS DateTime), CAST(N'2021-10-22T00:00:00.000' AS DateTime))
INSERT [dbo].[TERP_SEMSI_PERIOD] ([GUID], [YEAR], [MONTH], [NAME], [MILADI], [START_DATE], [END_DATE]) VALUES (N'0f5167f9-0ed6-428f-ab27-f3d667d65051', 1400, 3, N'Khordad', N'May-Jun', CAST(N'2021-05-22T00:00:00.000' AS DateTime), CAST(N'2021-06-21T00:00:00.000' AS DateTime))
GO

# [DF_TERP_COST_GUID]

In [0]:
ALTER TABLE [dbo].[TERP_COST] ADD  CONSTRAINT [DF_TERP_COST_GUID]  DEFAULT (newid()) FOR [GUID]
GO

# [DF_TERP_SEMSI_PERIOD_GUID]

In [0]:
ALTER TABLE [dbo].[TERP_SEMSI_PERIOD] ADD  CONSTRAINT [DF_TERP_SEMSI_PERIOD_GUID]  DEFAULT (newid()) FOR [GUID]
GO